#!/usr/bin/env bash
set -euo pipefail

# SourceBridge Demo — Three-Mode Hybrid Demo Script
#
# Mode 1: Zero-config (Docker only, indexes sample repo)
#   ./demo.sh
#
# Mode 2: Local Ollama (auto-detected, generates AI artifacts)
#   ./demo.sh                # Ollama auto-detected at localhost:11434
#
# Mode 3: Cloud API key (best quality AI generation)
#   SOURCEBRIDGE_LLM_API_KEY=sk-ant-... ./demo.sh
#   SOURCEBRIDGE_LLM_PROVIDER=openai SOURCEBRIDGE_LLM_API_KEY=sk-... ./demo.sh

# ── Color Output ──────────────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

info()    { echo -e "${BLUE}▸${NC} $*"; }
success() { echo -e "${GREEN}✓${NC} $*"; }
warn()    { echo -e "${YELLOW}▹${NC} $*"; }
fail()    { echo -e "${RED}✗${NC} $*"; exit 1; }
header()  { echo -e "\n${BOLD}${CYAN}$*${NC}\n"; }

# ── Configuration ─────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEMO_PASSWORD="demo-pass"
API_PORT="${SOURCEBRIDGE_API_PORT:-8080}"
WEB_PORT="${SOURCEBRIDGE_WEB_PORT:-3000}"
API_URL="http://localhost:${API_PORT}"
WEB_URL="http://localhost:${WEB_PORT}"
HEALTH_TIMEOUT=120
SAMPLE_REPO_NAME="acme-api"
SAMPLE_REPO_PATH="/demo-repos/acme-api"

# ── Prerequisite Checks ──────────────────────────────────────────────────────

header "SourceBridge Demo"

# Check Docker
if ! command -v docker &>/dev/null; then
  fail "Docker is not installed. Install it from https://docker.com and try again."
fi

if ! docker info &>/dev/null 2>&1; then
  fail "Docker daemon is not running. Start Docker Desktop and try again."
fi

# Check Docker Compose
if ! docker compose version &>/dev/null 2>&1; then
  fail "Docker Compose v2 not found. Update Docker Desktop or install the compose plugin."
fi

success "Docker is installed and running"

# Check ports
check_port() {
  if lsof -Pi ":$1" -sTCP:LISTEN -t &>/dev/null 2>&1; then
    fail "Port $1 is already in use. Stop the process using it, or set SOURCEBRIDGE_${2}_PORT to use a different port."
  fi
}

check_port "$API_PORT" "API"
check_port "$WEB_PORT" "WEB"
success "Ports ${API_PORT} and ${WEB_PORT} are available"

# ── Detect LLM Mode ──────────────────────────────────────────────────────────

LLM_MODE="none"
LLM_DETAIL=""

if [[ -n "${SOURCEBRIDGE_LLM_API_KEY:-}" ]]; then
  LLM_MODE="cloud"
  PROVIDER="${SOURCEBRIDGE_LLM_PROVIDER:-anthropic}"
  LLM_DETAIL="Using ${PROVIDER} (cloud API key provided)"
elif curl -sf http://localhost:11434/api/tags &>/dev/null 2>&1; then
  LLM_MODE="ollama"
  LLM_DETAIL="Ollama detected at localhost:11434"
fi

case "$LLM_MODE" in
  cloud)
    success "$LLM_DETAIL"
    info "AI-powered artifacts (cliff notes, code tours, learning paths) will be generated automatically"
    ;;
  ollama)
    success "$LLM_DETAIL"
    info "AI-powered artifacts will be generated using your local Ollama models"
    ;;
  none)
    warn "No LLM detected (no API key, no Ollama)"
    info "The demo will index the sample repo — you'll see the file tree, symbols, and structure"
    info "For AI-generated cliff notes and code tours, either:"
    info "  • Install Ollama (https://ollama.com) and pull a model: ollama pull qwen3:32b"
    info "  • Or set SOURCEBRIDGE_LLM_API_KEY=your-key and re-run this script"
    ;;
esac

# ── Start Services ────────────────────────────────────────────────────────────

header "Starting SourceBridge services..."

# Create demo compose override to mount sample repo
OVERRIDE_FILE="${SCRIPT_DIR}/docker-compose.demo.yml"
cat > "$OVERRIDE_FILE" <<YAML
# Auto-generated by demo.sh — mounts sample repo, fixes permissions, and configures LLM
services:
  surrealdb:
    user: root
    healthcheck:
      test: ["CMD", "/surreal", "is-ready", "--endpoint", "http://localhost:8000"]
      interval: 5s
      timeout: 3s
      retries: 15
      start_period: 5s
  web:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.demo-web
    environment:
      - NEXT_PUBLIC_API_URL=http://sourcebridge:8080
      - SOURCEBRIDGE_WEB_DEV_PROXY=http://sourcebridge:8080
  worker:
    environment:
      - SOURCEBRIDGE_WORKER_LLM_PROVIDER=\${SOURCEBRIDGE_LLM_PROVIDER:-ollama}
      - SOURCEBRIDGE_WORKER_LLM_BASE_URL=\${SOURCEBRIDGE_LLM_BASE_URL:-http://host.docker.internal:11434/v1}
      - SOURCEBRIDGE_WORKER_LLM_MODEL=\${SOURCEBRIDGE_LLM_MODEL:-qwen3:32b}
      - SOURCEBRIDGE_WORKER_LLM_API_KEY=\${SOURCEBRIDGE_LLM_API_KEY:-not-needed}
      - SOURCEBRIDGE_WORKER_EMBEDDING_PROVIDER=\${SOURCEBRIDGE_EMBEDDING_PROVIDER:-ollama}
      - SOURCEBRIDGE_WORKER_EMBEDDING_BASE_URL=\${SOURCEBRIDGE_EMBEDDING_BASE_URL:-\${SOURCEBRIDGE_LLM_BASE_URL:-http://host.docker.internal:11434}}
  sourcebridge:
    environment:
      - SOURCEBRIDGE_LLM_PROVIDER=\${SOURCEBRIDGE_LLM_PROVIDER:-ollama}
      - SOURCEBRIDGE_LLM_BASE_URL=\${SOURCEBRIDGE_LLM_BASE_URL:-http://host.docker.internal:11434/v1}
      - SOURCEBRIDGE_LLM_SUMMARY_MODEL=\${SOURCEBRIDGE_LLM_MODEL:-qwen3:32b}
    volumes:
      - ./examples/acme-api:/demo-repos/acme-api:ro
YAML

# Build compose command with port and LLM overrides
export SOURCEBRIDGE_API_PORT="$API_PORT"
export SOURCEBRIDGE_WEB_PORT="$WEB_PORT"

if [[ "$LLM_MODE" == "cloud" ]]; then
  export SOURCEBRIDGE_LLM_PROVIDER="${SOURCEBRIDGE_LLM_PROVIDER:-anthropic}"
  export SOURCEBRIDGE_LLM_API_KEY="${SOURCEBRIDGE_LLM_API_KEY}"
  [[ -n "${SOURCEBRIDGE_LLM_MODEL:-}" ]] && export SOURCEBRIDGE_LLM_MODEL
  [[ -n "${SOURCEBRIDGE_LLM_BASE_URL:-}" ]] && export SOURCEBRIDGE_LLM_BASE_URL
fi

# Start services
cd "$SCRIPT_DIR"
if ! docker compose -f docker-compose.yml -f "$OVERRIDE_FILE" up -d --build 2>&1 | \
  while IFS= read -r line; do
    echo -e "  ${DIM}${line}${NC}"
  done; then
  # Check if services actually started despite pipe exit code
  if ! docker compose -f docker-compose.yml -f "$OVERRIDE_FILE" ps --format '{{.Name}}' 2>/dev/null | grep -q .; then
    fail "Docker Compose failed to start. Run 'docker compose -f docker-compose.yml -f docker-compose.demo.yml logs' for details."
  fi
fi

success "Docker Compose services starting"

# ── Wait for Health ───────────────────────────────────────────────────────────

header "Waiting for services to be ready..."

elapsed=0
while [[ $elapsed -lt $HEALTH_TIMEOUT ]]; do
  if curl -sf "${API_URL}/healthz" &>/dev/null; then
    break
  fi
  sleep 3
  elapsed=$((elapsed + 3))
  printf "\r  ${DIM}Waiting for API server... %ds / %ds${NC}" "$elapsed" "$HEALTH_TIMEOUT"
done
echo

if [[ $elapsed -ge $HEALTH_TIMEOUT ]]; then
  fail "API server did not become healthy within ${HEALTH_TIMEOUT}s. Check 'docker compose logs sourcebridge' for details."
fi
success "API server is healthy"

# Wait for web UI
elapsed=0
while [[ $elapsed -lt 60 ]]; do
  if curl -sf "${WEB_URL}" &>/dev/null; then
    break
  fi
  sleep 3
  elapsed=$((elapsed + 3))
done

if curl -sf "${WEB_URL}" &>/dev/null; then
  success "Web UI is ready"
else
  warn "Web UI is still starting — it may take a few more seconds"
fi

# ── Set Up Auth ───────────────────────────────────────────────────────────────

header "Configuring demo account..."

# Try setup first, fall back to login if already configured
SETUP_RESPONSE=$(curl -sf -X POST "${API_URL}/auth/setup" \
  -H "Content-Type: application/json" \
  -d "{\"password\":\"${DEMO_PASSWORD}\"}" 2>/dev/null || true)

if echo "$SETUP_RESPONSE" | grep -q '"token"'; then
  TOKEN=$(echo "$SETUP_RESPONSE" | grep -o '"token":"[^"]*"' | cut -d'"' -f4)
  success "Demo account created"
else
  # Already set up — login instead
  LOGIN_RESPONSE=$(curl -sf -X POST "${API_URL}/auth/login" \
    -H "Content-Type: application/json" \
    -d "{\"password\":\"${DEMO_PASSWORD}\"}" 2>/dev/null || true)

  if echo "$LOGIN_RESPONSE" | grep -q '"token"'; then
    TOKEN=$(echo "$LOGIN_RESPONSE" | grep -o '"token":"[^"]*"' | cut -d'"' -f4)
    success "Logged in to existing demo account"
  else
    warn "Could not authenticate — the demo will still work, but repo import will be skipped"
    TOKEN=""
  fi
fi

# ── Import Sample Repository ─────────────────────────────────────────────────

if [[ -n "$TOKEN" ]]; then
  header "Importing sample repository (${SAMPLE_REPO_NAME})..."

  IMPORT_RESPONSE=$(curl -sf -X POST "${API_URL}/api/v1/graphql" \
    -H "Authorization: Bearer ${TOKEN}" \
    -H "Content-Type: application/json" \
    -d "{
      \"query\": \"mutation AddRepo(\$i: AddRepositoryInput!) { addRepository(input: \$i) { id name status } }\",
      \"variables\": { \"i\": { \"name\": \"${SAMPLE_REPO_NAME}\", \"path\": \"${SAMPLE_REPO_PATH}\" } }
    }" 2>/dev/null || true)

  if echo "$IMPORT_RESPONSE" | grep -q '"addRepository"'; then
    REPO_STATUS=$(echo "$IMPORT_RESPONSE" | grep -o '"status":"[^"]*"' | head -1 | cut -d'"' -f4)
    success "Sample repo added (status: ${REPO_STATUS})"

    # Wait for indexing to complete
    info "Indexing sample repository..."
    index_elapsed=0
    while [[ $index_elapsed -lt 120 ]]; do
      STATUS_RESPONSE=$(curl -sf -X POST "${API_URL}/api/v1/graphql" \
        -H "Authorization: Bearer ${TOKEN}" \
        -H "Content-Type: application/json" \
        -d '{"query":"{ repositories { id name status } }"}' 2>/dev/null || true)

      if echo "$STATUS_RESPONSE" | grep -q '"status":"ready"'; then
        success "Sample repo indexed successfully"
        break
      fi
      sleep 3
      index_elapsed=$((index_elapsed + 3))
      printf "\r  ${DIM}Indexing... %ds${NC}" "$index_elapsed"
    done
    echo

    if [[ $index_elapsed -ge 120 ]]; then
      warn "Indexing is still running — it will complete in the background"
    fi
  else
    warn "Could not import sample repo — you can add it manually from the web UI"
  fi
fi

# ── Summary ───────────────────────────────────────────────────────────────────

header "SourceBridge is ready!"

echo -e "  ${BOLD}Open in your browser:${NC}  ${GREEN}${WEB_URL}${NC}"
echo ""

if [[ -n "$TOKEN" ]]; then
  echo -e "  ${BOLD}Password:${NC}  ${DEMO_PASSWORD}"
  echo ""
fi

echo -e "  ${BOLD}What to explore:${NC}"
echo -e "    1. Click on ${CYAN}acme-api${NC} in the repository list"
echo -e "    2. Browse the ${CYAN}file tree${NC} and ${CYAN}symbol index${NC}"

case "$LLM_MODE" in
  cloud|ollama)
    echo -e "    3. Open ${CYAN}Cliff Notes${NC} to see the AI-generated field guide"
    echo -e "    4. Explore the ${CYAN}Code Tour${NC} for a guided walkthrough"
    echo -e "    5. Check the ${CYAN}Learning Path${NC} for onboarding steps"
    echo ""
    info "AI artifacts are generating in the background — they may take a few minutes to appear."
    ;;
  none)
    echo ""
    echo -e "  ${BOLD}Want AI-generated insights?${NC}"
    echo -e "    Install Ollama (${CYAN}https://ollama.com${NC}), pull a model, and re-run:"
    echo -e "    ${DIM}ollama pull qwen3:32b${NC}"
    echo -e "    ${DIM}./demo.sh${NC}"
    echo ""
    echo -e "    Or provide a cloud API key:"
    echo -e "    ${DIM}SOURCEBRIDGE_LLM_API_KEY=sk-ant-... ./demo.sh${NC}"
    ;;
esac

echo ""
echo -e "  ${BOLD}Next steps:${NC}"
echo -e "    • Try adding your own repo from the web UI"
echo -e "    • Read ${CYAN}docs/start-here.md${NC} for a walkthrough"
echo ""
echo -e "  ${BOLD}Did it work?${NC} Let us know!"
echo -e "    ${CYAN}https://github.com/sourcebridge-ai/sourcebridge/discussions${NC}"
echo -e "    Or star the repo if you found it useful."
echo ""

# ── Cleanup Note ──────────────────────────────────────────────────────────────

echo -e "  ${DIM}To stop:  docker compose -f docker-compose.yml -f docker-compose.demo.yml down${NC}"
echo -e "  ${DIM}To reset: docker compose -f docker-compose.yml -f docker-compose.demo.yml down -v${NC}"
echo ""
