// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 SourceBridge Contributors

package graphql

import (
	"testing"
)

// TestLanguageGroovyCanary asserts that the GROOVY enum value was correctly
// generated by gqlgen into models_gen.go. Protects against accidental
// regeneration that drops the value or misnames it.
func TestLanguageGroovyCanary(t *testing.T) {
	if !LanguageGroovy.IsValid() {
		t.Fatalf("LanguageGroovy.IsValid() = false; expected true")
	}
	if string(LanguageGroovy) != "GROOVY" {
		t.Fatalf("LanguageGroovy string = %q; want %q", string(LanguageGroovy), "GROOVY")
	}
	found := false
	for _, l := range AllLanguage {
		if l == LanguageGroovy {
			found = true
			break
		}
	}
	if !found {
		t.Fatalf("LanguageGroovy not present in AllLanguage slice")
	}
}
