// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 SourceBridge Contributors
//
// Helpers for the living-wiki global-settings resolvers.
// The actual resolver methods (LivingWikiSettings query,
// UpdateLivingWikiSettings and TestLivingWikiConnection mutations) are
// generated by gqlgen and live in schema.resolvers.go. This file holds
// only mapping helpers, provider connectivity tests, and micro-utilities
// so they stay out of the ~3000-line schema.resolvers.go file.

package graphql

import (
	"context"
	"fmt"
	"net/http"

	"github.com/sourcebridge/sourcebridge/internal/settings/livingwiki"
)

// ─────────────────────────────────────────────────────────────────────────────
// Mapping helper
// ─────────────────────────────────────────────────────────────────────────────

func mapLivingWikiSettings(s livingwiki.Settings) *LivingWikiSettings {
	out := &LivingWikiSettings{
		Enabled:   s.Enabled,
		UpdatedBy: strPtrIfNonEmpty(s.UpdatedBy),
	}
	if s.WorkerCount > 0 {
		v := s.WorkerCount
		out.WorkerCount = &v
	}
	if s.EventTimeout != "" {
		out.EventTimeout = &s.EventTimeout
	}
	if s.GitHubToken != "" {
		out.GithubToken = &s.GitHubToken
	}
	if s.GitLabToken != "" {
		out.GitlabToken = &s.GitLabToken
	}
	if s.ConfluenceEmail != "" {
		out.ConfluenceEmail = &s.ConfluenceEmail
	}
	if s.ConfluenceToken != "" {
		out.ConfluenceToken = &s.ConfluenceToken
	}
	if s.NotionToken != "" {
		out.NotionToken = &s.NotionToken
	}
	if s.ConfluenceWebhookSecret != "" {
		out.ConfluenceWebhookSecret = &s.ConfluenceWebhookSecret
	}
	if s.NotionWebhookSecret != "" {
		out.NotionWebhookSecret = &s.NotionWebhookSecret
	}
	if !s.UpdatedAt.IsZero() {
		out.UpdatedAt = &s.UpdatedAt
	}
	return out
}

// ─────────────────────────────────────────────────────────────────────────────
// Provider connectivity tests
// ─────────────────────────────────────────────────────────────────────────────

func testGitHubConnection(ctx context.Context, token string) (*LivingWikiConnectionTestResult, error) {
	if token == "" {
		return &LivingWikiConnectionTestResult{
			Provider: "github",
			Ok:       false,
			Message:  strPtr("no GitHub token configured"),
		}, nil
	}
	req, _ := http.NewRequestWithContext(ctx, http.MethodGet, "https://api.github.com/user", nil)
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("X-GitHub-Api-Version", "2022-11-28")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return &LivingWikiConnectionTestResult{
			Provider: "github",
			Ok:       false,
			Message:  strPtr(err.Error()),
		}, nil
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusOK {
		return &LivingWikiConnectionTestResult{Provider: "github", Ok: true}, nil
	}
	return &LivingWikiConnectionTestResult{
		Provider: "github",
		Ok:       false,
		Message:  strPtr(fmt.Sprintf("GitHub API returned %d", resp.StatusCode)),
	}, nil
}

func testGitLabConnection(ctx context.Context, token string) (*LivingWikiConnectionTestResult, error) {
	if token == "" {
		return &LivingWikiConnectionTestResult{
			Provider: "gitlab",
			Ok:       false,
			Message:  strPtr("no GitLab token configured"),
		}, nil
	}
	req, _ := http.NewRequestWithContext(ctx, http.MethodGet, "https://gitlab.com/api/v4/user", nil)
	req.Header.Set("PRIVATE-TOKEN", token)

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return &LivingWikiConnectionTestResult{
			Provider: "gitlab",
			Ok:       false,
			Message:  strPtr(err.Error()),
		}, nil
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusOK {
		return &LivingWikiConnectionTestResult{Provider: "gitlab", Ok: true}, nil
	}
	return &LivingWikiConnectionTestResult{
		Provider: "gitlab",
		Ok:       false,
		Message:  strPtr(fmt.Sprintf("GitLab API returned %d", resp.StatusCode)),
	}, nil
}

func testConfluenceConnection(ctx context.Context, email, token string) (*LivingWikiConnectionTestResult, error) {
	if email == "" || token == "" {
		return &LivingWikiConnectionTestResult{
			Provider: "confluence",
			Ok:       false,
			Message:  strPtr("Confluence email and token are both required"),
		}, nil
	}
	req, _ := http.NewRequestWithContext(ctx, http.MethodGet, "https://api.atlassian.com/me", nil)
	req.SetBasicAuth(email, token)
	req.Header.Set("Accept", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return &LivingWikiConnectionTestResult{
			Provider: "confluence",
			Ok:       false,
			Message:  strPtr(err.Error()),
		}, nil
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusOK {
		return &LivingWikiConnectionTestResult{Provider: "confluence", Ok: true}, nil
	}
	return &LivingWikiConnectionTestResult{
		Provider: "confluence",
		Ok:       false,
		Message:  strPtr(fmt.Sprintf("Atlassian API returned %d", resp.StatusCode)),
	}, nil
}

func testNotionConnection(ctx context.Context, token string) (*LivingWikiConnectionTestResult, error) {
	if token == "" {
		return &LivingWikiConnectionTestResult{
			Provider: "notion",
			Ok:       false,
			Message:  strPtr("no Notion token configured"),
		}, nil
	}
	req, _ := http.NewRequestWithContext(ctx, http.MethodGet, "https://api.notion.com/v1/users/me", nil)
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Notion-Version", "2022-06-28")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return &LivingWikiConnectionTestResult{
			Provider: "notion",
			Ok:       false,
			Message:  strPtr(err.Error()),
		}, nil
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusOK {
		return &LivingWikiConnectionTestResult{Provider: "notion", Ok: true}, nil
	}
	return &LivingWikiConnectionTestResult{
		Provider: "notion",
		Ok:       false,
		Message:  strPtr(fmt.Sprintf("Notion API returned %d", resp.StatusCode)),
	}, nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Micro-helpers
// ─────────────────────────────────────────────────────────────────────────────

func strPtrIfNonEmpty(s string) *string {
	if s == "" {
		return nil
	}
	return &s
}

// userIDFromContext extracts the caller's user ID for audit logging.
// Returns "" when no user is in context (e.g. anonymous or API token callers).
func userIDFromContext(ctx context.Context) string {
	// Extended by the enterprise layer; acceptable stub for now.
	_ = ctx
	return ""
}

// remoteAddrContextKey is the context key used to carry the HTTP remote address
// for audit logging. Middleware that wants to propagate the caller's IP should
// store it under this key via context.WithValue.
type remoteAddrContextKey struct{}

// remoteAddrFromContext extracts the remote IP address from the request context
// for audit logging. Returns "" when no address is available.
func remoteAddrFromContext(ctx context.Context) string {
	if ctx == nil {
		return ""
	}
	if addr, ok := ctx.Value(remoteAddrContextKey{}).(string); ok {
		return addr
	}
	return ""
}

// WithRemoteAddr returns a context carrying the caller's remote address for
// audit-log extraction by [remoteAddrFromContext].
func WithRemoteAddr(ctx context.Context, addr string) context.Context {
	return context.WithValue(ctx, remoteAddrContextKey{}, addr)
}

