// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type APIContract struct {
	ID            string    `json:"id"`
	RepoID        string    `json:"repoId"`
	FilePath      string    `json:"filePath"`
	ContractType  string    `json:"contractType"`
	EndpointCount int       `json:"endpointCount"`
	Version       *string   `json:"version,omitempty"`
	DetectedAt    time.Time `json:"detectedAt"`
}

type AddRepositoryInput struct {
	Name  string  `json:"name"`
	Path  string  `json:"path"`
	Token *string `json:"token,omitempty"`
}

type AnalysisResult struct {
	Summary      string   `json:"summary"`
	Purpose      string   `json:"purpose"`
	Concerns     []string `json:"concerns"`
	Suggestions  []string `json:"suggestions"`
	Model        *string  `json:"model,omitempty"`
	InputTokens  *int     `json:"inputTokens,omitempty"`
	OutputTokens *int     `json:"outputTokens,omitempty"`
}

type ArtifactDependency struct {
	ID               string    `json:"id"`
	DependencyType   string    `json:"dependencyType"`
	TargetID         string    `json:"targetId"`
	TargetRevisionFp *string   `json:"targetRevisionFp,omitempty"`
	Metadata         *string   `json:"metadata,omitempty"`
	CreatedAt        time.Time `json:"createdAt"`
}

type AskCrossRepoRef struct {
	RepositoryID string  `json:"repositoryId"`
	FilePath     *string `json:"filePath,omitempty"`
	Note         *string `json:"note,omitempty"`
}

type AskDebug struct {
	Prompt          *string              `json:"prompt,omitempty"`
	ContextMarkdown *string              `json:"contextMarkdown,omitempty"`
	Candidates      []*AskDebugCandidate `json:"candidates,omitempty"`
}

type AskDebugCandidate struct {
	Source string   `json:"source"`
	ID     *string  `json:"id,omitempty"`
	Score  *float64 `json:"score,omitempty"`
	Reason *string  `json:"reason,omitempty"`
}

type AskDiagnostics struct {
	QuestionType          *string           `json:"questionType,omitempty"`
	UnderstandingStage    *string           `json:"understandingStage,omitempty"`
	TreeStatus            *string           `json:"treeStatus,omitempty"`
	UnderstandingRevision *string           `json:"understandingRevision,omitempty"`
	UnderstandingUsed     *bool             `json:"understandingUsed,omitempty"`
	GraphExpansionUsed    *bool             `json:"graphExpansionUsed,omitempty"`
	FilesConsidered       []string          `json:"filesConsidered,omitempty"`
	FilesUsed             []string          `json:"filesUsed,omitempty"`
	FallbackUsed          *string           `json:"fallbackUsed,omitempty"`
	ModelUsed             *string           `json:"modelUsed,omitempty"`
	StageTimingsMs        []*AskStageTiming `json:"stageTimingsMs,omitempty"`
	Mode                  *string           `json:"mode,omitempty"`
}

type AskFileRangeRef struct {
	FilePath  string  `json:"filePath"`
	StartLine *int    `json:"startLine,omitempty"`
	EndLine   *int    `json:"endLine,omitempty"`
	Snippet   *string `json:"snippet,omitempty"`
}

type AskInput struct {
	RepositoryID   string    `json:"repositoryId"`
	Question       string    `json:"question"`
	Mode           *string   `json:"mode,omitempty"`
	ConversationID *string   `json:"conversationId,omitempty"`
	PriorMessages  []string  `json:"priorMessages,omitempty"`
	FilePath       *string   `json:"filePath,omitempty"`
	Code           *string   `json:"code,omitempty"`
	Language       *Language `json:"language,omitempty"`
	ArtifactID     *string   `json:"artifactId,omitempty"`
	SymbolID       *string   `json:"symbolId,omitempty"`
	RequirementID  *string   `json:"requirementId,omitempty"`
	IncludeDebug   *bool     `json:"includeDebug,omitempty"`
}

type AskReference struct {
	Kind                 string                      `json:"kind"`
	Title                *string                     `json:"title,omitempty"`
	Symbol               *AskSymbolRef               `json:"symbol,omitempty"`
	FileRange            *AskFileRangeRef            `json:"fileRange,omitempty"`
	Requirement          *AskRequirementRef          `json:"requirement,omitempty"`
	UnderstandingSection *AskUnderstandingSectionRef `json:"understandingSection,omitempty"`
	CrossRepo            *AskCrossRepoRef            `json:"crossRepo,omitempty"`
}

type AskRequirementRef struct {
	ExternalID string  `json:"externalId"`
	Title      *string `json:"title,omitempty"`
	FilePath   *string `json:"filePath,omitempty"`
}

type AskResult struct {
	Answer              string          `json:"answer"`
	References          []*AskReference `json:"references"`
	RelatedRequirements []string        `json:"relatedRequirements"`
	Diagnostics         *AskDiagnostics `json:"diagnostics"`
	Usage               *AskUsage       `json:"usage"`
	Debug               *AskDebug       `json:"debug,omitempty"`
}

type AskStageTiming struct {
	Stage      string `json:"stage"`
	DurationMs int    `json:"durationMs"`
}

type AskSymbolRef struct {
	SymbolID      string  `json:"symbolId"`
	QualifiedName string  `json:"qualifiedName"`
	FilePath      *string `json:"filePath,omitempty"`
	StartLine     *int    `json:"startLine,omitempty"`
	EndLine       *int    `json:"endLine,omitempty"`
	Language      *string `json:"language,omitempty"`
}

type AskUnderstandingSectionRef struct {
	ArtifactID *string `json:"artifactId,omitempty"`
	SectionID  *string `json:"sectionId,omitempty"`
	Headline   *string `json:"headline,omitempty"`
	Kind       *string `json:"kind,omitempty"`
	ActionURL  *string `json:"actionUrl,omitempty"`
}

type AskUsage struct {
	Model        *string `json:"model,omitempty"`
	InputTokens  *int    `json:"inputTokens,omitempty"`
	OutputTokens *int    `json:"outputTokens,omitempty"`
}

type AutoLinkResult struct {
	LinksCreated          int                `json:"linksCreated"`
	RequirementsProcessed int                `json:"requirementsProcessed"`
	Links                 []*RequirementLink `json:"links"`
}

type BuildRepositoryUnderstandingInput struct {
	RepositoryID string              `json:"repositoryId"`
	ScopeType    *KnowledgeScopeType `json:"scopeType,omitempty"`
	ScopePath    *string             `json:"scopePath,omitempty"`
}

type CodeSymbol struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	QualifiedName string             `json:"qualifiedName"`
	Kind          SymbolKind         `json:"kind"`
	Language      Language           `json:"language"`
	FilePath      string             `json:"filePath"`
	StartLine     int                `json:"startLine"`
	EndLine       int                `json:"endLine"`
	Signature     *string            `json:"signature,omitempty"`
	DocComment    *string            `json:"docComment,omitempty"`
	Callers       []*CodeSymbol      `json:"callers"`
	Callees       []*CodeSymbol      `json:"callees"`
	Requirements  []*RequirementLink `json:"requirements"`
}

type CodeTourStop struct {
	Title       string               `json:"title"`
	Description string               `json:"description"`
	FilePath    string               `json:"filePath"`
	LineStart   int                  `json:"lineStart"`
	LineEnd     int                  `json:"lineEnd"`
	OrderIndex  int                  `json:"orderIndex"`
	Evidence    []*KnowledgeEvidence `json:"evidence"`
}

type ComprehensionSettings struct {
	ID                             *string                  `json:"id,omitempty"`
	ScopeType                      string                   `json:"scopeType"`
	ScopeKey                       string                   `json:"scopeKey"`
	StrategyPreferenceChain        []string                 `json:"strategyPreferenceChain,omitempty"`
	KnowledgeGenerationModeDefault *KnowledgeGenerationMode `json:"knowledgeGenerationModeDefault,omitempty"`
	ModelID                        *string                  `json:"modelId,omitempty"`
	MaxConcurrency                 *int                     `json:"maxConcurrency,omitempty"`
	MaxPromptTokens                *int                     `json:"maxPromptTokens,omitempty"`
	LeafBudgetTokens               *int                     `json:"leafBudgetTokens,omitempty"`
	RefinePassEnabled              *bool                    `json:"refinePassEnabled,omitempty"`
	LongContextMaxTokens           *int                     `json:"longContextMaxTokens,omitempty"`
	GraphragEntityTypes            []string                 `json:"graphragEntityTypes,omitempty"`
	CacheEnabled                   *bool                    `json:"cacheEnabled,omitempty"`
	AllowUnsafeCombinations        *bool                    `json:"allowUnsafeCombinations,omitempty"`
	UpdatedAt                      *time.Time               `json:"updatedAt,omitempty"`
	UpdatedBy                      *string                  `json:"updatedBy,omitempty"`
}

type CreateManualLinkInput struct {
	RepositoryID  string  `json:"repositoryId"`
	RequirementID string  `json:"requirementId"`
	SymbolID      string  `json:"symbolId"`
	Rationale     *string `json:"rationale,omitempty"`
}

// Create a single requirement. `externalId` auto-generates when blank.
// Server validates uniqueness of (repositoryId, externalId) among
// non-trashed rows.
type CreateRequirementInput struct {
	RepositoryID string   `json:"repositoryId"`
	ExternalID   *string  `json:"externalId,omitempty"`
	Title        string   `json:"title"`
	Description  *string  `json:"description,omitempty"`
	Priority     *string  `json:"priority,omitempty"`
	Source       *string  `json:"source,omitempty"`
	Tags         []string `json:"tags,omitempty"`
}

type CrossRepoRef struct {
	ID             string           `json:"id"`
	SourceSymbolID string           `json:"sourceSymbolId"`
	TargetSymbolID string           `json:"targetSymbolId"`
	SourceRepoID   string           `json:"sourceRepoId"`
	TargetRepoID   string           `json:"targetRepoId"`
	RefType        CrossRepoRefType `json:"refType"`
	Confidence     float64          `json:"confidence"`
	ContractFile   *string          `json:"contractFile,omitempty"`
	ConsumerFile   *string          `json:"consumerFile,omitempty"`
	Evidence       *string          `json:"evidence,omitempty"`
	CreatedAt      time.Time        `json:"createdAt"`
}

type CrossRepoRefConnection struct {
	Nodes      []*CrossRepoRef `json:"nodes"`
	TotalCount int             `json:"totalCount"`
}

type DiagramEdge struct {
	TargetPath string `json:"targetPath"`
	CallCount  int    `json:"callCount"`
}

type DiagramModule struct {
	Path                 string         `json:"path"`
	SymbolCount          int            `json:"symbolCount"`
	FileCount            int            `json:"fileCount"`
	RequirementLinkCount int            `json:"requirementLinkCount"`
	InboundEdgeCount     int            `json:"inboundEdgeCount"`
	OutboundEdges        []*DiagramEdge `json:"outboundEdges"`
}

type DiagramOutput struct {
	MermaidSource string           `json:"mermaidSource"`
	Modules       []*DiagramModule `json:"modules"`
	Level         DiagramLevel     `json:"level"`
	TotalModules  int              `json:"totalModules"`
	ShownModules  int              `json:"shownModules"`
	Truncated     bool             `json:"truncated"`
}

type DiscoveredRequirement struct {
	ID              string    `json:"id"`
	RepoID          string    `json:"repoId"`
	Source          string    `json:"source"`
	SourceFile      string    `json:"sourceFile"`
	SourceLine      int       `json:"sourceLine"`
	SourceFiles     []string  `json:"sourceFiles"`
	Text            string    `json:"text"`
	RawText         string    `json:"rawText"`
	GroupKey        string    `json:"groupKey"`
	Language        string    `json:"language"`
	Keywords        []string  `json:"keywords"`
	Confidence      string    `json:"confidence"`
	Status          string    `json:"status"`
	LlmRefined      bool      `json:"llmRefined"`
	PromotedTo      *string   `json:"promotedTo,omitempty"`
	DismissedBy     *string   `json:"dismissedBy,omitempty"`
	DismissedReason *string   `json:"dismissedReason,omitempty"`
	CreatedAt       time.Time `json:"createdAt"`
}

type DiscoveredRequirementConnection struct {
	Nodes      []*DiscoveredRequirement `json:"nodes"`
	TotalCount int                      `json:"totalCount"`
}

type DiscussCodeInput struct {
	RepositoryID        string    `json:"repositoryId"`
	Question            string    `json:"question"`
	FilePath            *string   `json:"filePath,omitempty"`
	Code                *string   `json:"code,omitempty"`
	Language            *Language `json:"language,omitempty"`
	ArtifactID          *string   `json:"artifactId,omitempty"`
	SymbolID            *string   `json:"symbolId,omitempty"`
	RequirementID       *string   `json:"requirementId,omitempty"`
	ConversationHistory []string  `json:"conversationHistory,omitempty"`
}

type DiscussionResult struct {
	Answer              string   `json:"answer"`
	References          []string `json:"references"`
	RelatedRequirements []string `json:"relatedRequirements"`
	Model               *string  `json:"model,omitempty"`
	InputTokens         *int     `json:"inputTokens,omitempty"`
	OutputTokens        *int     `json:"outputTokens,omitempty"`
}

type EffectiveComprehensionSettings struct {
	ScopeType                      string                  `json:"scopeType"`
	ScopeKey                       string                  `json:"scopeKey"`
	StrategyPreferenceChain        []string                `json:"strategyPreferenceChain"`
	KnowledgeGenerationModeDefault KnowledgeGenerationMode `json:"knowledgeGenerationModeDefault"`
	ModelID                        string                  `json:"modelId"`
	MaxConcurrency                 int                     `json:"maxConcurrency"`
	MaxPromptTokens                int                     `json:"maxPromptTokens"`
	LeafBudgetTokens               int                     `json:"leafBudgetTokens"`
	RefinePassEnabled              bool                    `json:"refinePassEnabled"`
	LongContextMaxTokens           int                     `json:"longContextMaxTokens"`
	GraphragEntityTypes            []string                `json:"graphragEntityTypes"`
	CacheEnabled                   bool                    `json:"cacheEnabled"`
	AllowUnsafeCombinations        bool                    `json:"allowUnsafeCombinations"`
	InheritedFrom                  []*FieldOrigin          `json:"inheritedFrom,omitempty"`
}

// enableLivingWikiForRepo saves the repo settings and enqueues the cold-start
// job. Returns jobId so the UI can track progress via the activity feed.
//
// Kill-switch behavior: if SOURCEBRIDGE_LIVING_WIKI_KILL_SWITCH=true is set,
// the mutation persists settings but returns jobId: null and a non-null notice.
// Globally-disabled behavior: if the global LivingWikiSettings.enabled is false,
// the same notice+null pattern applies.
type EnableLivingWikiForRepoInput struct {
	RepositoryID string               `json:"repositoryId"`
	Mode         RepoWikiMode         `json:"mode"`
	Sinks        []*RepoWikiSinkInput `json:"sinks"`
	// When true, restrict the cold-start job to re-attempting only the pages that
	// were excluded in the most recent job (from lw_job_results.excluded_page_ids).
	// Used by the "Retry excluded pages" CTA. Defaults to false (full run).
	RetryExcludedOnly *bool `json:"retryExcludedOnly,omitempty"`
}

type EnableLivingWikiResult struct {
	Settings *RepositoryLivingWikiSettings `json:"settings"`
	// jobId is visible in the LLM activity feed. Null in two cases:
	// 1. Living-wiki is globally disabled.
	// 2. SOURCEBRIDGE_LIVING_WIKI_KILL_SWITCH=true is set.
	// In both cases notice is non-null.
	JobID *string `json:"jobId,omitempty"`
	// notice is non-null when settings were saved but no job was enqueued.
	// The UI renders this as an informational banner (not a toast).
	Notice *string `json:"notice,omitempty"`
}

type ExecutionEntryPoint struct {
	Kind      ExecutionEntryKind `json:"kind"`
	Label     string             `json:"label"`
	Value     string             `json:"value"`
	FilePath  *string            `json:"filePath,omitempty"`
	LineStart *int               `json:"lineStart,omitempty"`
	LineEnd   *int               `json:"lineEnd,omitempty"`
	SymbolID  *string            `json:"symbolId,omitempty"`
	Summary   *string            `json:"summary,omitempty"`
}

type ExecutionPathInput struct {
	RepositoryID string             `json:"repositoryId"`
	EntryKind    ExecutionEntryKind `json:"entryKind"`
	EntryValue   string             `json:"entryValue"`
	MaxDepth     *int               `json:"maxDepth,omitempty"`
}

type ExecutionPathResult struct {
	EntryKind         ExecutionEntryKind   `json:"entryKind"`
	EntryLabel        string               `json:"entryLabel"`
	Message           *string              `json:"message,omitempty"`
	TrustQualified    bool                 `json:"trustQualified"`
	ObservedStepCount int                  `json:"observedStepCount"`
	InferredStepCount int                  `json:"inferredStepCount"`
	Steps             []*ExecutionPathStep `json:"steps"`
}

type ExecutionPathStep struct {
	OrderIndex  int     `json:"orderIndex"`
	Kind        string  `json:"kind"`
	Label       string  `json:"label"`
	Explanation string  `json:"explanation"`
	Confidence  string  `json:"confidence"`
	Observed    bool    `json:"observed"`
	Reason      *string `json:"reason,omitempty"`
	FilePath    *string `json:"filePath,omitempty"`
	LineStart   *int    `json:"lineStart,omitempty"`
	LineEnd     *int    `json:"lineEnd,omitempty"`
	SymbolID    *string `json:"symbolId,omitempty"`
	SymbolName  *string `json:"symbolName,omitempty"`
}

type ExplainSystemInput struct {
	RepositoryID   string                   `json:"repositoryId"`
	Audience       *KnowledgeAudience       `json:"audience,omitempty"`
	Depth          *KnowledgeDepth          `json:"depth,omitempty"`
	GenerationMode *KnowledgeGenerationMode `json:"generationMode,omitempty"`
	Question       *string                  `json:"question,omitempty"`
	ScopeType      *KnowledgeScopeType      `json:"scopeType,omitempty"`
	ScopePath      *string                  `json:"scopePath,omitempty"`
}

type ExplainSystemResult struct {
	Explanation  string  `json:"explanation"`
	Model        *string `json:"model,omitempty"`
	InputTokens  *int    `json:"inputTokens,omitempty"`
	OutputTokens *int    `json:"outputTokens,omitempty"`
}

type Features struct {
	MultiTenant              bool `json:"multiTenant"`
	Sso                      bool `json:"sso"`
	LinearConnector          bool `json:"linearConnector"`
	JiraConnector            bool `json:"jiraConnector"`
	GithubApp                bool `json:"githubApp"`
	GitlabApp                bool `json:"gitlabApp"`
	AuditLog                 bool `json:"auditLog"`
	Webhooks                 bool `json:"webhooks"`
	CustomTemplates          bool `json:"customTemplates"`
	Billing                  bool `json:"billing"`
	CliffNotes               bool `json:"cliffNotes"`
	LearningPaths            bool `json:"learningPaths"`
	CodeTours                bool `json:"codeTours"`
	SystemExplain            bool `json:"systemExplain"`
	SymbolScopedAnalysis     bool `json:"symbolScopedAnalysis"`
	MultiAudienceKnowledge   bool `json:"multiAudienceKnowledge"`
	CustomKnowledgeTemplates bool `json:"customKnowledgeTemplates"`
	AdvancedLearningPaths    bool `json:"advancedLearningPaths"`
	SlideGeneration          bool `json:"slideGeneration"`
	PodcastGeneration        bool `json:"podcastGeneration"`
	KnowledgeScheduling      bool `json:"knowledgeScheduling"`
	KnowledgeExport          bool `json:"knowledgeExport"`
}

type FieldOrigin struct {
	Field     string `json:"field"`
	ScopeType string `json:"scopeType"`
	ScopeKey  string `json:"scopeKey"`
}

type File struct {
	ID        string        `json:"id"`
	Path      string        `json:"path"`
	Language  Language      `json:"language"`
	LineCount int           `json:"lineCount"`
	AiScore   float64       `json:"aiScore"`
	AiSignals []string      `json:"aiSignals"`
	Symbols   []*CodeSymbol `json:"symbols"`
}

type FileConnection struct {
	Nodes      []*File `json:"nodes"`
	TotalCount int     `json:"totalCount"`
}

type FileDiff struct {
	Path      string     `json:"path"`
	OldPath   *string    `json:"oldPath,omitempty"`
	Status    DiffStatus `json:"status"`
	Additions int        `json:"additions"`
	Deletions int        `json:"deletions"`
}

type GenerateArchitectureDiagramInput struct {
	RepositoryID string             `json:"repositoryId"`
	Audience     *KnowledgeAudience `json:"audience,omitempty"`
	Depth        *KnowledgeDepth    `json:"depth,omitempty"`
}

type GenerateCliffNotesInput struct {
	RepositoryID   string                   `json:"repositoryId"`
	Audience       *KnowledgeAudience       `json:"audience,omitempty"`
	Depth          *KnowledgeDepth          `json:"depth,omitempty"`
	GenerationMode *KnowledgeGenerationMode `json:"generationMode,omitempty"`
	ScopeType      *KnowledgeScopeType      `json:"scopeType,omitempty"`
	ScopePath      *string                  `json:"scopePath,omitempty"`
}

type GenerateCodeTourInput struct {
	RepositoryID   string                   `json:"repositoryId"`
	Audience       *KnowledgeAudience       `json:"audience,omitempty"`
	Depth          *KnowledgeDepth          `json:"depth,omitempty"`
	GenerationMode *KnowledgeGenerationMode `json:"generationMode,omitempty"`
	Theme          *string                  `json:"theme,omitempty"`
}

type GenerateLearningPathInput struct {
	RepositoryID   string                   `json:"repositoryId"`
	Audience       *KnowledgeAudience       `json:"audience,omitempty"`
	Depth          *KnowledgeDepth          `json:"depth,omitempty"`
	GenerationMode *KnowledgeGenerationMode `json:"generationMode,omitempty"`
	FocusArea      *string                  `json:"focusArea,omitempty"`
}

type GenerateWorkflowStoryInput struct {
	RepositoryID      string                   `json:"repositoryId"`
	Audience          *KnowledgeAudience       `json:"audience,omitempty"`
	Depth             *KnowledgeDepth          `json:"depth,omitempty"`
	GenerationMode    *KnowledgeGenerationMode `json:"generationMode,omitempty"`
	ScopeType         *KnowledgeScopeType      `json:"scopeType,omitempty"`
	ScopePath         *string                  `json:"scopePath,omitempty"`
	AnchorLabel       *string                  `json:"anchorLabel,omitempty"`
	ExecutionPathJSON *string                  `json:"executionPathJson,omitempty"`
}

type HealthStatus struct {
	Status   string           `json:"status"`
	Services []*ServiceHealth `json:"services"`
}

type IDECapabilities struct {
	RepoKnowledge   bool `json:"repoKnowledge"`
	ScopedKnowledge bool `json:"scopedKnowledge"`
	ScopedExplain   bool `json:"scopedExplain"`
	ImpactReports   bool `json:"impactReports"`
	DiscussCode     bool `json:"discussCode"`
	ReviewCode      bool `json:"reviewCode"`
	Vscode          bool `json:"vscode"`
	Jetbrains       bool `json:"jetbrains"`
}

type ImpactAffectedLink struct {
	LinkID        string  `json:"linkId"`
	RequirementID string  `json:"requirementId"`
	SymbolID      string  `json:"symbolId"`
	Impact        string  `json:"impact"`
	Confidence    float64 `json:"confidence"`
}

type ImpactAffectedRequirement struct {
	RequirementID string `json:"requirementId"`
	ExternalID    string `json:"externalId"`
	Title         string `json:"title"`
	AffectedLinks int    `json:"affectedLinks"`
	TotalLinks    int    `json:"totalLinks"`
}

type ImpactReport struct {
	ID                   string                       `json:"id"`
	RepositoryID         string                       `json:"repositoryId"`
	OldCommitSha         *string                      `json:"oldCommitSha,omitempty"`
	NewCommitSha         *string                      `json:"newCommitSha,omitempty"`
	FilesChanged         []*FileDiff                  `json:"filesChanged"`
	SymbolsAdded         []*SymbolChange              `json:"symbolsAdded"`
	SymbolsModified      []*SymbolChange              `json:"symbolsModified"`
	SymbolsRemoved       []*SymbolChange              `json:"symbolsRemoved"`
	AffectedLinks        []*ImpactAffectedLink        `json:"affectedLinks"`
	AffectedRequirements []*ImpactAffectedRequirement `json:"affectedRequirements"`
	StaleArtifacts       []string                     `json:"staleArtifacts"`
	ComputedAt           time.Time                    `json:"computedAt"`
}

type ImportRequirementsInput struct {
	RepositoryID string            `json:"repositoryId"`
	Content      string            `json:"content"`
	Format       RequirementFormat `json:"format"`
	SourcePath   *string           `json:"sourcePath,omitempty"`
}

type ImportResult struct {
	Imported int      `json:"imported"`
	Skipped  int      `json:"skipped"`
	Warnings []string `json:"warnings"`
}

type KnowledgeArtifact struct {
	ID              string                  `json:"id"`
	RepositoryID    string                  `json:"repositoryId"`
	Type            KnowledgeArtifactType   `json:"type"`
	Audience        KnowledgeAudience       `json:"audience"`
	Depth           KnowledgeDepth          `json:"depth"`
	Scope           *KnowledgeScope         `json:"scope"`
	Status          KnowledgeArtifactStatus `json:"status"`
	Progress        float64                 `json:"progress"`
	ProgressPhase   *string                 `json:"progressPhase,omitempty"`
	ProgressMessage *string                 `json:"progressMessage,omitempty"`
	SourceRevision  *SourceRevision         `json:"sourceRevision"`
	Stale           bool                    `json:"stale"`
	// Explanation for why this artifact is stale. Present when selective
	// invalidation on reindex flagged the artifact; null for fresh artifacts and
	// for artifacts that were staled by legacy blanket invalidation on installs
	// prior to the Phase 1 rollout.
	StaleReason             *StaleReason               `json:"staleReason,omitempty"`
	GeneratedAt             *time.Time                 `json:"generatedAt,omitempty"`
	CreatedAt               time.Time                  `json:"createdAt"`
	UpdatedAt               time.Time                  `json:"updatedAt"`
	ErrorCode               *string                    `json:"errorCode,omitempty"`
	ErrorMessage            *string                    `json:"errorMessage,omitempty"`
	GenerationMode          KnowledgeGenerationMode    `json:"generationMode"`
	RendererVersion         *string                    `json:"rendererVersion,omitempty"`
	UnderstandingID         *string                    `json:"understandingId,omitempty"`
	UnderstandingRevisionFp *string                    `json:"understandingRevisionFp,omitempty"`
	RefreshAvailable        bool                       `json:"refreshAvailable"`
	Dependencies            []*ArtifactDependency      `json:"dependencies"`
	RefinementUnits         []*KnowledgeRefinementUnit `json:"refinementUnits"`
	Sections                []*KnowledgeSection        `json:"sections"`
}

type KnowledgeEvidence struct {
	ID         string             `json:"id"`
	SectionID  string             `json:"sectionId"`
	SourceType EvidenceSourceType `json:"sourceType"`
	SourceID   string             `json:"sourceId"`
	FilePath   *string            `json:"filePath,omitempty"`
	LineStart  *int               `json:"lineStart,omitempty"`
	LineEnd    *int               `json:"lineEnd,omitempty"`
	Rationale  *string            `json:"rationale,omitempty"`
	Metadata   *string            `json:"metadata,omitempty"`
}

type KnowledgeRefinementUnit struct {
	ID                 string    `json:"id"`
	ArtifactID         string    `json:"artifactId"`
	SectionKey         string    `json:"sectionKey"`
	SectionTitle       string    `json:"sectionTitle"`
	RefinementType     string    `json:"refinementType"`
	Status             string    `json:"status"`
	AttemptCount       int       `json:"attemptCount"`
	UnderstandingID    *string   `json:"understandingId,omitempty"`
	EvidenceRevisionFp *string   `json:"evidenceRevisionFp,omitempty"`
	RendererVersion    *string   `json:"rendererVersion,omitempty"`
	LastError          *string   `json:"lastError,omitempty"`
	Metadata           *string   `json:"metadata,omitempty"`
	CreatedAt          time.Time `json:"createdAt"`
	UpdatedAt          time.Time `json:"updatedAt"`
}

type KnowledgeScope struct {
	ScopeType  KnowledgeScopeType `json:"scopeType"`
	ScopePath  string             `json:"scopePath"`
	ModulePath *string            `json:"modulePath,omitempty"`
	FilePath   *string            `json:"filePath,omitempty"`
	SymbolName *string            `json:"symbolName,omitempty"`
}

type KnowledgeSection struct {
	ID               string               `json:"id"`
	ArtifactID       string               `json:"artifactId"`
	SectionKey       *string              `json:"sectionKey,omitempty"`
	Title            string               `json:"title"`
	Content          string               `json:"content"`
	Summary          *string              `json:"summary,omitempty"`
	Metadata         *string              `json:"metadata,omitempty"`
	Confidence       KnowledgeConfidence  `json:"confidence"`
	Inferred         bool                 `json:"inferred"`
	OrderIndex       int                  `json:"orderIndex"`
	RefinementStatus *string              `json:"refinementStatus,omitempty"`
	Evidence         []*KnowledgeEvidence `json:"evidence"`
}

type LLMUsageEntry struct {
	ID           string    `json:"id"`
	Provider     string    `json:"provider"`
	Model        string    `json:"model"`
	Operation    string    `json:"operation"`
	InputTokens  int       `json:"inputTokens"`
	OutputTokens int       `json:"outputTokens"`
	CreatedAt    time.Time `json:"createdAt"`
}

type LearningPathStep struct {
	Title         string               `json:"title"`
	Description   string               `json:"description"`
	TargetFiles   []string             `json:"targetFiles"`
	TargetSymbols []string             `json:"targetSymbols"`
	Difficulty    string               `json:"difficulty"`
	OrderIndex    int                  `json:"orderIndex"`
	Evidence      []*KnowledgeEvidence `json:"evidence"`
}

type LivingWikiConnectionTestResult struct {
	Provider string  `json:"provider"`
	Ok       bool    `json:"ok"`
	Message  *string `json:"message,omitempty"`
}

type LivingWikiJobResult struct {
	JobID          string     `json:"jobId"`
	StartedAt      time.Time  `json:"startedAt"`
	CompletedAt    *time.Time `json:"completedAt,omitempty"`
	PagesPlanned   int        `json:"pagesPlanned"`
	PagesGenerated int        `json:"pagesGenerated"`
	PagesExcluded  int        `json:"pagesExcluded"`
	// Page IDs excluded in this job. Used by the retryExcludedOnly path on the
	// next enableLivingWikiForRepo call.
	ExcludedPageIds []string `json:"excludedPageIds"`
	// Titles of pages generated by this job. Historical — does not reflect the
	// current PageStore state.
	GeneratedPageTitles []string `json:"generatedPageTitles"`
	ExclusionReasons    []string `json:"exclusionReasons"`
	// status is one of: running, ok, partial, failed.
	Status string `json:"status"`
	// failureCategory classifies terminal failures into one of three buckets that
	// drive distinct CTAs in the UI. Values: transient, auth, partial_content.
	// Empty when status is ok, partial, or running.
	FailureCategory *string `json:"failureCategory,omitempty"`
	ErrorMessage    *string `json:"errorMessage,omitempty"`
}

// LivingWikiSettings is the UI-managed living-wiki configuration.
//
// Secret fields (tokens, webhook secrets) are never returned in plaintext.
// When a secret has been stored, its value is the sentinel string "********".
// A non-sentinel value in an UpdateLivingWikiSettingsInput replaces the stored
// secret; the sentinel value is treated as "do not change".
type LivingWikiSettings struct {
	Enabled                 *bool      `json:"enabled,omitempty"`
	WorkerCount             *int       `json:"workerCount,omitempty"`
	EventTimeout            *string    `json:"eventTimeout,omitempty"`
	GithubToken             *string    `json:"githubToken,omitempty"`
	GitlabToken             *string    `json:"gitlabToken,omitempty"`
	ConfluenceEmail         *string    `json:"confluenceEmail,omitempty"`
	ConfluenceToken         *string    `json:"confluenceToken,omitempty"`
	NotionToken             *string    `json:"notionToken,omitempty"`
	ConfluenceWebhookSecret *string    `json:"confluenceWebhookSecret,omitempty"`
	NotionWebhookSecret     *string    `json:"notionWebhookSecret,omitempty"`
	UpdatedAt               *time.Time `json:"updatedAt,omitempty"`
	UpdatedBy               *string    `json:"updatedBy,omitempty"`
	// killSwitchActive is true when SOURCEBRIDGE_LIVING_WIKI_KILL_SWITCH=true is
	// set on the server at boot time. When true, the dispatcher is not running
	// even if enabled=true. The UI uses this to render State 1 (kill-switch
	// active) rather than the activation gate.
	KillSwitchActive bool `json:"killSwitchActive"`
}

type ModelCapabilityProfile struct {
	ID                     *string    `json:"id,omitempty"`
	ModelID                string     `json:"modelId"`
	Provider               string     `json:"provider"`
	DeclaredContextTokens  int        `json:"declaredContextTokens"`
	EffectiveContextTokens int        `json:"effectiveContextTokens"`
	InstructionFollowing   string     `json:"instructionFollowing"`
	JSONMode               string     `json:"jsonMode"`
	ToolUse                string     `json:"toolUse"`
	ExtractionGrade        string     `json:"extractionGrade"`
	CreativeGrade          string     `json:"creativeGrade"`
	EmbeddingModel         bool       `json:"embeddingModel"`
	CostPer1kInput         *float64   `json:"costPer1kInput,omitempty"`
	CostPer1kOutput        *float64   `json:"costPer1kOutput,omitempty"`
	LastProbedAt           *time.Time `json:"lastProbedAt,omitempty"`
	Source                 string     `json:"source"`
	Notes                  *string    `json:"notes,omitempty"`
	UpdatedAt              *time.Time `json:"updatedAt,omitempty"`
}

type Module struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Path      string `json:"path"`
	FileCount int    `json:"fileCount"`
}

type Mutation struct {
}

type MutationResult struct {
	Success bool    `json:"success"`
	Error   *string `json:"error,omitempty"`
}

type PlatformStats struct {
	Repositories      int `json:"repositories"`
	Files             int `json:"files"`
	Symbols           int `json:"symbols"`
	Requirements      int `json:"requirements"`
	Links             int `json:"links"`
	TotalInputTokens  int `json:"totalInputTokens"`
	TotalOutputTokens int `json:"totalOutputTokens"`
}

type PromoteResult struct {
	Requirement           *Requirement           `json:"requirement"`
	DiscoveredRequirement *DiscoveredRequirement `json:"discoveredRequirement"`
}

type Query struct {
}

type RepoLink struct {
	ID           string    `json:"id"`
	SourceRepoID string    `json:"sourceRepoId"`
	TargetRepoID string    `json:"targetRepoId"`
	LinkType     string    `json:"linkType"`
	CreatedAt    time.Time `json:"createdAt"`
}

type RepoWikiSink struct {
	Kind            RepoWikiSinkKind `json:"kind"`
	IntegrationName string           `json:"integrationName"`
	// Audience is per-sink, not per-repo.
	Audience   RepoWikiAudience   `json:"audience"`
	EditPolicy RepoWikiEditPolicy `json:"editPolicy"`
}

type RepoWikiSinkInput struct {
	Kind            RepoWikiSinkKind `json:"kind"`
	IntegrationName string           `json:"integrationName"`
	Audience        RepoWikiAudience `json:"audience"`
	// Omit to use the default edit policy for the sink kind.
	// Stage A silently applies the default; Stage B exposes it for override.
	EditPolicy *RepoWikiEditPolicy `json:"editPolicy,omitempty"`
}

type Repository struct {
	ID                      string                   `json:"id"`
	Name                    string                   `json:"name"`
	Path                    string                   `json:"path"`
	RemoteURL               *string                  `json:"remoteUrl,omitempty"`
	CommitSha               *string                  `json:"commitSha,omitempty"`
	Branch                  *string                  `json:"branch,omitempty"`
	GenerationModeDefault   *KnowledgeGenerationMode `json:"generationModeDefault,omitempty"`
	HasAuth                 bool                     `json:"hasAuth"`
	Status                  RepositoryStatus         `json:"status"`
	FileCount               int                      `json:"fileCount"`
	FunctionCount           int                      `json:"functionCount"`
	ClassCount              int                      `json:"classCount"`
	RequirementCount        int                      `json:"requirementCount"`
	LastIndexedAt           *time.Time               `json:"lastIndexedAt,omitempty"`
	CreatedAt               time.Time                `json:"createdAt"`
	Files                   *FileConnection          `json:"files"`
	Modules                 []*Module                `json:"modules"`
	UnderstandingScore      *UnderstandingScore      `json:"understandingScore,omitempty"`
	RepositoryUnderstanding *RepositoryUnderstanding `json:"repositoryUnderstanding,omitempty"`
	// Liveness of the stored index vs the canonical remote. Null for repos
	// that don't have a remote URL (local-path only). The lookup is a
	// cached `git ls-remote`; UI callers should poll this while the repo
	// page is visible to surface "N commits behind" signals.
	UpstreamStatus *RepositoryUpstreamStatus `json:"upstreamStatus,omitempty"`
	// Per-repo living-wiki opt-in configuration. Null when living-wiki has
	// never been configured for this repo (treated as disabled).
	LivingWikiSettings *RepositoryLivingWikiSettings `json:"livingWikiSettings,omitempty"`
}

type RepositoryLivingWikiSettings struct {
	Enabled           bool                  `json:"enabled"`
	Mode              RepoWikiMode          `json:"mode"`
	Sinks             []*RepoWikiSink       `json:"sinks"`
	ExcludePaths      []string              `json:"excludePaths"`
	StaleWhenStrategy RepoStaleWhenStrategy `json:"staleWhenStrategy"`
	MaxPagesPerJob    int                   `json:"maxPagesPerJob"`
	LastRunAt         *time.Time            `json:"lastRunAt,omitempty"`
	UpdatedAt         *time.Time            `json:"updatedAt,omitempty"`
	UpdatedBy         *string               `json:"updatedBy,omitempty"`
	// The most recent job result for this repo, surfaced in the settings panel
	// summary. Null when no job has been run yet.
	LastJobResult *LivingWikiJobResult `json:"lastJobResult,omitempty"`
	// Internal: the repo ID, threaded through from the parent resolver so
	// the lastJobResult field resolver can query JobResultStore. Not part
	// of the GraphQL schema — populated by mapRepoLivingWikiSettings.
	RepoID string `json:"-"`
}

type RepositoryUnderstanding struct {
	ID                string                            `json:"id"`
	RepositoryID      string                            `json:"repositoryId"`
	Scope             *KnowledgeScope                   `json:"scope"`
	CorpusID          *string                           `json:"corpusId,omitempty"`
	RevisionFp        string                            `json:"revisionFp"`
	Strategy          *string                           `json:"strategy,omitempty"`
	Stage             RepositoryUnderstandingStage      `json:"stage"`
	TreeStatus        RepositoryUnderstandingTreeStatus `json:"treeStatus"`
	CachedNodes       int                               `json:"cachedNodes"`
	TotalNodes        int                               `json:"totalNodes"`
	ModelUsed         *string                           `json:"modelUsed,omitempty"`
	FirstPassSections []*UnderstandingSection           `json:"firstPassSections"`
	RefreshAvailable  bool                              `json:"refreshAvailable"`
	CreatedAt         time.Time                         `json:"createdAt"`
	UpdatedAt         time.Time                         `json:"updatedAt"`
	ErrorCode         *string                           `json:"errorCode,omitempty"`
	ErrorMessage      *string                           `json:"errorMessage,omitempty"`
}

// Snapshot of the upstream remote's HEAD for the repo's tracked branch,
// compared against the repo's stored indexed commit. `checkedAt` is when
// the server last refreshed its cache (typically within the last ~30s).
type RepositoryUpstreamStatus struct {
	Status            UpstreamStatus `json:"status"`
	UpstreamCommitSha *string        `json:"upstreamCommitSha,omitempty"`
	IndexedCommitSha  *string        `json:"indexedCommitSha,omitempty"`
	CheckedAt         time.Time      `json:"checkedAt"`
	ErrorMessage      *string        `json:"errorMessage,omitempty"`
}

type Requirement struct {
	ID          string   `json:"id"`
	ExternalID  *string  `json:"externalId,omitempty"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Source      string   `json:"source"`
	Priority    *string  `json:"priority,omitempty"`
	Tags        []string `json:"tags"`
	// Ordered acceptance criteria bullet-list. Writable via
	// updateRequirementFields; readable here. Empty list when unset (never null).
	AcceptanceCriteria []string           `json:"acceptanceCriteria"`
	Links              []*RequirementLink `json:"links"`
	CreatedAt          time.Time          `json:"createdAt"`
	UpdatedAt          *time.Time         `json:"updatedAt,omitempty"`
}

type RequirementConnection struct {
	Nodes      []*Requirement `json:"nodes"`
	TotalCount int            `json:"totalCount"`
}

type RequirementLink struct {
	ID            string       `json:"id"`
	RequirementID string       `json:"requirementId"`
	SymbolID      string       `json:"symbolId"`
	Confidence    Confidence   `json:"confidence"`
	Rationale     *string      `json:"rationale,omitempty"`
	Verified      bool         `json:"verified"`
	VerifiedBy    *string      `json:"verifiedBy,omitempty"`
	Symbol        *CodeSymbol  `json:"symbol,omitempty"`
	Requirement   *Requirement `json:"requirement,omitempty"`
	CreatedAt     time.Time    `json:"createdAt"`
}

type RequirementLinkConnection struct {
	Nodes      []*RequirementLink `json:"nodes"`
	TotalCount int                `json:"totalCount"`
}

type ResolvedSymbol struct {
	SymbolID      string  `json:"symbolId"`
	Name          string  `json:"name"`
	QualifiedName string  `json:"qualifiedName"`
	Kind          string  `json:"kind"`
	FilePath      string  `json:"filePath"`
	Similarity    float64 `json:"similarity"`
	IsAnchor      bool    `json:"isAnchor"`
}

type RestoreResult struct {
	RestoredID string  `json:"restoredId"`
	BatchSize  int     `json:"batchSize"`
	Renamed    bool    `json:"renamed"`
	NewKey     *string `json:"newKey,omitempty"`
}

type ReviewCodeInput struct {
	RepositoryID string    `json:"repositoryId"`
	FilePath     string    `json:"filePath"`
	Template     string    `json:"template"`
	Code         *string   `json:"code,omitempty"`
	Language     *Language `json:"language,omitempty"`
}

type ReviewFinding struct {
	Category   string  `json:"category"`
	Severity   string  `json:"severity"`
	Message    string  `json:"message"`
	FilePath   *string `json:"filePath,omitempty"`
	StartLine  *int    `json:"startLine,omitempty"`
	EndLine    *int    `json:"endLine,omitempty"`
	Suggestion *string `json:"suggestion,omitempty"`
}

type ReviewResult struct {
	Template     string           `json:"template"`
	Findings     []*ReviewFinding `json:"findings"`
	Score        float64          `json:"score"`
	Model        *string          `json:"model,omitempty"`
	InputTokens  *int             `json:"inputTokens,omitempty"`
	OutputTokens *int             `json:"outputTokens,omitempty"`
}

type ScopeChild struct {
	ScopeType   KnowledgeScopeType `json:"scopeType"`
	Label       string             `json:"label"`
	ScopePath   string             `json:"scopePath"`
	HasArtifact bool               `json:"hasArtifact"`
	Summary     *string            `json:"summary,omitempty"`
}

type ScopeOrigin struct {
	Type string `json:"type"`
	Key  string `json:"key"`
}

type SearchResult struct {
	Type           string         `json:"type"`
	ID             string         `json:"id"`
	Title          string         `json:"title"`
	Description    *string        `json:"description,omitempty"`
	FilePath       *string        `json:"filePath,omitempty"`
	Line           *int           `json:"line,omitempty"`
	RepositoryID   string         `json:"repositoryId"`
	RepositoryName string         `json:"repositoryName"`
	Score          *float64       `json:"score,omitempty"`
	Signals        *SearchSignals `json:"signals,omitempty"`
}

type SearchSignals struct {
	Exact       *float64 `json:"exact,omitempty"`
	Lexical     *float64 `json:"lexical,omitempty"`
	Semantic    *float64 `json:"semantic,omitempty"`
	Graph       *float64 `json:"graph,omitempty"`
	Requirement *float64 `json:"requirement,omitempty"`
}

type ServiceHealth struct {
	Name   string `json:"name"`
	Status string `json:"status"`
}

type SimulateChangeInput struct {
	RepositoryID string  `json:"repositoryId"`
	Description  string  `json:"description"`
	AnchorFile   *string `json:"anchorFile,omitempty"`
	AnchorSymbol *string `json:"anchorSymbol,omitempty"`
}

type SimulatedImpactReport struct {
	ID              string            `json:"id"`
	Simulated       bool              `json:"simulated"`
	Description     string            `json:"description"`
	AnchorFile      *string           `json:"anchorFile,omitempty"`
	AnchorSymbol    *string           `json:"anchorSymbol,omitempty"`
	ResolvedSymbols []*ResolvedSymbol `json:"resolvedSymbols"`
	Report          *ImpactReport     `json:"report"`
	ComputedAt      time.Time         `json:"computedAt"`
}

type SourceFile struct {
	RepositoryID string   `json:"repositoryId"`
	FilePath     string   `json:"filePath"`
	Language     Language `json:"language"`
	LineCount    int      `json:"lineCount"`
	Content      string   `json:"content"`
	ContentHash  *string  `json:"contentHash,omitempty"`
}

type SourceFileResult struct {
	Ok        bool        `json:"ok"`
	ErrorCode *string     `json:"errorCode,omitempty"`
	Message   *string     `json:"message,omitempty"`
	File      *SourceFile `json:"file,omitempty"`
}

type SourceRevision struct {
	CommitSha          *string `json:"commitSha,omitempty"`
	Branch             *string `json:"branch,omitempty"`
	ContentFingerprint *string `json:"contentFingerprint,omitempty"`
	DocsFingerprint    *string `json:"docsFingerprint,omitempty"`
}

type SpecExtractionResult struct {
	Discovered      int      `json:"discovered"`
	TotalCandidates int      `json:"totalCandidates"`
	Warnings        []string `json:"warnings"`
	Model           *string  `json:"model,omitempty"`
	InputTokens     *int     `json:"inputTokens,omitempty"`
	OutputTokens    *int     `json:"outputTokens,omitempty"`
}

// StaleReason explains which changes caused an artifact to be marked stale.
// Surfaces progressive-disclosure "what changed" context in the UI.
type StaleReason struct {
	// Symbol IDs whose change triggered the invalidation (may be empty).
	Symbols []string `json:"symbols"`
	// File paths whose change triggered the invalidation (may be empty).
	Files []string `json:"files"`
	// True when the artifact was staled without specific attribution
	// (missing evidence, whole-repo evidence only, or change-set-size fallback).
	Blanket bool `json:"blanket"`
	// ID of the ImpactReport that caused the invalidation (may be empty).
	ReportID *string `json:"reportId,omitempty"`
}

type SymbolChange struct {
	SymbolID     *string          `json:"symbolId,omitempty"`
	Name         string           `json:"name"`
	FilePath     string           `json:"filePath"`
	ChangeType   SymbolChangeType `json:"changeType"`
	OldSignature *string          `json:"oldSignature,omitempty"`
	NewSignature *string          `json:"newSignature,omitempty"`
}

type SymbolConnection struct {
	Nodes      []*CodeSymbol `json:"nodes"`
	TotalCount int           `json:"totalCount"`
}

type TraceabilityMatrix struct {
	Requirements []*Requirement     `json:"requirements"`
	Symbols      []*CodeSymbol      `json:"symbols"`
	Links        []*RequirementLink `json:"links"`
	Coverage     float64            `json:"coverage"`
}

type TrashConnection struct {
	Nodes         []*TrashEntry `json:"nodes"`
	TotalCount    int           `json:"totalCount"`
	RetentionDays int           `json:"retentionDays"`
}

type TrashEntry struct {
	ID              string        `json:"id"`
	Type            TrashableType `json:"type"`
	RepositoryID    *string       `json:"repositoryId,omitempty"`
	Label           string        `json:"label"`
	OriginalKey     *string       `json:"originalKey,omitempty"`
	DeletedAt       string        `json:"deletedAt"`
	DeletedBy       *string       `json:"deletedBy,omitempty"`
	ExpiresAt       string        `json:"expiresAt"`
	CanRestore      bool          `json:"canRestore"`
	RestoreConflict *string       `json:"restoreConflict,omitempty"`
	TrashBatchID    string        `json:"trashBatchId"`
}

type TriggerSpecExtractionInput struct {
	RepositoryID      string `json:"repositoryId"`
	SkipLlmRefinement *bool  `json:"skipLlmRefinement,omitempty"`
}

type UnderstandingScore struct {
	Overall               float64   `json:"overall"`
	TraceabilityCoverage  float64   `json:"traceabilityCoverage"`
	DocumentationCoverage float64   `json:"documentationCoverage"`
	ReviewCoverage        float64   `json:"reviewCoverage"`
	TestCoverage          float64   `json:"testCoverage"`
	KnowledgeFreshness    float64   `json:"knowledgeFreshness"`
	AiCodeRatio           float64   `json:"aiCodeRatio"`
	ComputedAt            time.Time `json:"computedAt"`
}

type UnderstandingSection struct {
	Title   string `json:"title"`
	Summary string `json:"summary"`
}

type UpdateComprehensionSettingsInput struct {
	ScopeType                      string                   `json:"scopeType"`
	ScopeKey                       *string                  `json:"scopeKey,omitempty"`
	StrategyPreferenceChain        []string                 `json:"strategyPreferenceChain,omitempty"`
	KnowledgeGenerationModeDefault *KnowledgeGenerationMode `json:"knowledgeGenerationModeDefault,omitempty"`
	ModelID                        *string                  `json:"modelId,omitempty"`
	MaxConcurrency                 *int                     `json:"maxConcurrency,omitempty"`
	MaxPromptTokens                *int                     `json:"maxPromptTokens,omitempty"`
	LeafBudgetTokens               *int                     `json:"leafBudgetTokens,omitempty"`
	RefinePassEnabled              *bool                    `json:"refinePassEnabled,omitempty"`
	LongContextMaxTokens           *int                     `json:"longContextMaxTokens,omitempty"`
	GraphragEntityTypes            []string                 `json:"graphragEntityTypes,omitempty"`
	CacheEnabled                   *bool                    `json:"cacheEnabled,omitempty"`
	AllowUnsafeCombinations        *bool                    `json:"allowUnsafeCombinations,omitempty"`
}

type UpdateLivingWikiSettingsInput struct {
	Enabled                 *bool   `json:"enabled,omitempty"`
	WorkerCount             *int    `json:"workerCount,omitempty"`
	EventTimeout            *string `json:"eventTimeout,omitempty"`
	GithubToken             *string `json:"githubToken,omitempty"`
	GitlabToken             *string `json:"gitlabToken,omitempty"`
	ConfluenceEmail         *string `json:"confluenceEmail,omitempty"`
	ConfluenceToken         *string `json:"confluenceToken,omitempty"`
	NotionToken             *string `json:"notionToken,omitempty"`
	ConfluenceWebhookSecret *string `json:"confluenceWebhookSecret,omitempty"`
	NotionWebhookSecret     *string `json:"notionWebhookSecret,omitempty"`
}

type UpdateModelCapabilitiesInput struct {
	ModelID                string  `json:"modelId"`
	Provider               *string `json:"provider,omitempty"`
	DeclaredContextTokens  *int    `json:"declaredContextTokens,omitempty"`
	EffectiveContextTokens *int    `json:"effectiveContextTokens,omitempty"`
	InstructionFollowing   *string `json:"instructionFollowing,omitempty"`
	JSONMode               *string `json:"jsonMode,omitempty"`
	ToolUse                *string `json:"toolUse,omitempty"`
	ExtractionGrade        *string `json:"extractionGrade,omitempty"`
	CreativeGrade          *string `json:"creativeGrade,omitempty"`
	EmbeddingModel         *bool   `json:"embeddingModel,omitempty"`
	Source                 *string `json:"source,omitempty"`
	Notes                  *string `json:"notes,omitempty"`
}

type UpdateRepositoryKnowledgeSettingsInput struct {
	RepositoryID          string                  `json:"repositoryId"`
	GenerationModeDefault KnowledgeGenerationMode `json:"generationModeDefault"`
}

type UpdateRepositoryLivingWikiSettingsInput struct {
	RepositoryID      string                 `json:"repositoryId"`
	Enabled           *bool                  `json:"enabled,omitempty"`
	Mode              *RepoWikiMode          `json:"mode,omitempty"`
	Sinks             []*RepoWikiSinkInput   `json:"sinks,omitempty"`
	ExcludePaths      []string               `json:"excludePaths,omitempty"`
	StaleWhenStrategy *RepoStaleWhenStrategy `json:"staleWhenStrategy,omitempty"`
	MaxPagesPerJob    *int                   `json:"maxPagesPerJob,omitempty"`
}

// Patch an existing requirement. Every non-null field replaces the
// stored value; null fields preserve it. `externalId` uniqueness is
// enforced against active (non-trashed) rows in the same repository.
type UpdateRequirementFieldsInput struct {
	ID                 string   `json:"id"`
	ExternalID         *string  `json:"externalId,omitempty"`
	Title              *string  `json:"title,omitempty"`
	Description        *string  `json:"description,omitempty"`
	Priority           *string  `json:"priority,omitempty"`
	Source             *string  `json:"source,omitempty"`
	Tags               []string `json:"tags,omitempty"`
	AcceptanceCriteria []string `json:"acceptanceCriteria,omitempty"`
}

type VersionInfo struct {
	Version   string `json:"version"`
	Commit    string `json:"commit"`
	BuildDate string `json:"buildDate"`
}

type Confidence string

const (
	ConfidenceLow      Confidence = "LOW"
	ConfidenceMedium   Confidence = "MEDIUM"
	ConfidenceHigh     Confidence = "HIGH"
	ConfidenceVerified Confidence = "VERIFIED"
)

var AllConfidence = []Confidence{
	ConfidenceLow,
	ConfidenceMedium,
	ConfidenceHigh,
	ConfidenceVerified,
}

func (e Confidence) IsValid() bool {
	switch e {
	case ConfidenceLow, ConfidenceMedium, ConfidenceHigh, ConfidenceVerified:
		return true
	}
	return false
}

func (e Confidence) String() string {
	return string(e)
}

func (e *Confidence) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Confidence(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Confidence", str)
	}
	return nil
}

func (e Confidence) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Confidence) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Confidence) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CrossRepoRefType string

const (
	CrossRepoRefTypeAPIEndpoint     CrossRepoRefType = "API_ENDPOINT"
	CrossRepoRefTypeProtobufService CrossRepoRefType = "PROTOBUF_SERVICE"
	CrossRepoRefTypeGraphqlType     CrossRepoRefType = "GRAPHQL_TYPE"
	CrossRepoRefTypeImport          CrossRepoRefType = "IMPORT"
	CrossRepoRefTypeTypeReference   CrossRepoRefType = "TYPE_REFERENCE"
)

var AllCrossRepoRefType = []CrossRepoRefType{
	CrossRepoRefTypeAPIEndpoint,
	CrossRepoRefTypeProtobufService,
	CrossRepoRefTypeGraphqlType,
	CrossRepoRefTypeImport,
	CrossRepoRefTypeTypeReference,
}

func (e CrossRepoRefType) IsValid() bool {
	switch e {
	case CrossRepoRefTypeAPIEndpoint, CrossRepoRefTypeProtobufService, CrossRepoRefTypeGraphqlType, CrossRepoRefTypeImport, CrossRepoRefTypeTypeReference:
		return true
	}
	return false
}

func (e CrossRepoRefType) String() string {
	return string(e)
}

func (e *CrossRepoRefType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CrossRepoRefType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CrossRepoRefType", str)
	}
	return nil
}

func (e CrossRepoRefType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CrossRepoRefType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CrossRepoRefType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DiagramLevel string

const (
	DiagramLevelModule DiagramLevel = "MODULE"
	DiagramLevelFile   DiagramLevel = "FILE"
)

var AllDiagramLevel = []DiagramLevel{
	DiagramLevelModule,
	DiagramLevelFile,
}

func (e DiagramLevel) IsValid() bool {
	switch e {
	case DiagramLevelModule, DiagramLevelFile:
		return true
	}
	return false
}

func (e DiagramLevel) String() string {
	return string(e)
}

func (e *DiagramLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DiagramLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DiagramLevel", str)
	}
	return nil
}

func (e DiagramLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DiagramLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DiagramLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DiffStatus string

const (
	DiffStatusAdded    DiffStatus = "ADDED"
	DiffStatusModified DiffStatus = "MODIFIED"
	DiffStatusDeleted  DiffStatus = "DELETED"
	DiffStatusRenamed  DiffStatus = "RENAMED"
)

var AllDiffStatus = []DiffStatus{
	DiffStatusAdded,
	DiffStatusModified,
	DiffStatusDeleted,
	DiffStatusRenamed,
}

func (e DiffStatus) IsValid() bool {
	switch e {
	case DiffStatusAdded, DiffStatusModified, DiffStatusDeleted, DiffStatusRenamed:
		return true
	}
	return false
}

func (e DiffStatus) String() string {
	return string(e)
}

func (e *DiffStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DiffStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DiffStatus", str)
	}
	return nil
}

func (e DiffStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DiffStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DiffStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EvidenceSourceType string

const (
	EvidenceSourceTypeRepository    EvidenceSourceType = "REPOSITORY"
	EvidenceSourceTypeFile          EvidenceSourceType = "FILE"
	EvidenceSourceTypeSymbol        EvidenceSourceType = "SYMBOL"
	EvidenceSourceTypeRequirement   EvidenceSourceType = "REQUIREMENT"
	EvidenceSourceTypeLink          EvidenceSourceType = "LINK"
	EvidenceSourceTypeTest          EvidenceSourceType = "TEST"
	EvidenceSourceTypeCommit        EvidenceSourceType = "COMMIT"
	EvidenceSourceTypeDocumentation EvidenceSourceType = "DOCUMENTATION"
)

var AllEvidenceSourceType = []EvidenceSourceType{
	EvidenceSourceTypeRepository,
	EvidenceSourceTypeFile,
	EvidenceSourceTypeSymbol,
	EvidenceSourceTypeRequirement,
	EvidenceSourceTypeLink,
	EvidenceSourceTypeTest,
	EvidenceSourceTypeCommit,
	EvidenceSourceTypeDocumentation,
}

func (e EvidenceSourceType) IsValid() bool {
	switch e {
	case EvidenceSourceTypeRepository, EvidenceSourceTypeFile, EvidenceSourceTypeSymbol, EvidenceSourceTypeRequirement, EvidenceSourceTypeLink, EvidenceSourceTypeTest, EvidenceSourceTypeCommit, EvidenceSourceTypeDocumentation:
		return true
	}
	return false
}

func (e EvidenceSourceType) String() string {
	return string(e)
}

func (e *EvidenceSourceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EvidenceSourceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EvidenceSourceType", str)
	}
	return nil
}

func (e EvidenceSourceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EvidenceSourceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EvidenceSourceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ExecutionEntryKind string

const (
	ExecutionEntryKindRoute  ExecutionEntryKind = "ROUTE"
	ExecutionEntryKindFile   ExecutionEntryKind = "FILE"
	ExecutionEntryKindSymbol ExecutionEntryKind = "SYMBOL"
)

var AllExecutionEntryKind = []ExecutionEntryKind{
	ExecutionEntryKindRoute,
	ExecutionEntryKindFile,
	ExecutionEntryKindSymbol,
}

func (e ExecutionEntryKind) IsValid() bool {
	switch e {
	case ExecutionEntryKindRoute, ExecutionEntryKindFile, ExecutionEntryKindSymbol:
		return true
	}
	return false
}

func (e ExecutionEntryKind) String() string {
	return string(e)
}

func (e *ExecutionEntryKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ExecutionEntryKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ExecutionEntryKind", str)
	}
	return nil
}

func (e ExecutionEntryKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ExecutionEntryKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ExecutionEntryKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type KnowledgeArtifactStatus string

const (
	KnowledgeArtifactStatusPending    KnowledgeArtifactStatus = "PENDING"
	KnowledgeArtifactStatusGenerating KnowledgeArtifactStatus = "GENERATING"
	KnowledgeArtifactStatusReady      KnowledgeArtifactStatus = "READY"
	KnowledgeArtifactStatusFailed     KnowledgeArtifactStatus = "FAILED"
	KnowledgeArtifactStatusStale      KnowledgeArtifactStatus = "STALE"
)

var AllKnowledgeArtifactStatus = []KnowledgeArtifactStatus{
	KnowledgeArtifactStatusPending,
	KnowledgeArtifactStatusGenerating,
	KnowledgeArtifactStatusReady,
	KnowledgeArtifactStatusFailed,
	KnowledgeArtifactStatusStale,
}

func (e KnowledgeArtifactStatus) IsValid() bool {
	switch e {
	case KnowledgeArtifactStatusPending, KnowledgeArtifactStatusGenerating, KnowledgeArtifactStatusReady, KnowledgeArtifactStatusFailed, KnowledgeArtifactStatusStale:
		return true
	}
	return false
}

func (e KnowledgeArtifactStatus) String() string {
	return string(e)
}

func (e *KnowledgeArtifactStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = KnowledgeArtifactStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid KnowledgeArtifactStatus", str)
	}
	return nil
}

func (e KnowledgeArtifactStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *KnowledgeArtifactStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e KnowledgeArtifactStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type KnowledgeArtifactType string

const (
	KnowledgeArtifactTypeCliffNotes          KnowledgeArtifactType = "CLIFF_NOTES"
	KnowledgeArtifactTypeArchitectureDiagram KnowledgeArtifactType = "ARCHITECTURE_DIAGRAM"
	KnowledgeArtifactTypeLearningPath        KnowledgeArtifactType = "LEARNING_PATH"
	KnowledgeArtifactTypeCodeTour            KnowledgeArtifactType = "CODE_TOUR"
	KnowledgeArtifactTypeWorkflowStory       KnowledgeArtifactType = "WORKFLOW_STORY"
)

var AllKnowledgeArtifactType = []KnowledgeArtifactType{
	KnowledgeArtifactTypeCliffNotes,
	KnowledgeArtifactTypeArchitectureDiagram,
	KnowledgeArtifactTypeLearningPath,
	KnowledgeArtifactTypeCodeTour,
	KnowledgeArtifactTypeWorkflowStory,
}

func (e KnowledgeArtifactType) IsValid() bool {
	switch e {
	case KnowledgeArtifactTypeCliffNotes, KnowledgeArtifactTypeArchitectureDiagram, KnowledgeArtifactTypeLearningPath, KnowledgeArtifactTypeCodeTour, KnowledgeArtifactTypeWorkflowStory:
		return true
	}
	return false
}

func (e KnowledgeArtifactType) String() string {
	return string(e)
}

func (e *KnowledgeArtifactType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = KnowledgeArtifactType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid KnowledgeArtifactType", str)
	}
	return nil
}

func (e KnowledgeArtifactType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *KnowledgeArtifactType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e KnowledgeArtifactType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type KnowledgeAudience string

const (
	KnowledgeAudienceBeginner  KnowledgeAudience = "BEGINNER"
	KnowledgeAudienceDeveloper KnowledgeAudience = "DEVELOPER"
)

var AllKnowledgeAudience = []KnowledgeAudience{
	KnowledgeAudienceBeginner,
	KnowledgeAudienceDeveloper,
}

func (e KnowledgeAudience) IsValid() bool {
	switch e {
	case KnowledgeAudienceBeginner, KnowledgeAudienceDeveloper:
		return true
	}
	return false
}

func (e KnowledgeAudience) String() string {
	return string(e)
}

func (e *KnowledgeAudience) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = KnowledgeAudience(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid KnowledgeAudience", str)
	}
	return nil
}

func (e KnowledgeAudience) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *KnowledgeAudience) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e KnowledgeAudience) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type KnowledgeConfidence string

const (
	KnowledgeConfidenceHigh   KnowledgeConfidence = "HIGH"
	KnowledgeConfidenceMedium KnowledgeConfidence = "MEDIUM"
	KnowledgeConfidenceLow    KnowledgeConfidence = "LOW"
)

var AllKnowledgeConfidence = []KnowledgeConfidence{
	KnowledgeConfidenceHigh,
	KnowledgeConfidenceMedium,
	KnowledgeConfidenceLow,
}

func (e KnowledgeConfidence) IsValid() bool {
	switch e {
	case KnowledgeConfidenceHigh, KnowledgeConfidenceMedium, KnowledgeConfidenceLow:
		return true
	}
	return false
}

func (e KnowledgeConfidence) String() string {
	return string(e)
}

func (e *KnowledgeConfidence) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = KnowledgeConfidence(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid KnowledgeConfidence", str)
	}
	return nil
}

func (e KnowledgeConfidence) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *KnowledgeConfidence) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e KnowledgeConfidence) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type KnowledgeDepth string

const (
	KnowledgeDepthSummary KnowledgeDepth = "SUMMARY"
	KnowledgeDepthMedium  KnowledgeDepth = "MEDIUM"
	KnowledgeDepthDeep    KnowledgeDepth = "DEEP"
)

var AllKnowledgeDepth = []KnowledgeDepth{
	KnowledgeDepthSummary,
	KnowledgeDepthMedium,
	KnowledgeDepthDeep,
}

func (e KnowledgeDepth) IsValid() bool {
	switch e {
	case KnowledgeDepthSummary, KnowledgeDepthMedium, KnowledgeDepthDeep:
		return true
	}
	return false
}

func (e KnowledgeDepth) String() string {
	return string(e)
}

func (e *KnowledgeDepth) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = KnowledgeDepth(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid KnowledgeDepth", str)
	}
	return nil
}

func (e KnowledgeDepth) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *KnowledgeDepth) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e KnowledgeDepth) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type KnowledgeGenerationMode string

const (
	KnowledgeGenerationModeClassic            KnowledgeGenerationMode = "CLASSIC"
	KnowledgeGenerationModeUnderstandingFirst KnowledgeGenerationMode = "UNDERSTANDING_FIRST"
)

var AllKnowledgeGenerationMode = []KnowledgeGenerationMode{
	KnowledgeGenerationModeClassic,
	KnowledgeGenerationModeUnderstandingFirst,
}

func (e KnowledgeGenerationMode) IsValid() bool {
	switch e {
	case KnowledgeGenerationModeClassic, KnowledgeGenerationModeUnderstandingFirst:
		return true
	}
	return false
}

func (e KnowledgeGenerationMode) String() string {
	return string(e)
}

func (e *KnowledgeGenerationMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = KnowledgeGenerationMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid KnowledgeGenerationMode", str)
	}
	return nil
}

func (e KnowledgeGenerationMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *KnowledgeGenerationMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e KnowledgeGenerationMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type KnowledgeScopeType string

const (
	KnowledgeScopeTypeRepository  KnowledgeScopeType = "REPOSITORY"
	KnowledgeScopeTypeModule      KnowledgeScopeType = "MODULE"
	KnowledgeScopeTypeFile        KnowledgeScopeType = "FILE"
	KnowledgeScopeTypeSymbol      KnowledgeScopeType = "SYMBOL"
	KnowledgeScopeTypeRequirement KnowledgeScopeType = "REQUIREMENT"
)

var AllKnowledgeScopeType = []KnowledgeScopeType{
	KnowledgeScopeTypeRepository,
	KnowledgeScopeTypeModule,
	KnowledgeScopeTypeFile,
	KnowledgeScopeTypeSymbol,
	KnowledgeScopeTypeRequirement,
}

func (e KnowledgeScopeType) IsValid() bool {
	switch e {
	case KnowledgeScopeTypeRepository, KnowledgeScopeTypeModule, KnowledgeScopeTypeFile, KnowledgeScopeTypeSymbol, KnowledgeScopeTypeRequirement:
		return true
	}
	return false
}

func (e KnowledgeScopeType) String() string {
	return string(e)
}

func (e *KnowledgeScopeType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = KnowledgeScopeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid KnowledgeScopeType", str)
	}
	return nil
}

func (e KnowledgeScopeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *KnowledgeScopeType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e KnowledgeScopeType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Language string

const (
	LanguageGo         Language = "GO"
	LanguagePython     Language = "PYTHON"
	LanguageTypescript Language = "TYPESCRIPT"
	LanguageJavascript Language = "JAVASCRIPT"
	LanguageJava       Language = "JAVA"
	LanguageRust       Language = "RUST"
	LanguageCsharp     Language = "CSHARP"
	LanguageCpp        Language = "CPP"
	LanguageRuby       Language = "RUBY"
	LanguagePhp        Language = "PHP"
	LanguageUnknown    Language = "UNKNOWN"
)

var AllLanguage = []Language{
	LanguageGo,
	LanguagePython,
	LanguageTypescript,
	LanguageJavascript,
	LanguageJava,
	LanguageRust,
	LanguageCsharp,
	LanguageCpp,
	LanguageRuby,
	LanguagePhp,
	LanguageUnknown,
}

func (e Language) IsValid() bool {
	switch e {
	case LanguageGo, LanguagePython, LanguageTypescript, LanguageJavascript, LanguageJava, LanguageRust, LanguageCsharp, LanguageCpp, LanguageRuby, LanguagePhp, LanguageUnknown:
		return true
	}
	return false
}

func (e Language) String() string {
	return string(e)
}

func (e *Language) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Language(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Language", str)
	}
	return nil
}

func (e Language) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Language) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Language) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RepoStaleWhenStrategy string

const (
	RepoStaleWhenStrategyDirect     RepoStaleWhenStrategy = "DIRECT"
	RepoStaleWhenStrategyTransitive RepoStaleWhenStrategy = "TRANSITIVE"
)

var AllRepoStaleWhenStrategy = []RepoStaleWhenStrategy{
	RepoStaleWhenStrategyDirect,
	RepoStaleWhenStrategyTransitive,
}

func (e RepoStaleWhenStrategy) IsValid() bool {
	switch e {
	case RepoStaleWhenStrategyDirect, RepoStaleWhenStrategyTransitive:
		return true
	}
	return false
}

func (e RepoStaleWhenStrategy) String() string {
	return string(e)
}

func (e *RepoStaleWhenStrategy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RepoStaleWhenStrategy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RepoStaleWhenStrategy", str)
	}
	return nil
}

func (e RepoStaleWhenStrategy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RepoStaleWhenStrategy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RepoStaleWhenStrategy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RepoWikiAudience string

const (
	RepoWikiAudienceEngineer RepoWikiAudience = "ENGINEER"
	RepoWikiAudienceProduct  RepoWikiAudience = "PRODUCT"
	RepoWikiAudienceOperator RepoWikiAudience = "OPERATOR"
)

var AllRepoWikiAudience = []RepoWikiAudience{
	RepoWikiAudienceEngineer,
	RepoWikiAudienceProduct,
	RepoWikiAudienceOperator,
}

func (e RepoWikiAudience) IsValid() bool {
	switch e {
	case RepoWikiAudienceEngineer, RepoWikiAudienceProduct, RepoWikiAudienceOperator:
		return true
	}
	return false
}

func (e RepoWikiAudience) String() string {
	return string(e)
}

func (e *RepoWikiAudience) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RepoWikiAudience(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RepoWikiAudience", str)
	}
	return nil
}

func (e RepoWikiAudience) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RepoWikiAudience) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RepoWikiAudience) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RepoWikiEditPolicy string

const (
	RepoWikiEditPolicyProposePr     RepoWikiEditPolicy = "PROPOSE_PR"
	RepoWikiEditPolicyDirectPublish RepoWikiEditPolicy = "DIRECT_PUBLISH"
)

var AllRepoWikiEditPolicy = []RepoWikiEditPolicy{
	RepoWikiEditPolicyProposePr,
	RepoWikiEditPolicyDirectPublish,
}

func (e RepoWikiEditPolicy) IsValid() bool {
	switch e {
	case RepoWikiEditPolicyProposePr, RepoWikiEditPolicyDirectPublish:
		return true
	}
	return false
}

func (e RepoWikiEditPolicy) String() string {
	return string(e)
}

func (e *RepoWikiEditPolicy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RepoWikiEditPolicy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RepoWikiEditPolicy", str)
	}
	return nil
}

func (e RepoWikiEditPolicy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RepoWikiEditPolicy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RepoWikiEditPolicy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RepoWikiMode string

const (
	RepoWikiModePrReview      RepoWikiMode = "PR_REVIEW"
	RepoWikiModeDirectPublish RepoWikiMode = "DIRECT_PUBLISH"
)

var AllRepoWikiMode = []RepoWikiMode{
	RepoWikiModePrReview,
	RepoWikiModeDirectPublish,
}

func (e RepoWikiMode) IsValid() bool {
	switch e {
	case RepoWikiModePrReview, RepoWikiModeDirectPublish:
		return true
	}
	return false
}

func (e RepoWikiMode) String() string {
	return string(e)
}

func (e *RepoWikiMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RepoWikiMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RepoWikiMode", str)
	}
	return nil
}

func (e RepoWikiMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RepoWikiMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RepoWikiMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RepoWikiSinkKind string

const (
	RepoWikiSinkKindGitRepo           RepoWikiSinkKind = "GIT_REPO"
	RepoWikiSinkKindConfluence        RepoWikiSinkKind = "CONFLUENCE"
	RepoWikiSinkKindNotion            RepoWikiSinkKind = "NOTION"
	RepoWikiSinkKindGithubWiki        RepoWikiSinkKind = "GITHUB_WIKI"
	RepoWikiSinkKindGitlabWiki        RepoWikiSinkKind = "GITLAB_WIKI"
	RepoWikiSinkKindBackstageTechdocs RepoWikiSinkKind = "BACKSTAGE_TECHDOCS"
	RepoWikiSinkKindMkdocs            RepoWikiSinkKind = "MKDOCS"
	RepoWikiSinkKindDocusaurus        RepoWikiSinkKind = "DOCUSAURUS"
	RepoWikiSinkKindVitepress         RepoWikiSinkKind = "VITEPRESS"
)

var AllRepoWikiSinkKind = []RepoWikiSinkKind{
	RepoWikiSinkKindGitRepo,
	RepoWikiSinkKindConfluence,
	RepoWikiSinkKindNotion,
	RepoWikiSinkKindGithubWiki,
	RepoWikiSinkKindGitlabWiki,
	RepoWikiSinkKindBackstageTechdocs,
	RepoWikiSinkKindMkdocs,
	RepoWikiSinkKindDocusaurus,
	RepoWikiSinkKindVitepress,
}

func (e RepoWikiSinkKind) IsValid() bool {
	switch e {
	case RepoWikiSinkKindGitRepo, RepoWikiSinkKindConfluence, RepoWikiSinkKindNotion, RepoWikiSinkKindGithubWiki, RepoWikiSinkKindGitlabWiki, RepoWikiSinkKindBackstageTechdocs, RepoWikiSinkKindMkdocs, RepoWikiSinkKindDocusaurus, RepoWikiSinkKindVitepress:
		return true
	}
	return false
}

func (e RepoWikiSinkKind) String() string {
	return string(e)
}

func (e *RepoWikiSinkKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RepoWikiSinkKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RepoWikiSinkKind", str)
	}
	return nil
}

func (e RepoWikiSinkKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RepoWikiSinkKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RepoWikiSinkKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RepositoryStatus string

const (
	RepositoryStatusPending  RepositoryStatus = "PENDING"
	RepositoryStatusIndexing RepositoryStatus = "INDEXING"
	RepositoryStatusReady    RepositoryStatus = "READY"
	RepositoryStatusError    RepositoryStatus = "ERROR"
)

var AllRepositoryStatus = []RepositoryStatus{
	RepositoryStatusPending,
	RepositoryStatusIndexing,
	RepositoryStatusReady,
	RepositoryStatusError,
}

func (e RepositoryStatus) IsValid() bool {
	switch e {
	case RepositoryStatusPending, RepositoryStatusIndexing, RepositoryStatusReady, RepositoryStatusError:
		return true
	}
	return false
}

func (e RepositoryStatus) String() string {
	return string(e)
}

func (e *RepositoryStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RepositoryStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RepositoryStatus", str)
	}
	return nil
}

func (e RepositoryStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RepositoryStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RepositoryStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RepositoryUnderstandingStage string

const (
	RepositoryUnderstandingStageBuildingTree   RepositoryUnderstandingStage = "BUILDING_TREE"
	RepositoryUnderstandingStageFirstPassReady RepositoryUnderstandingStage = "FIRST_PASS_READY"
	RepositoryUnderstandingStageNeedsRefresh   RepositoryUnderstandingStage = "NEEDS_REFRESH"
	RepositoryUnderstandingStageDeepening      RepositoryUnderstandingStage = "DEEPENING"
	RepositoryUnderstandingStageReady          RepositoryUnderstandingStage = "READY"
	RepositoryUnderstandingStageFailed         RepositoryUnderstandingStage = "FAILED"
)

var AllRepositoryUnderstandingStage = []RepositoryUnderstandingStage{
	RepositoryUnderstandingStageBuildingTree,
	RepositoryUnderstandingStageFirstPassReady,
	RepositoryUnderstandingStageNeedsRefresh,
	RepositoryUnderstandingStageDeepening,
	RepositoryUnderstandingStageReady,
	RepositoryUnderstandingStageFailed,
}

func (e RepositoryUnderstandingStage) IsValid() bool {
	switch e {
	case RepositoryUnderstandingStageBuildingTree, RepositoryUnderstandingStageFirstPassReady, RepositoryUnderstandingStageNeedsRefresh, RepositoryUnderstandingStageDeepening, RepositoryUnderstandingStageReady, RepositoryUnderstandingStageFailed:
		return true
	}
	return false
}

func (e RepositoryUnderstandingStage) String() string {
	return string(e)
}

func (e *RepositoryUnderstandingStage) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RepositoryUnderstandingStage(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RepositoryUnderstandingStage", str)
	}
	return nil
}

func (e RepositoryUnderstandingStage) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RepositoryUnderstandingStage) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RepositoryUnderstandingStage) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RepositoryUnderstandingTreeStatus string

const (
	RepositoryUnderstandingTreeStatusMissing  RepositoryUnderstandingTreeStatus = "MISSING"
	RepositoryUnderstandingTreeStatusPartial  RepositoryUnderstandingTreeStatus = "PARTIAL"
	RepositoryUnderstandingTreeStatusComplete RepositoryUnderstandingTreeStatus = "COMPLETE"
)

var AllRepositoryUnderstandingTreeStatus = []RepositoryUnderstandingTreeStatus{
	RepositoryUnderstandingTreeStatusMissing,
	RepositoryUnderstandingTreeStatusPartial,
	RepositoryUnderstandingTreeStatusComplete,
}

func (e RepositoryUnderstandingTreeStatus) IsValid() bool {
	switch e {
	case RepositoryUnderstandingTreeStatusMissing, RepositoryUnderstandingTreeStatusPartial, RepositoryUnderstandingTreeStatusComplete:
		return true
	}
	return false
}

func (e RepositoryUnderstandingTreeStatus) String() string {
	return string(e)
}

func (e *RepositoryUnderstandingTreeStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RepositoryUnderstandingTreeStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RepositoryUnderstandingTreeStatus", str)
	}
	return nil
}

func (e RepositoryUnderstandingTreeStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RepositoryUnderstandingTreeStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RepositoryUnderstandingTreeStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RequirementFormat string

const (
	RequirementFormatMarkdown RequirementFormat = "MARKDOWN"
	RequirementFormatCSV      RequirementFormat = "CSV"
)

var AllRequirementFormat = []RequirementFormat{
	RequirementFormatMarkdown,
	RequirementFormatCSV,
}

func (e RequirementFormat) IsValid() bool {
	switch e {
	case RequirementFormatMarkdown, RequirementFormatCSV:
		return true
	}
	return false
}

func (e RequirementFormat) String() string {
	return string(e)
}

func (e *RequirementFormat) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RequirementFormat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RequirementFormat", str)
	}
	return nil
}

func (e RequirementFormat) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RequirementFormat) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RequirementFormat) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RestoreConflictResolution string

const (
	RestoreConflictResolutionCancel RestoreConflictResolution = "CANCEL"
	RestoreConflictResolutionRename RestoreConflictResolution = "RENAME"
)

var AllRestoreConflictResolution = []RestoreConflictResolution{
	RestoreConflictResolutionCancel,
	RestoreConflictResolutionRename,
}

func (e RestoreConflictResolution) IsValid() bool {
	switch e {
	case RestoreConflictResolutionCancel, RestoreConflictResolutionRename:
		return true
	}
	return false
}

func (e RestoreConflictResolution) String() string {
	return string(e)
}

func (e *RestoreConflictResolution) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RestoreConflictResolution(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RestoreConflictResolution", str)
	}
	return nil
}

func (e RestoreConflictResolution) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RestoreConflictResolution) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RestoreConflictResolution) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SymbolChangeType string

const (
	SymbolChangeTypeAdded    SymbolChangeType = "ADDED"
	SymbolChangeTypeModified SymbolChangeType = "MODIFIED"
	SymbolChangeTypeRemoved  SymbolChangeType = "REMOVED"
)

var AllSymbolChangeType = []SymbolChangeType{
	SymbolChangeTypeAdded,
	SymbolChangeTypeModified,
	SymbolChangeTypeRemoved,
}

func (e SymbolChangeType) IsValid() bool {
	switch e {
	case SymbolChangeTypeAdded, SymbolChangeTypeModified, SymbolChangeTypeRemoved:
		return true
	}
	return false
}

func (e SymbolChangeType) String() string {
	return string(e)
}

func (e *SymbolChangeType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SymbolChangeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SymbolChangeType", str)
	}
	return nil
}

func (e SymbolChangeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SymbolChangeType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SymbolChangeType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SymbolKind string

const (
	SymbolKindFunction  SymbolKind = "FUNCTION"
	SymbolKindMethod    SymbolKind = "METHOD"
	SymbolKindClass     SymbolKind = "CLASS"
	SymbolKindStruct    SymbolKind = "STRUCT"
	SymbolKindInterface SymbolKind = "INTERFACE"
	SymbolKindEnum      SymbolKind = "ENUM"
	SymbolKindConstant  SymbolKind = "CONSTANT"
	SymbolKindVariable  SymbolKind = "VARIABLE"
	SymbolKindModule    SymbolKind = "MODULE"
	SymbolKindPackage   SymbolKind = "PACKAGE"
	SymbolKindType      SymbolKind = "TYPE"
	SymbolKindTest      SymbolKind = "TEST"
)

var AllSymbolKind = []SymbolKind{
	SymbolKindFunction,
	SymbolKindMethod,
	SymbolKindClass,
	SymbolKindStruct,
	SymbolKindInterface,
	SymbolKindEnum,
	SymbolKindConstant,
	SymbolKindVariable,
	SymbolKindModule,
	SymbolKindPackage,
	SymbolKindType,
	SymbolKindTest,
}

func (e SymbolKind) IsValid() bool {
	switch e {
	case SymbolKindFunction, SymbolKindMethod, SymbolKindClass, SymbolKindStruct, SymbolKindInterface, SymbolKindEnum, SymbolKindConstant, SymbolKindVariable, SymbolKindModule, SymbolKindPackage, SymbolKindType, SymbolKindTest:
		return true
	}
	return false
}

func (e SymbolKind) String() string {
	return string(e)
}

func (e *SymbolKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SymbolKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SymbolKind", str)
	}
	return nil
}

func (e SymbolKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SymbolKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SymbolKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TrashableType string

const (
	TrashableTypeRequirement       TrashableType = "REQUIREMENT"
	TrashableTypeRequirementLink   TrashableType = "REQUIREMENT_LINK"
	TrashableTypeKnowledgeArtifact TrashableType = "KNOWLEDGE_ARTIFACT"
)

var AllTrashableType = []TrashableType{
	TrashableTypeRequirement,
	TrashableTypeRequirementLink,
	TrashableTypeKnowledgeArtifact,
}

func (e TrashableType) IsValid() bool {
	switch e {
	case TrashableTypeRequirement, TrashableTypeRequirementLink, TrashableTypeKnowledgeArtifact:
		return true
	}
	return false
}

func (e TrashableType) String() string {
	return string(e)
}

func (e *TrashableType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TrashableType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TrashableType", str)
	}
	return nil
}

func (e TrashableType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TrashableType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TrashableType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UpstreamStatus string

const (
	// Indexed commit matches upstream HEAD.
	UpstreamStatusUpToDate UpstreamStatus = "UP_TO_DATE"
	// Upstream HEAD differs from indexed commit — reindex recommended.
	UpstreamStatusBehind UpstreamStatus = "BEHIND"
	// Check has never completed; UI should treat as 'unknown'.
	UpstreamStatusUnknown UpstreamStatus = "UNKNOWN"
	// ls-remote failed (network, auth, unreachable host). Soft error.
	UpstreamStatusUnreachable UpstreamStatus = "UNREACHABLE"
	// Repo has no remote URL; nothing to compare against.
	UpstreamStatusUnsupported UpstreamStatus = "UNSUPPORTED"
)

var AllUpstreamStatus = []UpstreamStatus{
	UpstreamStatusUpToDate,
	UpstreamStatusBehind,
	UpstreamStatusUnknown,
	UpstreamStatusUnreachable,
	UpstreamStatusUnsupported,
}

func (e UpstreamStatus) IsValid() bool {
	switch e {
	case UpstreamStatusUpToDate, UpstreamStatusBehind, UpstreamStatusUnknown, UpstreamStatusUnreachable, UpstreamStatusUnsupported:
		return true
	}
	return false
}

func (e UpstreamStatus) String() string {
	return string(e)
}

func (e *UpstreamStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UpstreamStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UpstreamStatus", str)
	}
	return nil
}

func (e UpstreamStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UpstreamStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UpstreamStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
