// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type APIContract struct {
	ID            string    `json:"id"`
	RepoID        string    `json:"repoId"`
	FilePath      string    `json:"filePath"`
	ContractType  string    `json:"contractType"`
	EndpointCount int       `json:"endpointCount"`
	Version       *string   `json:"version,omitempty"`
	DetectedAt    time.Time `json:"detectedAt"`
}

type AddRepositoryInput struct {
	Name  string  `json:"name"`
	Path  string  `json:"path"`
	Token *string `json:"token,omitempty"`
}

type AnalysisResult struct {
	Summary      string   `json:"summary"`
	Purpose      string   `json:"purpose"`
	Concerns     []string `json:"concerns"`
	Suggestions  []string `json:"suggestions"`
	Model        *string  `json:"model,omitempty"`
	InputTokens  *int     `json:"inputTokens,omitempty"`
	OutputTokens *int     `json:"outputTokens,omitempty"`
}

type ArtifactDependency struct {
	ID               string    `json:"id"`
	DependencyType   string    `json:"dependencyType"`
	TargetID         string    `json:"targetId"`
	TargetRevisionFp *string   `json:"targetRevisionFp,omitempty"`
	Metadata         *string   `json:"metadata,omitempty"`
	CreatedAt        time.Time `json:"createdAt"`
}

type AutoLinkResult struct {
	LinksCreated          int                `json:"linksCreated"`
	RequirementsProcessed int                `json:"requirementsProcessed"`
	Links                 []*RequirementLink `json:"links"`
}

type BuildRepositoryUnderstandingInput struct {
	RepositoryID string              `json:"repositoryId"`
	ScopeType    *KnowledgeScopeType `json:"scopeType,omitempty"`
	ScopePath    *string             `json:"scopePath,omitempty"`
}

type CodeSymbol struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	QualifiedName string             `json:"qualifiedName"`
	Kind          SymbolKind         `json:"kind"`
	Language      Language           `json:"language"`
	FilePath      string             `json:"filePath"`
	StartLine     int                `json:"startLine"`
	EndLine       int                `json:"endLine"`
	Signature     *string            `json:"signature,omitempty"`
	DocComment    *string            `json:"docComment,omitempty"`
	Callers       []*CodeSymbol      `json:"callers"`
	Callees       []*CodeSymbol      `json:"callees"`
	Requirements  []*RequirementLink `json:"requirements"`
}

type CodeTourStop struct {
	Title       string               `json:"title"`
	Description string               `json:"description"`
	FilePath    string               `json:"filePath"`
	LineStart   int                  `json:"lineStart"`
	LineEnd     int                  `json:"lineEnd"`
	OrderIndex  int                  `json:"orderIndex"`
	Evidence    []*KnowledgeEvidence `json:"evidence"`
}

type ComprehensionSettings struct {
	ID                             *string                  `json:"id,omitempty"`
	ScopeType                      string                   `json:"scopeType"`
	ScopeKey                       string                   `json:"scopeKey"`
	StrategyPreferenceChain        []string                 `json:"strategyPreferenceChain,omitempty"`
	KnowledgeGenerationModeDefault *KnowledgeGenerationMode `json:"knowledgeGenerationModeDefault,omitempty"`
	ModelID                        *string                  `json:"modelId,omitempty"`
	MaxConcurrency                 *int                     `json:"maxConcurrency,omitempty"`
	MaxPromptTokens                *int                     `json:"maxPromptTokens,omitempty"`
	LeafBudgetTokens               *int                     `json:"leafBudgetTokens,omitempty"`
	RefinePassEnabled              *bool                    `json:"refinePassEnabled,omitempty"`
	LongContextMaxTokens           *int                     `json:"longContextMaxTokens,omitempty"`
	GraphragEntityTypes            []string                 `json:"graphragEntityTypes,omitempty"`
	CacheEnabled                   *bool                    `json:"cacheEnabled,omitempty"`
	AllowUnsafeCombinations        *bool                    `json:"allowUnsafeCombinations,omitempty"`
	UpdatedAt                      *time.Time               `json:"updatedAt,omitempty"`
	UpdatedBy                      *string                  `json:"updatedBy,omitempty"`
}

type CreateManualLinkInput struct {
	RepositoryID  string  `json:"repositoryId"`
	RequirementID string  `json:"requirementId"`
	SymbolID      string  `json:"symbolId"`
	Rationale     *string `json:"rationale,omitempty"`
}

type CrossRepoRef struct {
	ID             string           `json:"id"`
	SourceSymbolID string           `json:"sourceSymbolId"`
	TargetSymbolID string           `json:"targetSymbolId"`
	SourceRepoID   string           `json:"sourceRepoId"`
	TargetRepoID   string           `json:"targetRepoId"`
	RefType        CrossRepoRefType `json:"refType"`
	Confidence     float64          `json:"confidence"`
	ContractFile   *string          `json:"contractFile,omitempty"`
	ConsumerFile   *string          `json:"consumerFile,omitempty"`
	Evidence       *string          `json:"evidence,omitempty"`
	CreatedAt      time.Time        `json:"createdAt"`
}

type DiagramEdge struct {
	TargetPath string `json:"targetPath"`
	CallCount  int    `json:"callCount"`
}

type DiagramModule struct {
	Path                 string         `json:"path"`
	SymbolCount          int            `json:"symbolCount"`
	FileCount            int            `json:"fileCount"`
	RequirementLinkCount int            `json:"requirementLinkCount"`
	InboundEdgeCount     int            `json:"inboundEdgeCount"`
	OutboundEdges        []*DiagramEdge `json:"outboundEdges"`
}

type DiagramOutput struct {
	MermaidSource string           `json:"mermaidSource"`
	Modules       []*DiagramModule `json:"modules"`
	Level         DiagramLevel     `json:"level"`
	TotalModules  int              `json:"totalModules"`
	ShownModules  int              `json:"shownModules"`
	Truncated     bool             `json:"truncated"`
}

type DiscoveredRequirement struct {
	ID              string    `json:"id"`
	RepoID          string    `json:"repoId"`
	Source          string    `json:"source"`
	SourceFile      string    `json:"sourceFile"`
	SourceLine      int       `json:"sourceLine"`
	SourceFiles     []string  `json:"sourceFiles"`
	Text            string    `json:"text"`
	RawText         string    `json:"rawText"`
	GroupKey        string    `json:"groupKey"`
	Language        string    `json:"language"`
	Keywords        []string  `json:"keywords"`
	Confidence      string    `json:"confidence"`
	Status          string    `json:"status"`
	LlmRefined      bool      `json:"llmRefined"`
	PromotedTo      *string   `json:"promotedTo,omitempty"`
	DismissedBy     *string   `json:"dismissedBy,omitempty"`
	DismissedReason *string   `json:"dismissedReason,omitempty"`
	CreatedAt       time.Time `json:"createdAt"`
}

type DiscoveredRequirementConnection struct {
	Nodes      []*DiscoveredRequirement `json:"nodes"`
	TotalCount int                      `json:"totalCount"`
}

type DiscussCodeInput struct {
	RepositoryID        string    `json:"repositoryId"`
	Question            string    `json:"question"`
	FilePath            *string   `json:"filePath,omitempty"`
	Code                *string   `json:"code,omitempty"`
	Language            *Language `json:"language,omitempty"`
	ArtifactID          *string   `json:"artifactId,omitempty"`
	SymbolID            *string   `json:"symbolId,omitempty"`
	RequirementID       *string   `json:"requirementId,omitempty"`
	ConversationHistory []string  `json:"conversationHistory,omitempty"`
}

type DiscussionResult struct {
	Answer              string   `json:"answer"`
	References          []string `json:"references"`
	RelatedRequirements []string `json:"relatedRequirements"`
	Model               *string  `json:"model,omitempty"`
	InputTokens         *int     `json:"inputTokens,omitempty"`
	OutputTokens        *int     `json:"outputTokens,omitempty"`
}

type EffectiveComprehensionSettings struct {
	ScopeType                      string                  `json:"scopeType"`
	ScopeKey                       string                  `json:"scopeKey"`
	StrategyPreferenceChain        []string                `json:"strategyPreferenceChain"`
	KnowledgeGenerationModeDefault KnowledgeGenerationMode `json:"knowledgeGenerationModeDefault"`
	ModelID                        string                  `json:"modelId"`
	MaxConcurrency                 int                     `json:"maxConcurrency"`
	MaxPromptTokens                int                     `json:"maxPromptTokens"`
	LeafBudgetTokens               int                     `json:"leafBudgetTokens"`
	RefinePassEnabled              bool                    `json:"refinePassEnabled"`
	LongContextMaxTokens           int                     `json:"longContextMaxTokens"`
	GraphragEntityTypes            []string                `json:"graphragEntityTypes"`
	CacheEnabled                   bool                    `json:"cacheEnabled"`
	AllowUnsafeCombinations        bool                    `json:"allowUnsafeCombinations"`
	InheritedFrom                  []*FieldOrigin          `json:"inheritedFrom,omitempty"`
}

type ExecutionEntryPoint struct {
	Kind      ExecutionEntryKind `json:"kind"`
	Label     string             `json:"label"`
	Value     string             `json:"value"`
	FilePath  *string            `json:"filePath,omitempty"`
	LineStart *int               `json:"lineStart,omitempty"`
	LineEnd   *int               `json:"lineEnd,omitempty"`
	SymbolID  *string            `json:"symbolId,omitempty"`
	Summary   *string            `json:"summary,omitempty"`
}

type ExecutionPathInput struct {
	RepositoryID string             `json:"repositoryId"`
	EntryKind    ExecutionEntryKind `json:"entryKind"`
	EntryValue   string             `json:"entryValue"`
	MaxDepth     *int               `json:"maxDepth,omitempty"`
}

type ExecutionPathResult struct {
	EntryKind         ExecutionEntryKind   `json:"entryKind"`
	EntryLabel        string               `json:"entryLabel"`
	Message           *string              `json:"message,omitempty"`
	TrustQualified    bool                 `json:"trustQualified"`
	ObservedStepCount int                  `json:"observedStepCount"`
	InferredStepCount int                  `json:"inferredStepCount"`
	Steps             []*ExecutionPathStep `json:"steps"`
}

type ExecutionPathStep struct {
	OrderIndex  int     `json:"orderIndex"`
	Kind        string  `json:"kind"`
	Label       string  `json:"label"`
	Explanation string  `json:"explanation"`
	Confidence  string  `json:"confidence"`
	Observed    bool    `json:"observed"`
	Reason      *string `json:"reason,omitempty"`
	FilePath    *string `json:"filePath,omitempty"`
	LineStart   *int    `json:"lineStart,omitempty"`
	LineEnd     *int    `json:"lineEnd,omitempty"`
	SymbolID    *string `json:"symbolId,omitempty"`
	SymbolName  *string `json:"symbolName,omitempty"`
}

type ExplainSystemInput struct {
	RepositoryID   string                   `json:"repositoryId"`
	Audience       *KnowledgeAudience       `json:"audience,omitempty"`
	Depth          *KnowledgeDepth          `json:"depth,omitempty"`
	GenerationMode *KnowledgeGenerationMode `json:"generationMode,omitempty"`
	Question       *string                  `json:"question,omitempty"`
	ScopeType      *KnowledgeScopeType      `json:"scopeType,omitempty"`
	ScopePath      *string                  `json:"scopePath,omitempty"`
}

type ExplainSystemResult struct {
	Explanation  string  `json:"explanation"`
	Model        *string `json:"model,omitempty"`
	InputTokens  *int    `json:"inputTokens,omitempty"`
	OutputTokens *int    `json:"outputTokens,omitempty"`
}

type Features struct {
	MultiTenant              bool `json:"multiTenant"`
	Sso                      bool `json:"sso"`
	LinearConnector          bool `json:"linearConnector"`
	JiraConnector            bool `json:"jiraConnector"`
	GithubApp                bool `json:"githubApp"`
	GitlabApp                bool `json:"gitlabApp"`
	AuditLog                 bool `json:"auditLog"`
	Webhooks                 bool `json:"webhooks"`
	CustomTemplates          bool `json:"customTemplates"`
	Billing                  bool `json:"billing"`
	CliffNotes               bool `json:"cliffNotes"`
	LearningPaths            bool `json:"learningPaths"`
	CodeTours                bool `json:"codeTours"`
	SystemExplain            bool `json:"systemExplain"`
	SymbolScopedAnalysis     bool `json:"symbolScopedAnalysis"`
	MultiAudienceKnowledge   bool `json:"multiAudienceKnowledge"`
	CustomKnowledgeTemplates bool `json:"customKnowledgeTemplates"`
	AdvancedLearningPaths    bool `json:"advancedLearningPaths"`
	SlideGeneration          bool `json:"slideGeneration"`
	PodcastGeneration        bool `json:"podcastGeneration"`
	KnowledgeScheduling      bool `json:"knowledgeScheduling"`
	KnowledgeExport          bool `json:"knowledgeExport"`
}

type FieldOrigin struct {
	Field     string `json:"field"`
	ScopeType string `json:"scopeType"`
	ScopeKey  string `json:"scopeKey"`
}

type File struct {
	ID        string        `json:"id"`
	Path      string        `json:"path"`
	Language  Language      `json:"language"`
	LineCount int           `json:"lineCount"`
	AiScore   float64       `json:"aiScore"`
	AiSignals []string      `json:"aiSignals"`
	Symbols   []*CodeSymbol `json:"symbols"`
}

type FileConnection struct {
	Nodes      []*File `json:"nodes"`
	TotalCount int     `json:"totalCount"`
}

type FileDiff struct {
	Path      string     `json:"path"`
	OldPath   *string    `json:"oldPath,omitempty"`
	Status    DiffStatus `json:"status"`
	Additions int        `json:"additions"`
	Deletions int        `json:"deletions"`
}

type GenerateArchitectureDiagramInput struct {
	RepositoryID string             `json:"repositoryId"`
	Audience     *KnowledgeAudience `json:"audience,omitempty"`
	Depth        *KnowledgeDepth    `json:"depth,omitempty"`
}

type GenerateCliffNotesInput struct {
	RepositoryID   string                   `json:"repositoryId"`
	Audience       *KnowledgeAudience       `json:"audience,omitempty"`
	Depth          *KnowledgeDepth          `json:"depth,omitempty"`
	GenerationMode *KnowledgeGenerationMode `json:"generationMode,omitempty"`
	ScopeType      *KnowledgeScopeType      `json:"scopeType,omitempty"`
	ScopePath      *string                  `json:"scopePath,omitempty"`
}

type GenerateCodeTourInput struct {
	RepositoryID   string                   `json:"repositoryId"`
	Audience       *KnowledgeAudience       `json:"audience,omitempty"`
	Depth          *KnowledgeDepth          `json:"depth,omitempty"`
	GenerationMode *KnowledgeGenerationMode `json:"generationMode,omitempty"`
	Theme          *string                  `json:"theme,omitempty"`
}

type GenerateLearningPathInput struct {
	RepositoryID   string                   `json:"repositoryId"`
	Audience       *KnowledgeAudience       `json:"audience,omitempty"`
	Depth          *KnowledgeDepth          `json:"depth,omitempty"`
	GenerationMode *KnowledgeGenerationMode `json:"generationMode,omitempty"`
	FocusArea      *string                  `json:"focusArea,omitempty"`
}

type GenerateWorkflowStoryInput struct {
	RepositoryID      string                   `json:"repositoryId"`
	Audience          *KnowledgeAudience       `json:"audience,omitempty"`
	Depth             *KnowledgeDepth          `json:"depth,omitempty"`
	GenerationMode    *KnowledgeGenerationMode `json:"generationMode,omitempty"`
	ScopeType         *KnowledgeScopeType      `json:"scopeType,omitempty"`
	ScopePath         *string                  `json:"scopePath,omitempty"`
	AnchorLabel       *string                  `json:"anchorLabel,omitempty"`
	ExecutionPathJSON *string                  `json:"executionPathJson,omitempty"`
}

type HealthStatus struct {
	Status   string           `json:"status"`
	Services []*ServiceHealth `json:"services"`
}

type IDECapabilities struct {
	RepoKnowledge   bool `json:"repoKnowledge"`
	ScopedKnowledge bool `json:"scopedKnowledge"`
	ScopedExplain   bool `json:"scopedExplain"`
	ImpactReports   bool `json:"impactReports"`
	DiscussCode     bool `json:"discussCode"`
	ReviewCode      bool `json:"reviewCode"`
	Vscode          bool `json:"vscode"`
	Jetbrains       bool `json:"jetbrains"`
}

type ImpactAffectedLink struct {
	LinkID        string  `json:"linkId"`
	RequirementID string  `json:"requirementId"`
	SymbolID      string  `json:"symbolId"`
	Impact        string  `json:"impact"`
	Confidence    float64 `json:"confidence"`
}

type ImpactAffectedRequirement struct {
	RequirementID string `json:"requirementId"`
	ExternalID    string `json:"externalId"`
	Title         string `json:"title"`
	AffectedLinks int    `json:"affectedLinks"`
	TotalLinks    int    `json:"totalLinks"`
}

type ImpactReport struct {
	ID                   string                       `json:"id"`
	RepositoryID         string                       `json:"repositoryId"`
	OldCommitSha         *string                      `json:"oldCommitSha,omitempty"`
	NewCommitSha         *string                      `json:"newCommitSha,omitempty"`
	FilesChanged         []*FileDiff                  `json:"filesChanged"`
	SymbolsAdded         []*SymbolChange              `json:"symbolsAdded"`
	SymbolsModified      []*SymbolChange              `json:"symbolsModified"`
	SymbolsRemoved       []*SymbolChange              `json:"symbolsRemoved"`
	AffectedLinks        []*ImpactAffectedLink        `json:"affectedLinks"`
	AffectedRequirements []*ImpactAffectedRequirement `json:"affectedRequirements"`
	StaleArtifacts       []string                     `json:"staleArtifacts"`
	ComputedAt           time.Time                    `json:"computedAt"`
}

type ImportRequirementsInput struct {
	RepositoryID string            `json:"repositoryId"`
	Content      string            `json:"content"`
	Format       RequirementFormat `json:"format"`
	SourcePath   *string           `json:"sourcePath,omitempty"`
}

type ImportResult struct {
	Imported int      `json:"imported"`
	Skipped  int      `json:"skipped"`
	Warnings []string `json:"warnings"`
}

type KnowledgeArtifact struct {
	ID                      string                     `json:"id"`
	RepositoryID            string                     `json:"repositoryId"`
	Type                    KnowledgeArtifactType      `json:"type"`
	Audience                KnowledgeAudience          `json:"audience"`
	Depth                   KnowledgeDepth             `json:"depth"`
	Scope                   *KnowledgeScope            `json:"scope"`
	Status                  KnowledgeArtifactStatus    `json:"status"`
	Progress                float64                    `json:"progress"`
	ProgressPhase           *string                    `json:"progressPhase,omitempty"`
	ProgressMessage         *string                    `json:"progressMessage,omitempty"`
	SourceRevision          *SourceRevision            `json:"sourceRevision"`
	Stale                   bool                       `json:"stale"`
	GeneratedAt             *time.Time                 `json:"generatedAt,omitempty"`
	CreatedAt               time.Time                  `json:"createdAt"`
	UpdatedAt               time.Time                  `json:"updatedAt"`
	ErrorCode               *string                    `json:"errorCode,omitempty"`
	ErrorMessage            *string                    `json:"errorMessage,omitempty"`
	GenerationMode          KnowledgeGenerationMode    `json:"generationMode"`
	RendererVersion         *string                    `json:"rendererVersion,omitempty"`
	UnderstandingID         *string                    `json:"understandingId,omitempty"`
	UnderstandingRevisionFp *string                    `json:"understandingRevisionFp,omitempty"`
	RefreshAvailable        bool                       `json:"refreshAvailable"`
	Dependencies            []*ArtifactDependency      `json:"dependencies"`
	RefinementUnits         []*KnowledgeRefinementUnit `json:"refinementUnits"`
	Sections                []*KnowledgeSection        `json:"sections"`
}

type KnowledgeEvidence struct {
	ID         string             `json:"id"`
	SectionID  string             `json:"sectionId"`
	SourceType EvidenceSourceType `json:"sourceType"`
	SourceID   string             `json:"sourceId"`
	FilePath   *string            `json:"filePath,omitempty"`
	LineStart  *int               `json:"lineStart,omitempty"`
	LineEnd    *int               `json:"lineEnd,omitempty"`
	Rationale  *string            `json:"rationale,omitempty"`
	Metadata   *string            `json:"metadata,omitempty"`
}

type KnowledgeRefinementUnit struct {
	ID                 string    `json:"id"`
	ArtifactID         string    `json:"artifactId"`
	SectionKey         string    `json:"sectionKey"`
	SectionTitle       string    `json:"sectionTitle"`
	RefinementType     string    `json:"refinementType"`
	Status             string    `json:"status"`
	AttemptCount       int       `json:"attemptCount"`
	UnderstandingID    *string   `json:"understandingId,omitempty"`
	EvidenceRevisionFp *string   `json:"evidenceRevisionFp,omitempty"`
	RendererVersion    *string   `json:"rendererVersion,omitempty"`
	LastError          *string   `json:"lastError,omitempty"`
	Metadata           *string   `json:"metadata,omitempty"`
	CreatedAt          time.Time `json:"createdAt"`
	UpdatedAt          time.Time `json:"updatedAt"`
}

type KnowledgeScope struct {
	ScopeType  KnowledgeScopeType `json:"scopeType"`
	ScopePath  string             `json:"scopePath"`
	ModulePath *string            `json:"modulePath,omitempty"`
	FilePath   *string            `json:"filePath,omitempty"`
	SymbolName *string            `json:"symbolName,omitempty"`
}

type KnowledgeSection struct {
	ID               string               `json:"id"`
	ArtifactID       string               `json:"artifactId"`
	SectionKey       *string              `json:"sectionKey,omitempty"`
	Title            string               `json:"title"`
	Content          string               `json:"content"`
	Summary          *string              `json:"summary,omitempty"`
	Metadata         *string              `json:"metadata,omitempty"`
	Confidence       KnowledgeConfidence  `json:"confidence"`
	Inferred         bool                 `json:"inferred"`
	OrderIndex       int                  `json:"orderIndex"`
	RefinementStatus *string              `json:"refinementStatus,omitempty"`
	Evidence         []*KnowledgeEvidence `json:"evidence"`
}

type LLMUsageEntry struct {
	ID           string    `json:"id"`
	Provider     string    `json:"provider"`
	Model        string    `json:"model"`
	Operation    string    `json:"operation"`
	InputTokens  int       `json:"inputTokens"`
	OutputTokens int       `json:"outputTokens"`
	CreatedAt    time.Time `json:"createdAt"`
}

type LearningPathStep struct {
	Title         string               `json:"title"`
	Description   string               `json:"description"`
	TargetFiles   []string             `json:"targetFiles"`
	TargetSymbols []string             `json:"targetSymbols"`
	Difficulty    string               `json:"difficulty"`
	OrderIndex    int                  `json:"orderIndex"`
	Evidence      []*KnowledgeEvidence `json:"evidence"`
}

type ModelCapabilityProfile struct {
	ID                     *string    `json:"id,omitempty"`
	ModelID                string     `json:"modelId"`
	Provider               string     `json:"provider"`
	DeclaredContextTokens  int        `json:"declaredContextTokens"`
	EffectiveContextTokens int        `json:"effectiveContextTokens"`
	InstructionFollowing   string     `json:"instructionFollowing"`
	JSONMode               string     `json:"jsonMode"`
	ToolUse                string     `json:"toolUse"`
	ExtractionGrade        string     `json:"extractionGrade"`
	CreativeGrade          string     `json:"creativeGrade"`
	EmbeddingModel         bool       `json:"embeddingModel"`
	CostPer1kInput         *float64   `json:"costPer1kInput,omitempty"`
	CostPer1kOutput        *float64   `json:"costPer1kOutput,omitempty"`
	LastProbedAt           *time.Time `json:"lastProbedAt,omitempty"`
	Source                 string     `json:"source"`
	Notes                  *string    `json:"notes,omitempty"`
	UpdatedAt              *time.Time `json:"updatedAt,omitempty"`
}

type Module struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Path      string `json:"path"`
	FileCount int    `json:"fileCount"`
}

type Mutation struct {
}

type PlatformStats struct {
	Repositories      int `json:"repositories"`
	Files             int `json:"files"`
	Symbols           int `json:"symbols"`
	Requirements      int `json:"requirements"`
	Links             int `json:"links"`
	TotalInputTokens  int `json:"totalInputTokens"`
	TotalOutputTokens int `json:"totalOutputTokens"`
}

type PromoteResult struct {
	Requirement           *Requirement           `json:"requirement"`
	DiscoveredRequirement *DiscoveredRequirement `json:"discoveredRequirement"`
}

type Query struct {
}

type RepoLink struct {
	ID           string    `json:"id"`
	SourceRepoID string    `json:"sourceRepoId"`
	TargetRepoID string    `json:"targetRepoId"`
	LinkType     string    `json:"linkType"`
	CreatedAt    time.Time `json:"createdAt"`
}

type Repository struct {
	ID                      string                   `json:"id"`
	Name                    string                   `json:"name"`
	Path                    string                   `json:"path"`
	RemoteURL               *string                  `json:"remoteUrl,omitempty"`
	CommitSha               *string                  `json:"commitSha,omitempty"`
	Branch                  *string                  `json:"branch,omitempty"`
	GenerationModeDefault   *KnowledgeGenerationMode `json:"generationModeDefault,omitempty"`
	HasAuth                 bool                     `json:"hasAuth"`
	Status                  RepositoryStatus         `json:"status"`
	FileCount               int                      `json:"fileCount"`
	FunctionCount           int                      `json:"functionCount"`
	ClassCount              int                      `json:"classCount"`
	RequirementCount        int                      `json:"requirementCount"`
	LastIndexedAt           *time.Time               `json:"lastIndexedAt,omitempty"`
	CreatedAt               time.Time                `json:"createdAt"`
	Files                   *FileConnection          `json:"files"`
	Modules                 []*Module                `json:"modules"`
	UnderstandingScore      *UnderstandingScore      `json:"understandingScore,omitempty"`
	RepositoryUnderstanding *RepositoryUnderstanding `json:"repositoryUnderstanding,omitempty"`
}

type RepositoryUnderstanding struct {
	ID                string                            `json:"id"`
	RepositoryID      string                            `json:"repositoryId"`
	Scope             *KnowledgeScope                   `json:"scope"`
	CorpusID          *string                           `json:"corpusId,omitempty"`
	RevisionFp        string                            `json:"revisionFp"`
	Strategy          *string                           `json:"strategy,omitempty"`
	Stage             RepositoryUnderstandingStage      `json:"stage"`
	TreeStatus        RepositoryUnderstandingTreeStatus `json:"treeStatus"`
	CachedNodes       int                               `json:"cachedNodes"`
	TotalNodes        int                               `json:"totalNodes"`
	ModelUsed         *string                           `json:"modelUsed,omitempty"`
	FirstPassSections []*UnderstandingSection           `json:"firstPassSections"`
	RefreshAvailable  bool                              `json:"refreshAvailable"`
	CreatedAt         time.Time                         `json:"createdAt"`
	UpdatedAt         time.Time                         `json:"updatedAt"`
	ErrorCode         *string                           `json:"errorCode,omitempty"`
	ErrorMessage      *string                           `json:"errorMessage,omitempty"`
}

type Requirement struct {
	ID          string             `json:"id"`
	ExternalID  *string            `json:"externalId,omitempty"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Source      string             `json:"source"`
	Priority    *string            `json:"priority,omitempty"`
	Tags        []string           `json:"tags"`
	Links       []*RequirementLink `json:"links"`
	CreatedAt   time.Time          `json:"createdAt"`
	UpdatedAt   *time.Time         `json:"updatedAt,omitempty"`
}

type RequirementConnection struct {
	Nodes      []*Requirement `json:"nodes"`
	TotalCount int            `json:"totalCount"`
}

type RequirementLink struct {
	ID            string       `json:"id"`
	RequirementID string       `json:"requirementId"`
	SymbolID      string       `json:"symbolId"`
	Confidence    Confidence   `json:"confidence"`
	Rationale     *string      `json:"rationale,omitempty"`
	Verified      bool         `json:"verified"`
	VerifiedBy    *string      `json:"verifiedBy,omitempty"`
	Symbol        *CodeSymbol  `json:"symbol,omitempty"`
	Requirement   *Requirement `json:"requirement,omitempty"`
	CreatedAt     time.Time    `json:"createdAt"`
}

type ResolvedSymbol struct {
	SymbolID      string  `json:"symbolId"`
	Name          string  `json:"name"`
	QualifiedName string  `json:"qualifiedName"`
	Kind          string  `json:"kind"`
	FilePath      string  `json:"filePath"`
	Similarity    float64 `json:"similarity"`
	IsAnchor      bool    `json:"isAnchor"`
}

type ReviewCodeInput struct {
	RepositoryID string    `json:"repositoryId"`
	FilePath     string    `json:"filePath"`
	Template     string    `json:"template"`
	Code         *string   `json:"code,omitempty"`
	Language     *Language `json:"language,omitempty"`
}

type ReviewFinding struct {
	Category   string  `json:"category"`
	Severity   string  `json:"severity"`
	Message    string  `json:"message"`
	FilePath   *string `json:"filePath,omitempty"`
	StartLine  *int    `json:"startLine,omitempty"`
	EndLine    *int    `json:"endLine,omitempty"`
	Suggestion *string `json:"suggestion,omitempty"`
}

type ReviewResult struct {
	Template     string           `json:"template"`
	Findings     []*ReviewFinding `json:"findings"`
	Score        float64          `json:"score"`
	Model        *string          `json:"model,omitempty"`
	InputTokens  *int             `json:"inputTokens,omitempty"`
	OutputTokens *int             `json:"outputTokens,omitempty"`
}

type ScopeChild struct {
	ScopeType   KnowledgeScopeType `json:"scopeType"`
	Label       string             `json:"label"`
	ScopePath   string             `json:"scopePath"`
	HasArtifact bool               `json:"hasArtifact"`
	Summary     *string            `json:"summary,omitempty"`
}

type ScopeOrigin struct {
	Type string `json:"type"`
	Key  string `json:"key"`
}

type SearchResult struct {
	Type           string  `json:"type"`
	ID             string  `json:"id"`
	Title          string  `json:"title"`
	Description    *string `json:"description,omitempty"`
	FilePath       *string `json:"filePath,omitempty"`
	Line           *int    `json:"line,omitempty"`
	RepositoryID   string  `json:"repositoryId"`
	RepositoryName string  `json:"repositoryName"`
}

type ServiceHealth struct {
	Name   string `json:"name"`
	Status string `json:"status"`
}

type SimulateChangeInput struct {
	RepositoryID string  `json:"repositoryId"`
	Description  string  `json:"description"`
	AnchorFile   *string `json:"anchorFile,omitempty"`
	AnchorSymbol *string `json:"anchorSymbol,omitempty"`
}

type SimulatedImpactReport struct {
	ID              string            `json:"id"`
	Simulated       bool              `json:"simulated"`
	Description     string            `json:"description"`
	AnchorFile      *string           `json:"anchorFile,omitempty"`
	AnchorSymbol    *string           `json:"anchorSymbol,omitempty"`
	ResolvedSymbols []*ResolvedSymbol `json:"resolvedSymbols"`
	Report          *ImpactReport     `json:"report"`
	ComputedAt      time.Time         `json:"computedAt"`
}

type SourceFile struct {
	RepositoryID string   `json:"repositoryId"`
	FilePath     string   `json:"filePath"`
	Language     Language `json:"language"`
	LineCount    int      `json:"lineCount"`
	Content      string   `json:"content"`
	ContentHash  *string  `json:"contentHash,omitempty"`
}

type SourceFileResult struct {
	Ok        bool        `json:"ok"`
	ErrorCode *string     `json:"errorCode,omitempty"`
	Message   *string     `json:"message,omitempty"`
	File      *SourceFile `json:"file,omitempty"`
}

type SourceRevision struct {
	CommitSha          *string `json:"commitSha,omitempty"`
	Branch             *string `json:"branch,omitempty"`
	ContentFingerprint *string `json:"contentFingerprint,omitempty"`
	DocsFingerprint    *string `json:"docsFingerprint,omitempty"`
}

type SpecExtractionResult struct {
	Discovered      int      `json:"discovered"`
	TotalCandidates int      `json:"totalCandidates"`
	Warnings        []string `json:"warnings"`
	Model           *string  `json:"model,omitempty"`
	InputTokens     *int     `json:"inputTokens,omitempty"`
	OutputTokens    *int     `json:"outputTokens,omitempty"`
}

type SymbolChange struct {
	SymbolID     *string          `json:"symbolId,omitempty"`
	Name         string           `json:"name"`
	FilePath     string           `json:"filePath"`
	ChangeType   SymbolChangeType `json:"changeType"`
	OldSignature *string          `json:"oldSignature,omitempty"`
	NewSignature *string          `json:"newSignature,omitempty"`
}

type SymbolConnection struct {
	Nodes      []*CodeSymbol `json:"nodes"`
	TotalCount int           `json:"totalCount"`
}

type TraceabilityMatrix struct {
	Requirements []*Requirement     `json:"requirements"`
	Symbols      []*CodeSymbol      `json:"symbols"`
	Links        []*RequirementLink `json:"links"`
	Coverage     float64            `json:"coverage"`
}

type TriggerSpecExtractionInput struct {
	RepositoryID      string `json:"repositoryId"`
	SkipLlmRefinement *bool  `json:"skipLlmRefinement,omitempty"`
}

type UnderstandingScore struct {
	Overall               float64   `json:"overall"`
	TraceabilityCoverage  float64   `json:"traceabilityCoverage"`
	DocumentationCoverage float64   `json:"documentationCoverage"`
	ReviewCoverage        float64   `json:"reviewCoverage"`
	TestCoverage          float64   `json:"testCoverage"`
	KnowledgeFreshness    float64   `json:"knowledgeFreshness"`
	AiCodeRatio           float64   `json:"aiCodeRatio"`
	ComputedAt            time.Time `json:"computedAt"`
}

type UnderstandingSection struct {
	Title   string `json:"title"`
	Summary string `json:"summary"`
}

type UpdateComprehensionSettingsInput struct {
	ScopeType                      string                   `json:"scopeType"`
	ScopeKey                       *string                  `json:"scopeKey,omitempty"`
	StrategyPreferenceChain        []string                 `json:"strategyPreferenceChain,omitempty"`
	KnowledgeGenerationModeDefault *KnowledgeGenerationMode `json:"knowledgeGenerationModeDefault,omitempty"`
	ModelID                        *string                  `json:"modelId,omitempty"`
	MaxConcurrency                 *int                     `json:"maxConcurrency,omitempty"`
	MaxPromptTokens                *int                     `json:"maxPromptTokens,omitempty"`
	LeafBudgetTokens               *int                     `json:"leafBudgetTokens,omitempty"`
	RefinePassEnabled              *bool                    `json:"refinePassEnabled,omitempty"`
	LongContextMaxTokens           *int                     `json:"longContextMaxTokens,omitempty"`
	GraphragEntityTypes            []string                 `json:"graphragEntityTypes,omitempty"`
	CacheEnabled                   *bool                    `json:"cacheEnabled,omitempty"`
	AllowUnsafeCombinations        *bool                    `json:"allowUnsafeCombinations,omitempty"`
}

type UpdateModelCapabilitiesInput struct {
	ModelID                string  `json:"modelId"`
	Provider               *string `json:"provider,omitempty"`
	DeclaredContextTokens  *int    `json:"declaredContextTokens,omitempty"`
	EffectiveContextTokens *int    `json:"effectiveContextTokens,omitempty"`
	InstructionFollowing   *string `json:"instructionFollowing,omitempty"`
	JSONMode               *string `json:"jsonMode,omitempty"`
	ToolUse                *string `json:"toolUse,omitempty"`
	ExtractionGrade        *string `json:"extractionGrade,omitempty"`
	CreativeGrade          *string `json:"creativeGrade,omitempty"`
	EmbeddingModel         *bool   `json:"embeddingModel,omitempty"`
	Source                 *string `json:"source,omitempty"`
	Notes                  *string `json:"notes,omitempty"`
}

type UpdateRepositoryKnowledgeSettingsInput struct {
	RepositoryID          string                  `json:"repositoryId"`
	GenerationModeDefault KnowledgeGenerationMode `json:"generationModeDefault"`
}

type VersionInfo struct {
	Version   string `json:"version"`
	Commit    string `json:"commit"`
	BuildDate string `json:"buildDate"`
}

type Confidence string

const (
	ConfidenceLow      Confidence = "LOW"
	ConfidenceMedium   Confidence = "MEDIUM"
	ConfidenceHigh     Confidence = "HIGH"
	ConfidenceVerified Confidence = "VERIFIED"
)

var AllConfidence = []Confidence{
	ConfidenceLow,
	ConfidenceMedium,
	ConfidenceHigh,
	ConfidenceVerified,
}

func (e Confidence) IsValid() bool {
	switch e {
	case ConfidenceLow, ConfidenceMedium, ConfidenceHigh, ConfidenceVerified:
		return true
	}
	return false
}

func (e Confidence) String() string {
	return string(e)
}

func (e *Confidence) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Confidence(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Confidence", str)
	}
	return nil
}

func (e Confidence) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Confidence) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Confidence) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CrossRepoRefType string

const (
	CrossRepoRefTypeAPIEndpoint     CrossRepoRefType = "API_ENDPOINT"
	CrossRepoRefTypeProtobufService CrossRepoRefType = "PROTOBUF_SERVICE"
	CrossRepoRefTypeGraphqlType     CrossRepoRefType = "GRAPHQL_TYPE"
	CrossRepoRefTypeImport          CrossRepoRefType = "IMPORT"
	CrossRepoRefTypeTypeReference   CrossRepoRefType = "TYPE_REFERENCE"
)

var AllCrossRepoRefType = []CrossRepoRefType{
	CrossRepoRefTypeAPIEndpoint,
	CrossRepoRefTypeProtobufService,
	CrossRepoRefTypeGraphqlType,
	CrossRepoRefTypeImport,
	CrossRepoRefTypeTypeReference,
}

func (e CrossRepoRefType) IsValid() bool {
	switch e {
	case CrossRepoRefTypeAPIEndpoint, CrossRepoRefTypeProtobufService, CrossRepoRefTypeGraphqlType, CrossRepoRefTypeImport, CrossRepoRefTypeTypeReference:
		return true
	}
	return false
}

func (e CrossRepoRefType) String() string {
	return string(e)
}

func (e *CrossRepoRefType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CrossRepoRefType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CrossRepoRefType", str)
	}
	return nil
}

func (e CrossRepoRefType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CrossRepoRefType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CrossRepoRefType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DiagramLevel string

const (
	DiagramLevelModule DiagramLevel = "MODULE"
	DiagramLevelFile   DiagramLevel = "FILE"
)

var AllDiagramLevel = []DiagramLevel{
	DiagramLevelModule,
	DiagramLevelFile,
}

func (e DiagramLevel) IsValid() bool {
	switch e {
	case DiagramLevelModule, DiagramLevelFile:
		return true
	}
	return false
}

func (e DiagramLevel) String() string {
	return string(e)
}

func (e *DiagramLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DiagramLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DiagramLevel", str)
	}
	return nil
}

func (e DiagramLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DiagramLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DiagramLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DiffStatus string

const (
	DiffStatusAdded    DiffStatus = "ADDED"
	DiffStatusModified DiffStatus = "MODIFIED"
	DiffStatusDeleted  DiffStatus = "DELETED"
	DiffStatusRenamed  DiffStatus = "RENAMED"
)

var AllDiffStatus = []DiffStatus{
	DiffStatusAdded,
	DiffStatusModified,
	DiffStatusDeleted,
	DiffStatusRenamed,
}

func (e DiffStatus) IsValid() bool {
	switch e {
	case DiffStatusAdded, DiffStatusModified, DiffStatusDeleted, DiffStatusRenamed:
		return true
	}
	return false
}

func (e DiffStatus) String() string {
	return string(e)
}

func (e *DiffStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DiffStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DiffStatus", str)
	}
	return nil
}

func (e DiffStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DiffStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DiffStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EvidenceSourceType string

const (
	EvidenceSourceTypeRepository    EvidenceSourceType = "REPOSITORY"
	EvidenceSourceTypeFile          EvidenceSourceType = "FILE"
	EvidenceSourceTypeSymbol        EvidenceSourceType = "SYMBOL"
	EvidenceSourceTypeRequirement   EvidenceSourceType = "REQUIREMENT"
	EvidenceSourceTypeLink          EvidenceSourceType = "LINK"
	EvidenceSourceTypeTest          EvidenceSourceType = "TEST"
	EvidenceSourceTypeCommit        EvidenceSourceType = "COMMIT"
	EvidenceSourceTypeDocumentation EvidenceSourceType = "DOCUMENTATION"
)

var AllEvidenceSourceType = []EvidenceSourceType{
	EvidenceSourceTypeRepository,
	EvidenceSourceTypeFile,
	EvidenceSourceTypeSymbol,
	EvidenceSourceTypeRequirement,
	EvidenceSourceTypeLink,
	EvidenceSourceTypeTest,
	EvidenceSourceTypeCommit,
	EvidenceSourceTypeDocumentation,
}

func (e EvidenceSourceType) IsValid() bool {
	switch e {
	case EvidenceSourceTypeRepository, EvidenceSourceTypeFile, EvidenceSourceTypeSymbol, EvidenceSourceTypeRequirement, EvidenceSourceTypeLink, EvidenceSourceTypeTest, EvidenceSourceTypeCommit, EvidenceSourceTypeDocumentation:
		return true
	}
	return false
}

func (e EvidenceSourceType) String() string {
	return string(e)
}

func (e *EvidenceSourceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EvidenceSourceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EvidenceSourceType", str)
	}
	return nil
}

func (e EvidenceSourceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EvidenceSourceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EvidenceSourceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ExecutionEntryKind string

const (
	ExecutionEntryKindRoute  ExecutionEntryKind = "ROUTE"
	ExecutionEntryKindFile   ExecutionEntryKind = "FILE"
	ExecutionEntryKindSymbol ExecutionEntryKind = "SYMBOL"
)

var AllExecutionEntryKind = []ExecutionEntryKind{
	ExecutionEntryKindRoute,
	ExecutionEntryKindFile,
	ExecutionEntryKindSymbol,
}

func (e ExecutionEntryKind) IsValid() bool {
	switch e {
	case ExecutionEntryKindRoute, ExecutionEntryKindFile, ExecutionEntryKindSymbol:
		return true
	}
	return false
}

func (e ExecutionEntryKind) String() string {
	return string(e)
}

func (e *ExecutionEntryKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ExecutionEntryKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ExecutionEntryKind", str)
	}
	return nil
}

func (e ExecutionEntryKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ExecutionEntryKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ExecutionEntryKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type KnowledgeArtifactStatus string

const (
	KnowledgeArtifactStatusPending    KnowledgeArtifactStatus = "PENDING"
	KnowledgeArtifactStatusGenerating KnowledgeArtifactStatus = "GENERATING"
	KnowledgeArtifactStatusReady      KnowledgeArtifactStatus = "READY"
	KnowledgeArtifactStatusFailed     KnowledgeArtifactStatus = "FAILED"
	KnowledgeArtifactStatusStale      KnowledgeArtifactStatus = "STALE"
)

var AllKnowledgeArtifactStatus = []KnowledgeArtifactStatus{
	KnowledgeArtifactStatusPending,
	KnowledgeArtifactStatusGenerating,
	KnowledgeArtifactStatusReady,
	KnowledgeArtifactStatusFailed,
	KnowledgeArtifactStatusStale,
}

func (e KnowledgeArtifactStatus) IsValid() bool {
	switch e {
	case KnowledgeArtifactStatusPending, KnowledgeArtifactStatusGenerating, KnowledgeArtifactStatusReady, KnowledgeArtifactStatusFailed, KnowledgeArtifactStatusStale:
		return true
	}
	return false
}

func (e KnowledgeArtifactStatus) String() string {
	return string(e)
}

func (e *KnowledgeArtifactStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = KnowledgeArtifactStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid KnowledgeArtifactStatus", str)
	}
	return nil
}

func (e KnowledgeArtifactStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *KnowledgeArtifactStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e KnowledgeArtifactStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type KnowledgeArtifactType string

const (
	KnowledgeArtifactTypeCliffNotes          KnowledgeArtifactType = "CLIFF_NOTES"
	KnowledgeArtifactTypeArchitectureDiagram KnowledgeArtifactType = "ARCHITECTURE_DIAGRAM"
	KnowledgeArtifactTypeLearningPath        KnowledgeArtifactType = "LEARNING_PATH"
	KnowledgeArtifactTypeCodeTour            KnowledgeArtifactType = "CODE_TOUR"
	KnowledgeArtifactTypeWorkflowStory       KnowledgeArtifactType = "WORKFLOW_STORY"
)

var AllKnowledgeArtifactType = []KnowledgeArtifactType{
	KnowledgeArtifactTypeCliffNotes,
	KnowledgeArtifactTypeArchitectureDiagram,
	KnowledgeArtifactTypeLearningPath,
	KnowledgeArtifactTypeCodeTour,
	KnowledgeArtifactTypeWorkflowStory,
}

func (e KnowledgeArtifactType) IsValid() bool {
	switch e {
	case KnowledgeArtifactTypeCliffNotes, KnowledgeArtifactTypeArchitectureDiagram, KnowledgeArtifactTypeLearningPath, KnowledgeArtifactTypeCodeTour, KnowledgeArtifactTypeWorkflowStory:
		return true
	}
	return false
}

func (e KnowledgeArtifactType) String() string {
	return string(e)
}

func (e *KnowledgeArtifactType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = KnowledgeArtifactType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid KnowledgeArtifactType", str)
	}
	return nil
}

func (e KnowledgeArtifactType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *KnowledgeArtifactType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e KnowledgeArtifactType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type KnowledgeAudience string

const (
	KnowledgeAudienceBeginner  KnowledgeAudience = "BEGINNER"
	KnowledgeAudienceDeveloper KnowledgeAudience = "DEVELOPER"
)

var AllKnowledgeAudience = []KnowledgeAudience{
	KnowledgeAudienceBeginner,
	KnowledgeAudienceDeveloper,
}

func (e KnowledgeAudience) IsValid() bool {
	switch e {
	case KnowledgeAudienceBeginner, KnowledgeAudienceDeveloper:
		return true
	}
	return false
}

func (e KnowledgeAudience) String() string {
	return string(e)
}

func (e *KnowledgeAudience) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = KnowledgeAudience(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid KnowledgeAudience", str)
	}
	return nil
}

func (e KnowledgeAudience) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *KnowledgeAudience) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e KnowledgeAudience) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type KnowledgeConfidence string

const (
	KnowledgeConfidenceHigh   KnowledgeConfidence = "HIGH"
	KnowledgeConfidenceMedium KnowledgeConfidence = "MEDIUM"
	KnowledgeConfidenceLow    KnowledgeConfidence = "LOW"
)

var AllKnowledgeConfidence = []KnowledgeConfidence{
	KnowledgeConfidenceHigh,
	KnowledgeConfidenceMedium,
	KnowledgeConfidenceLow,
}

func (e KnowledgeConfidence) IsValid() bool {
	switch e {
	case KnowledgeConfidenceHigh, KnowledgeConfidenceMedium, KnowledgeConfidenceLow:
		return true
	}
	return false
}

func (e KnowledgeConfidence) String() string {
	return string(e)
}

func (e *KnowledgeConfidence) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = KnowledgeConfidence(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid KnowledgeConfidence", str)
	}
	return nil
}

func (e KnowledgeConfidence) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *KnowledgeConfidence) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e KnowledgeConfidence) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type KnowledgeDepth string

const (
	KnowledgeDepthSummary KnowledgeDepth = "SUMMARY"
	KnowledgeDepthMedium  KnowledgeDepth = "MEDIUM"
	KnowledgeDepthDeep    KnowledgeDepth = "DEEP"
)

var AllKnowledgeDepth = []KnowledgeDepth{
	KnowledgeDepthSummary,
	KnowledgeDepthMedium,
	KnowledgeDepthDeep,
}

func (e KnowledgeDepth) IsValid() bool {
	switch e {
	case KnowledgeDepthSummary, KnowledgeDepthMedium, KnowledgeDepthDeep:
		return true
	}
	return false
}

func (e KnowledgeDepth) String() string {
	return string(e)
}

func (e *KnowledgeDepth) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = KnowledgeDepth(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid KnowledgeDepth", str)
	}
	return nil
}

func (e KnowledgeDepth) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *KnowledgeDepth) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e KnowledgeDepth) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type KnowledgeGenerationMode string

const (
	KnowledgeGenerationModeClassic            KnowledgeGenerationMode = "CLASSIC"
	KnowledgeGenerationModeUnderstandingFirst KnowledgeGenerationMode = "UNDERSTANDING_FIRST"
)

var AllKnowledgeGenerationMode = []KnowledgeGenerationMode{
	KnowledgeGenerationModeClassic,
	KnowledgeGenerationModeUnderstandingFirst,
}

func (e KnowledgeGenerationMode) IsValid() bool {
	switch e {
	case KnowledgeGenerationModeClassic, KnowledgeGenerationModeUnderstandingFirst:
		return true
	}
	return false
}

func (e KnowledgeGenerationMode) String() string {
	return string(e)
}

func (e *KnowledgeGenerationMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = KnowledgeGenerationMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid KnowledgeGenerationMode", str)
	}
	return nil
}

func (e KnowledgeGenerationMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *KnowledgeGenerationMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e KnowledgeGenerationMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type KnowledgeScopeType string

const (
	KnowledgeScopeTypeRepository  KnowledgeScopeType = "REPOSITORY"
	KnowledgeScopeTypeModule      KnowledgeScopeType = "MODULE"
	KnowledgeScopeTypeFile        KnowledgeScopeType = "FILE"
	KnowledgeScopeTypeSymbol      KnowledgeScopeType = "SYMBOL"
	KnowledgeScopeTypeRequirement KnowledgeScopeType = "REQUIREMENT"
)

var AllKnowledgeScopeType = []KnowledgeScopeType{
	KnowledgeScopeTypeRepository,
	KnowledgeScopeTypeModule,
	KnowledgeScopeTypeFile,
	KnowledgeScopeTypeSymbol,
	KnowledgeScopeTypeRequirement,
}

func (e KnowledgeScopeType) IsValid() bool {
	switch e {
	case KnowledgeScopeTypeRepository, KnowledgeScopeTypeModule, KnowledgeScopeTypeFile, KnowledgeScopeTypeSymbol, KnowledgeScopeTypeRequirement:
		return true
	}
	return false
}

func (e KnowledgeScopeType) String() string {
	return string(e)
}

func (e *KnowledgeScopeType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = KnowledgeScopeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid KnowledgeScopeType", str)
	}
	return nil
}

func (e KnowledgeScopeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *KnowledgeScopeType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e KnowledgeScopeType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Language string

const (
	LanguageGo         Language = "GO"
	LanguagePython     Language = "PYTHON"
	LanguageTypescript Language = "TYPESCRIPT"
	LanguageJavascript Language = "JAVASCRIPT"
	LanguageJava       Language = "JAVA"
	LanguageRust       Language = "RUST"
	LanguageCsharp     Language = "CSHARP"
	LanguageCpp        Language = "CPP"
	LanguageRuby       Language = "RUBY"
	LanguagePhp        Language = "PHP"
	LanguageUnknown    Language = "UNKNOWN"
)

var AllLanguage = []Language{
	LanguageGo,
	LanguagePython,
	LanguageTypescript,
	LanguageJavascript,
	LanguageJava,
	LanguageRust,
	LanguageCsharp,
	LanguageCpp,
	LanguageRuby,
	LanguagePhp,
	LanguageUnknown,
}

func (e Language) IsValid() bool {
	switch e {
	case LanguageGo, LanguagePython, LanguageTypescript, LanguageJavascript, LanguageJava, LanguageRust, LanguageCsharp, LanguageCpp, LanguageRuby, LanguagePhp, LanguageUnknown:
		return true
	}
	return false
}

func (e Language) String() string {
	return string(e)
}

func (e *Language) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Language(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Language", str)
	}
	return nil
}

func (e Language) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Language) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Language) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RepositoryStatus string

const (
	RepositoryStatusPending  RepositoryStatus = "PENDING"
	RepositoryStatusIndexing RepositoryStatus = "INDEXING"
	RepositoryStatusReady    RepositoryStatus = "READY"
	RepositoryStatusError    RepositoryStatus = "ERROR"
)

var AllRepositoryStatus = []RepositoryStatus{
	RepositoryStatusPending,
	RepositoryStatusIndexing,
	RepositoryStatusReady,
	RepositoryStatusError,
}

func (e RepositoryStatus) IsValid() bool {
	switch e {
	case RepositoryStatusPending, RepositoryStatusIndexing, RepositoryStatusReady, RepositoryStatusError:
		return true
	}
	return false
}

func (e RepositoryStatus) String() string {
	return string(e)
}

func (e *RepositoryStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RepositoryStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RepositoryStatus", str)
	}
	return nil
}

func (e RepositoryStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RepositoryStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RepositoryStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RepositoryUnderstandingStage string

const (
	RepositoryUnderstandingStageBuildingTree   RepositoryUnderstandingStage = "BUILDING_TREE"
	RepositoryUnderstandingStageFirstPassReady RepositoryUnderstandingStage = "FIRST_PASS_READY"
	RepositoryUnderstandingStageNeedsRefresh   RepositoryUnderstandingStage = "NEEDS_REFRESH"
	RepositoryUnderstandingStageDeepening      RepositoryUnderstandingStage = "DEEPENING"
	RepositoryUnderstandingStageReady          RepositoryUnderstandingStage = "READY"
	RepositoryUnderstandingStageFailed         RepositoryUnderstandingStage = "FAILED"
)

var AllRepositoryUnderstandingStage = []RepositoryUnderstandingStage{
	RepositoryUnderstandingStageBuildingTree,
	RepositoryUnderstandingStageFirstPassReady,
	RepositoryUnderstandingStageNeedsRefresh,
	RepositoryUnderstandingStageDeepening,
	RepositoryUnderstandingStageReady,
	RepositoryUnderstandingStageFailed,
}

func (e RepositoryUnderstandingStage) IsValid() bool {
	switch e {
	case RepositoryUnderstandingStageBuildingTree, RepositoryUnderstandingStageFirstPassReady, RepositoryUnderstandingStageNeedsRefresh, RepositoryUnderstandingStageDeepening, RepositoryUnderstandingStageReady, RepositoryUnderstandingStageFailed:
		return true
	}
	return false
}

func (e RepositoryUnderstandingStage) String() string {
	return string(e)
}

func (e *RepositoryUnderstandingStage) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RepositoryUnderstandingStage(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RepositoryUnderstandingStage", str)
	}
	return nil
}

func (e RepositoryUnderstandingStage) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RepositoryUnderstandingStage) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RepositoryUnderstandingStage) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RepositoryUnderstandingTreeStatus string

const (
	RepositoryUnderstandingTreeStatusMissing  RepositoryUnderstandingTreeStatus = "MISSING"
	RepositoryUnderstandingTreeStatusPartial  RepositoryUnderstandingTreeStatus = "PARTIAL"
	RepositoryUnderstandingTreeStatusComplete RepositoryUnderstandingTreeStatus = "COMPLETE"
)

var AllRepositoryUnderstandingTreeStatus = []RepositoryUnderstandingTreeStatus{
	RepositoryUnderstandingTreeStatusMissing,
	RepositoryUnderstandingTreeStatusPartial,
	RepositoryUnderstandingTreeStatusComplete,
}

func (e RepositoryUnderstandingTreeStatus) IsValid() bool {
	switch e {
	case RepositoryUnderstandingTreeStatusMissing, RepositoryUnderstandingTreeStatusPartial, RepositoryUnderstandingTreeStatusComplete:
		return true
	}
	return false
}

func (e RepositoryUnderstandingTreeStatus) String() string {
	return string(e)
}

func (e *RepositoryUnderstandingTreeStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RepositoryUnderstandingTreeStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RepositoryUnderstandingTreeStatus", str)
	}
	return nil
}

func (e RepositoryUnderstandingTreeStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RepositoryUnderstandingTreeStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RepositoryUnderstandingTreeStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RequirementFormat string

const (
	RequirementFormatMarkdown RequirementFormat = "MARKDOWN"
	RequirementFormatCSV      RequirementFormat = "CSV"
)

var AllRequirementFormat = []RequirementFormat{
	RequirementFormatMarkdown,
	RequirementFormatCSV,
}

func (e RequirementFormat) IsValid() bool {
	switch e {
	case RequirementFormatMarkdown, RequirementFormatCSV:
		return true
	}
	return false
}

func (e RequirementFormat) String() string {
	return string(e)
}

func (e *RequirementFormat) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RequirementFormat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RequirementFormat", str)
	}
	return nil
}

func (e RequirementFormat) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RequirementFormat) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RequirementFormat) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SymbolChangeType string

const (
	SymbolChangeTypeAdded    SymbolChangeType = "ADDED"
	SymbolChangeTypeModified SymbolChangeType = "MODIFIED"
	SymbolChangeTypeRemoved  SymbolChangeType = "REMOVED"
)

var AllSymbolChangeType = []SymbolChangeType{
	SymbolChangeTypeAdded,
	SymbolChangeTypeModified,
	SymbolChangeTypeRemoved,
}

func (e SymbolChangeType) IsValid() bool {
	switch e {
	case SymbolChangeTypeAdded, SymbolChangeTypeModified, SymbolChangeTypeRemoved:
		return true
	}
	return false
}

func (e SymbolChangeType) String() string {
	return string(e)
}

func (e *SymbolChangeType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SymbolChangeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SymbolChangeType", str)
	}
	return nil
}

func (e SymbolChangeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SymbolChangeType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SymbolChangeType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SymbolKind string

const (
	SymbolKindFunction  SymbolKind = "FUNCTION"
	SymbolKindMethod    SymbolKind = "METHOD"
	SymbolKindClass     SymbolKind = "CLASS"
	SymbolKindStruct    SymbolKind = "STRUCT"
	SymbolKindInterface SymbolKind = "INTERFACE"
	SymbolKindEnum      SymbolKind = "ENUM"
	SymbolKindConstant  SymbolKind = "CONSTANT"
	SymbolKindVariable  SymbolKind = "VARIABLE"
	SymbolKindModule    SymbolKind = "MODULE"
	SymbolKindPackage   SymbolKind = "PACKAGE"
	SymbolKindType      SymbolKind = "TYPE"
	SymbolKindTest      SymbolKind = "TEST"
)

var AllSymbolKind = []SymbolKind{
	SymbolKindFunction,
	SymbolKindMethod,
	SymbolKindClass,
	SymbolKindStruct,
	SymbolKindInterface,
	SymbolKindEnum,
	SymbolKindConstant,
	SymbolKindVariable,
	SymbolKindModule,
	SymbolKindPackage,
	SymbolKindType,
	SymbolKindTest,
}

func (e SymbolKind) IsValid() bool {
	switch e {
	case SymbolKindFunction, SymbolKindMethod, SymbolKindClass, SymbolKindStruct, SymbolKindInterface, SymbolKindEnum, SymbolKindConstant, SymbolKindVariable, SymbolKindModule, SymbolKindPackage, SymbolKindType, SymbolKindTest:
		return true
	}
	return false
}

func (e SymbolKind) String() string {
	return string(e)
}

func (e *SymbolKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SymbolKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SymbolKind", str)
	}
	return nil
}

func (e SymbolKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SymbolKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SymbolKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
