// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 SourceBridge Contributors
//
// Helpers for the per-repository living-wiki settings resolvers.
//
// The actual resolver methods are generated by gqlgen and live in
// schema.resolvers.go:
//   - Query.repositoryLivingWikiSettings
//   - Query.repositoriesUsingSink
//   - Repository.livingWikiSettings
//   - RepositoryLivingWikiSettings.lastJobResult
//   - Mutation.updateRepositoryLivingWikiSettings
//   - Mutation.enableLivingWikiForRepo
//   - Mutation.disableLivingWikiForRepo
//
// This file holds only mapping helpers and cross-resolver utilities so they
// stay out of the large schema.resolvers.go file.

package graphql

import (
	"github.com/sourcebridge/sourcebridge/internal/settings/livingwiki"
)

// ─────────────────────────────────────────────────────────────────────────────
// Helpers used by schema.resolvers.go
// ─────────────────────────────────────────────────────────────────────────────

// defaultRepoSettings returns a zero-value settings record for the given repo.
func defaultRepoSettings(repoID string) *livingwiki.RepositoryLivingWikiSettings {
	return &livingwiki.RepositoryLivingWikiSettings{
		TenantID:          defaultTenantID,
		RepoID:            repoID,
		Enabled:           false,
		Mode:              livingwiki.RepoWikiModePRReview,
		Sinks:             []livingwiki.RepoWikiSink{},
		ExcludePaths:      []string{},
		StaleWhenStrategy: livingwiki.StaleStrategyDirect,
		MaxPagesPerJob:    50,
	}
}

// mapSinkInputs converts GraphQL sink inputs to domain sink models, applying
// default edit policies when the caller omits the field.
func mapSinkInputs(inputs []*RepoWikiSinkInput) []livingwiki.RepoWikiSink {
	out := make([]livingwiki.RepoWikiSink, 0, len(inputs))
	for _, inp := range inputs {
		if inp == nil {
			continue
		}
		sink := livingwiki.RepoWikiSink{
			Kind:            livingwiki.RepoWikiSinkKind(inp.Kind.String()),
			IntegrationName: inp.IntegrationName,
			Audience:        livingwiki.RepoWikiAudience(inp.Audience.String()),
		}
		if inp.EditPolicy != nil {
			sink.EditPolicy = livingwiki.RepoWikiEditPolicy(inp.EditPolicy.String())
		} else {
			// Apply the default policy for the kind silently (Stage A behavior).
			sink.EditPolicy = sink.EffectiveEditPolicy()
		}
		out = append(out, sink)
	}
	return out
}

// mapRepoLivingWikiSettings converts a domain model to the GraphQL type.
// Returns nil when s is nil (repo not yet configured).
func mapRepoLivingWikiSettings(s *livingwiki.RepositoryLivingWikiSettings) *RepositoryLivingWikiSettings {
	if s == nil {
		return nil
	}
	gql := &RepositoryLivingWikiSettings{
		Enabled:           s.Enabled,
		Mode:              RepoWikiMode(s.Mode),
		ExcludePaths:      nonNilStringSlice(s.ExcludePaths),
		StaleWhenStrategy: RepoStaleWhenStrategy(s.StaleWhenStrategy),
		MaxPagesPerJob:    s.MaxPagesPerJob,
	}
	if gql.MaxPagesPerJob == 0 {
		gql.MaxPagesPerJob = 50
	}
	if s.Mode == "" {
		gql.Mode = RepoWikiModePrReview
	}
	if string(s.StaleWhenStrategy) == "" {
		gql.StaleWhenStrategy = RepoStaleWhenStrategyDirect
	}

	gql.Sinks = make([]*RepoWikiSink, 0, len(s.Sinks))
	for _, sink := range s.Sinks {
		ep := RepoWikiEditPolicy(sink.EffectiveEditPolicy())
		gql.Sinks = append(gql.Sinks, &RepoWikiSink{
			Kind:            RepoWikiSinkKind(sink.Kind),
			IntegrationName: sink.IntegrationName,
			Audience:        RepoWikiAudience(sink.Audience),
			EditPolicy:      ep,
		})
	}

	if !s.UpdatedAt.IsZero() {
		gql.UpdatedAt = &s.UpdatedAt
	}
	if s.UpdatedBy != "" {
		gql.UpdatedBy = &s.UpdatedBy
	}
	if s.LastRunAt != nil {
		gql.LastRunAt = s.LastRunAt
	}

	return gql
}

// isLivingWikiGloballyEnabled checks whether the global living-wiki switch is on.
func (r *Resolver) isLivingWikiGloballyEnabled() bool {
	if r.LivingWikiStore == nil {
		return false
	}
	s, err := r.LivingWikiStore.Get()
	if err != nil || s == nil || s.Enabled == nil {
		return false
	}
	return *s.Enabled
}

// defaultTenantID is the tenant used for all single-tenant installs.
// Multi-tenant installs will inject this from context in a future workstream.
const defaultTenantID = "default"

