// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 SourceBridge Contributors

// confluence_writer.go implements the Confluence storage-XHTML sink adapter
// (Workstream A1.P4).
//
// # Confluence storage format
//
// Confluence pages are stored as XHTML with two Atlassian custom namespaces:
//
//   - ac: — macros and structured content
//   - ri: — resource identifiers (page references, users, attachments)
//
// # Block ID preservation
//
// Each AST block is wrapped in a SourceBridge structured macro:
//
//	<ac:structured-macro ac:name="sourcebridge-block">
//	  <ac:parameter ac:name="id">b3f7a1...</ac:parameter>
//	  <ac:parameter ac:name="kind">paragraph</ac:parameter>
//	  <ac:parameter ac:name="owner">generated</ac:parameter>
//	  <ac:rich-text-body>
//	    <!-- rendered block content -->
//	  </ac:rich-text-body>
//	</ac:structured-macro>
//
// Confluence preserves custom macro parameters across view/edit/save cycles,
// so block IDs survive user edits to the surrounding content. The macro
// appears as a visible panel in the Confluence editor but does not clutter the
// published page — Confluence hides unknown macro bodies behind a collapsible
// "Unknown Macro" panel which still preserves the parameters.
//
// # Page reconciliation
//
// Pages are identified by the SourceBridge page ID stored as a page-level
// metadata property ("sourcebridge_page_id"). On upsert the writer:
//
//  1. Fetches the existing page (via ConfluenceClient).
//  2. Parses the block IDs and ownership from the macro parameters.
//  3. Runs block-level reconciliation ([ast.ReconcileBlocks]).
//  4. For generated blocks that changed, writes the new content.
//  5. Leaves human-edited blocks untouched.
//
// # Managed-page marker
//
// A Confluence info macro is emitted at the top of every managed page:
//
//	<ac:structured-macro ac:name="info">
//	  <ac:rich-text-body>
//	    This page is auto-generated by SourceBridge. …
//	  </ac:rich-text-body>
//	</ac:structured-macro>
//
// # Edit policy
//
// Default is local_to_sink (G.2). The caller is responsible for composing
// canonical + overlay[sink] via [ast.ComposeForSink] before passing the page
// to [ConfluenceWriter.WritePage].
//
// # Real HTTP client
//
// The [ConfluenceClient] interface is the port. Real HTTP implementations are
// out of scope for A1.P4. [MemoryConfluenceClient] is the in-memory fake used
// in tests and development.
package markdown

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"regexp"
	"strings"

	"github.com/sourcebridge/sourcebridge/internal/livingwiki/ast"
)

// ─────────────────────────────────────────────────────────────────────────────
// Port interface
// ─────────────────────────────────────────────────────────────────────────────

// ConfluenceProperties is a typed property bag attached to a Confluence page.
// SourceBridge uses it to store the sourcebridge_page_id and last-sync metadata.
type ConfluenceProperties map[string]string

// ConfluenceClient is the port interface for interacting with the Confluence
// REST API. Real implementations call the Confluence Cloud/Server REST API;
// [MemoryConfluenceClient] is the in-memory fake for tests.
//
// All methods receive a context so real implementations can respect
// cancellation and deadlines.
type ConfluenceClient interface {
	// GetPage fetches a page by its SourceBridge external ID.
	// Returns (xhtml, metadata, nil) when the page exists.
	// Returns (nil, nil, nil) when no page with externalID exists yet.
	GetPage(ctx context.Context, externalID string) (xhtml []byte, metadata ConfluenceProperties, err error)

	// UpsertPage creates or updates the page identified by externalID with the
	// given XHTML body and metadata properties. The implementation is
	// responsible for translating externalID to a Confluence page ID on update.
	UpsertPage(ctx context.Context, externalID string, xhtml []byte, metadata ConfluenceProperties) error

	// GetBlockByExternalID fetches the XHTML body of a specific block within a
	// page, identified by the block's SourceBridge block ID stored in the macro
	// parameter. Returns (xhtml, true, nil) when the block is found.
	// Returns (nil, false, nil) when the block does not exist in the page.
	GetBlockByExternalID(ctx context.Context, pageExternalID string, blockExternalID ast.BlockID) (xhtml []byte, ok bool, err error)
}

// ─────────────────────────────────────────────────────────────────────────────
// In-memory fake
// ─────────────────────────────────────────────────────────────────────────────

// confluencePageRecord is the in-memory storage for one Confluence page.
type confluencePageRecord struct {
	xhtml      []byte
	properties ConfluenceProperties
}

// MemoryConfluenceClient is a thread-safe in-memory implementation of
// [ConfluenceClient] for use in tests and development.
type MemoryConfluenceClient struct {
	pages map[string]*confluencePageRecord // externalID → record
}

// NewMemoryConfluenceClient creates an empty [MemoryConfluenceClient].
func NewMemoryConfluenceClient() *MemoryConfluenceClient {
	return &MemoryConfluenceClient{
		pages: make(map[string]*confluencePageRecord),
	}
}

// GetPage implements [ConfluenceClient].
func (m *MemoryConfluenceClient) GetPage(_ context.Context, externalID string) ([]byte, ConfluenceProperties, error) {
	rec, ok := m.pages[externalID]
	if !ok {
		return nil, nil, nil
	}
	// Return copies so callers can't mutate internal state.
	xhtml := make([]byte, len(rec.xhtml))
	copy(xhtml, rec.xhtml)
	props := make(ConfluenceProperties, len(rec.properties))
	for k, v := range rec.properties {
		props[k] = v
	}
	return xhtml, props, nil
}

// UpsertPage implements [ConfluenceClient].
func (m *MemoryConfluenceClient) UpsertPage(_ context.Context, externalID string, xhtml []byte, metadata ConfluenceProperties) error {
	body := make([]byte, len(xhtml))
	copy(body, xhtml)
	props := make(ConfluenceProperties, len(metadata))
	for k, v := range metadata {
		props[k] = v
	}
	m.pages[externalID] = &confluencePageRecord{xhtml: body, properties: props}
	return nil
}

// GetBlockByExternalID implements [ConfluenceClient] by parsing the stored
// XHTML to find the macro with the matching block ID parameter.
func (m *MemoryConfluenceClient) GetBlockByExternalID(_ context.Context, pageExternalID string, blockExternalID ast.BlockID) ([]byte, bool, error) {
	rec, ok := m.pages[pageExternalID]
	if !ok {
		return nil, false, nil
	}
	blocks := parseConfluenceBlocks(rec.xhtml)
	for _, b := range blocks {
		if b.id == blockExternalID {
			return []byte(b.rawXHTML), true, nil
		}
	}
	return nil, false, nil
}

// MutateBlock directly modifies the stored XHTML of a block, simulating a
// Confluence editor changing content. This is used in integration tests to
// inject "human edits" into the in-memory store without going through the
// normal WritePage path.
//
// newBodyXHTML is the XHTML content that replaces the block's rich-text body.
// The block's id, kind, and owner macro parameters are preserved.
func (m *MemoryConfluenceClient) MutateBlock(pageExternalID string, blockID ast.BlockID, newBodyXHTML string) error {
	rec, ok := m.pages[pageExternalID]
	if !ok {
		return fmt.Errorf("memory confluence: page %q not found", pageExternalID)
	}

	// Replace the rich-text body of the block identified by blockID.
	// We do a targeted string replacement of the macro content.
	xhtml := string(rec.xhtml)
	result, err := replaceBlockBody(xhtml, blockID, newBodyXHTML)
	if err != nil {
		return err
	}
	rec.xhtml = []byte(result)
	return nil
}

// replaceBlockBody replaces the ac:rich-text-body content of the block macro
// with the matching id parameter. Returns the modified XHTML or an error if
// the block is not found.
func replaceBlockBody(xhtml string, blockID ast.BlockID, newBodyXHTML string) (string, error) {
	// Find the sourcebridge-block macro containing the given block ID.
	// Pattern: from the macro open tag containing the id parameter through to
	// the closing </ac:structured-macro>.
	escapedID := xmlEscape(string(blockID))
	// Build a pattern that matches: <ac:parameter ac:name="id">blockID</ac:parameter>
	idParamPattern := fmt.Sprintf(`<ac:parameter ac:name="id">%s</ac:parameter>`, regexp.QuoteMeta(escapedID))

	// Find the start of the enclosing macro.
	macroOpen := `<ac:structured-macro ac:name="sourcebridge-block">`

	// Find position of id parameter.
	idIdx := strings.Index(xhtml, idParamPattern)
	if idIdx < 0 {
		return "", fmt.Errorf("confluence block %q not found in XHTML", blockID)
	}

	// Walk backward to find the start of the enclosing macro.
	macroStart := strings.LastIndex(xhtml[:idIdx], macroOpen)
	if macroStart < 0 {
		return "", fmt.Errorf("confluence: could not find macro open tag for block %q", blockID)
	}

	// Find the end of the macro: </ac:structured-macro> after the id parameter.
	macroEnd := strings.Index(xhtml[idIdx:], "</ac:structured-macro>")
	if macroEnd < 0 {
		return "", fmt.Errorf("confluence: could not find macro close tag for block %q", blockID)
	}
	macroEnd = idIdx + macroEnd + len("</ac:structured-macro>")

	// Rebuild the macro with the new body.
	originalMacro := xhtml[macroStart:macroEnd]

	// Extract parameters to preserve them.
	idParam := extractAcParameter(originalMacro, "id")
	kindParam := extractAcParameter(originalMacro, "kind")
	ownerParam := extractAcParameter(originalMacro, "owner")

	var newMacro strings.Builder
	newMacro.WriteString(macroOpen)
	newMacro.WriteString("\n")
	fmt.Fprintf(&newMacro, `<ac:parameter ac:name="id">%s</ac:parameter>`, xmlEscape(idParam))
	newMacro.WriteString("\n")
	fmt.Fprintf(&newMacro, `<ac:parameter ac:name="kind">%s</ac:parameter>`, xmlEscape(kindParam))
	newMacro.WriteString("\n")
	fmt.Fprintf(&newMacro, `<ac:parameter ac:name="owner">%s</ac:parameter>`, xmlEscape(ownerParam))
	newMacro.WriteString("\n")
	newMacro.WriteString("<ac:rich-text-body>\n")
	newMacro.WriteString(newBodyXHTML)
	newMacro.WriteString("\n</ac:rich-text-body>\n")
	newMacro.WriteString("</ac:structured-macro>")

	return xhtml[:macroStart] + newMacro.String() + xhtml[macroEnd:], nil
}

// extractAcParameter extracts the text content of <ac:parameter ac:name="name">…</ac:parameter>.
func extractAcParameter(xhtml, name string) string {
	pattern := fmt.Sprintf(`<ac:parameter ac:name="%s">`, xmlEscape(name))
	idx := strings.Index(xhtml, pattern)
	if idx < 0 {
		return ""
	}
	start := idx + len(pattern)
	end := strings.Index(xhtml[start:], "</ac:parameter>")
	if end < 0 {
		return ""
	}
	// Unescape the value.
	val := xhtml[start : start+end]
	val = strings.ReplaceAll(val, "&amp;", "&")
	val = strings.ReplaceAll(val, "&lt;", "<")
	val = strings.ReplaceAll(val, "&gt;", ">")
	val = strings.ReplaceAll(val, "&quot;", `"`)
	val = strings.ReplaceAll(val, "&apos;", "'")
	return val
}

// ─────────────────────────────────────────────────────────────────────────────
// ConfluenceWriterConfig
// ─────────────────────────────────────────────────────────────────────────────

// ConfluenceWriterConfig controls the behaviour of [ConfluenceWriter].
type ConfluenceWriterConfig struct {
	// SpaceKey is the Confluence space key (e.g. "ENGINEERING").
	// Used as a metadata property on upsert; not required for the in-memory fake.
	SpaceKey string

	// ParentPageID is the Confluence page ID of the parent page under which new
	// pages are created. Optional; if empty the page is created at the space root.
	ParentPageID string
}

// ─────────────────────────────────────────────────────────────────────────────
// ConfluenceWriter
// ─────────────────────────────────────────────────────────────────────────────

// ConfluenceWriter is the Confluence storage-XHTML sink adapter.
//
// Call [WritePage] to do the full read-diff-write cycle:
//  1. Fetch the existing Confluence page via the [ConfluenceClient].
//  2. Parse the existing XHTML to recover block IDs and ownership.
//  3. Run block-level reconciliation.
//  4. Write only changed generated blocks; preserve human-edited blocks.
//  5. Upsert the composed XHTML via the [ConfluenceClient].
//
// The caller must compose canonical + overlay[sink] via [ast.ComposeForSink]
// before calling WritePage when the sink has a local_to_sink policy.
type ConfluenceWriter struct {
	client ConfluenceClient
	cfg    ConfluenceWriterConfig
}

// NewConfluenceWriter creates a [ConfluenceWriter] using the given client.
func NewConfluenceWriter(client ConfluenceClient, cfg ConfluenceWriterConfig) *ConfluenceWriter {
	return &ConfluenceWriter{client: client, cfg: cfg}
}

// WritePage performs the read-diff-write cycle for one page.
//
// The incoming page's blocks are expected to carry stable IDs already
// assigned by the orchestrator (canonical AST or proposed AST).
//
// Algorithm:
//  1. Fetch the existing Confluence page.
//  2. Parse existing blocks to build a map of blockID → existing block.
//  3. For each incoming block:
//     - If an existing block with the same ID is human-edited or human-only,
//       preserve its content and owner (the human edit wins).
//     - Otherwise use the incoming block's content.
//  4. Render and upsert.
//
// Caller responsibility: pass in the result of [ast.ComposeForSink] when the
// Confluence sink has a local_to_sink overlay, so that per-sink divergent
// content is included in the write.
func (cw *ConfluenceWriter) WritePage(ctx context.Context, page ast.Page) error {
	// Step 1: Fetch existing page.
	existingXHTML, _, err := cw.client.GetPage(ctx, page.ID)
	if err != nil {
		return fmt.Errorf("confluence_writer: GetPage %q: %w", page.ID, err)
	}

	// Step 2: Parse existing blocks to recover ownership by block ID.
	existingByID := make(map[ast.BlockID]ast.Block)
	if len(existingXHTML) > 0 {
		for _, b := range confluenceXHTMLToBlocks(existingXHTML) {
			existingByID[b.ID] = b
		}
	}

	// Step 3: Compose the output blocks, preserving human-edited content.
	output := make([]ast.Block, len(page.Blocks))
	for i, blk := range page.Blocks {
		output[i] = blk
		if existing, ok := existingByID[blk.ID]; ok {
			if existing.Owner == ast.OwnerHumanEdited || existing.Owner == ast.OwnerHumanOnly {
				// Human edit wins — preserve the existing content and owner.
				output[i].Content = existing.Content
				output[i].Owner = existing.Owner
			}
		}
	}

	// Step 4: Render to XHTML and upsert.
	var buf bytes.Buffer
	if err := writeConfluencePage(&buf, ast.Page{
		ID:         page.ID,
		Manifest:   page.Manifest,
		Blocks:     output,
		Provenance: page.Provenance,
	}); err != nil {
		return fmt.Errorf("confluence_writer: render %q: %w", page.ID, err)
	}

	props := ConfluenceProperties{
		"sourcebridge_page_id": page.ID,
		"space_key":            cw.cfg.SpaceKey,
	}
	if err := cw.client.UpsertPage(ctx, page.ID, buf.Bytes(), props); err != nil {
		return fmt.Errorf("confluence_writer: UpsertPage %q: %w", page.ID, err)
	}

	return nil
}

// WriteXHTML renders page to Confluence storage XHTML without performing
// read-diff-write reconciliation. Useful for testing the rendering output
// independently of the full WritePage cycle.
func WriteXHTML(w io.Writer, page ast.Page) error {
	return writeConfluencePage(w, page)
}

// ─────────────────────────────────────────────────────────────────────────────
// XHTML rendering
// ─────────────────────────────────────────────────────────────────────────────

// managedPageMarkerXHTML is the info macro emitted at the top of every
// SourceBridge-managed Confluence page.
const managedPageMarkerXHTML = `<ac:structured-macro ac:name="info">
<ac:rich-text-body>
<p>This page is auto-generated by SourceBridge. Edits made directly may be overwritten unless this block is human-edited.</p>
</ac:rich-text-body>
</ac:structured-macro>
`

// writeConfluencePage renders the full page XHTML including the managed marker.
func writeConfluencePage(w io.Writer, page ast.Page) error {
	// Managed-page marker.
	if _, err := io.WriteString(w, managedPageMarkerXHTML); err != nil {
		return err
	}

	for _, blk := range page.Blocks {
		if err := writeConfluenceBlock(w, blk); err != nil {
			return fmt.Errorf("confluence block %q: %w", blk.ID, err)
		}
	}
	return nil
}

// writeConfluenceBlock wraps block content in a sourcebridge-block macro.
func writeConfluenceBlock(w io.Writer, blk ast.Block) error {
	// Open the sourcebridge-block structured macro.
	if err := writeAcMacroOpen(w, "sourcebridge-block"); err != nil {
		return err
	}
	// Block ID parameter.
	if err := writeAcParameter(w, "id", string(blk.ID)); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w); err != nil {
		return err
	}
	// Kind parameter.
	if err := writeAcParameter(w, "kind", string(blk.Kind)); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w); err != nil {
		return err
	}
	// Owner parameter.
	if err := writeAcParameter(w, "owner", string(blk.Owner)); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w); err != nil {
		return err
	}
	// Rich-text body.
	if err := writeAcRichTextBodyWrap(w, func(inner io.Writer) error {
		return writeConfluenceBlockContent(inner, blk.Kind, blk.Content)
	}); err != nil {
		return err
	}
	// Close the macro.
	return writeAcMacroClose(w)
}

// writeConfluenceBlockContent renders one block's content as Confluence XHTML.
func writeConfluenceBlockContent(w io.Writer, kind ast.BlockKind, content ast.BlockContent) error {
	switch kind {
	case ast.BlockKindHeading:
		return writeConfluenceHeading(w, content)
	case ast.BlockKindParagraph:
		return writeConfluenceParagraph(w, content)
	case ast.BlockKindCode:
		return writeConfluenceCode(w, content)
	case ast.BlockKindTable:
		return writeConfluenceTable(w, content)
	case ast.BlockKindCallout:
		return writeConfluenceCallout(w, content)
	case ast.BlockKindEmbed:
		return writeConfluenceEmbed(w, content)
	case ast.BlockKindFreeform:
		return writeConfluenceFreeform(w, content)
	case ast.BlockKindStaleBanner:
		return writeConfluenceStaleBanner(w, content)
	default:
		// Unknown kind — wrap as paragraph so the page doesn't break.
		if _, err := fmt.Fprintf(w, "<p>[unknown block kind: %s]</p>\n", xmlEscape(string(kind))); err != nil {
			return err
		}
		return nil
	}
}

func writeConfluenceHeading(w io.Writer, content ast.BlockContent) error {
	if content.Heading == nil {
		return nil
	}
	tag := headingTagForLevel(content.Heading.Level)
	if err := writeOpenTag(w, tag); err != nil {
		return err
	}
	if err := writeText(w, content.Heading.Text); err != nil {
		return err
	}
	if err := writeCloseTag(w, tag); err != nil {
		return err
	}
	return writeln(w)
}

func writeConfluenceParagraph(w io.Writer, content ast.BlockContent) error {
	if content.Paragraph == nil {
		return nil
	}
	// Markdown is stored as-is inside a paragraph. Confluence renders inline
	// markdown-style syntax poorly, but the AST's primary audience for this
	// storage format is the Confluence editor, so we convert inline markup
	// minimally: just wrap in <p> and escape special characters.
	// Full markdown→XHTML inline conversion is deferred (A1.P6).
	if err := writeOpenTag(w, "p"); err != nil {
		return err
	}
	if err := writeText(w, content.Paragraph.Markdown); err != nil {
		return err
	}
	if err := writeCloseTag(w, "p"); err != nil {
		return err
	}
	return writeln(w)
}

func writeConfluenceCode(w io.Writer, content ast.BlockContent) error {
	if content.Code == nil {
		return nil
	}
	// Confluence Code Block macro.
	if err := writeAcMacroOpen(w, "code"); err != nil {
		return err
	}
	lang := confluenceCodeLanguage(content.Code.Language)
	if err := writeAcParameter(w, "language", lang); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w); err != nil {
		return err
	}
	// Code body goes in a plain-text body (not rich-text).
	if err := writeOpenTag(w, "ac:plain-text-body"); err != nil {
		return err
	}
	// CDATA wraps code to prevent XML special-character escaping.
	if _, err := fmt.Fprintf(w, "<![CDATA[%s]]>", content.Code.Body); err != nil {
		return err
	}
	if err := writeCloseTag(w, "ac:plain-text-body"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w); err != nil {
		return err
	}
	return writeAcMacroClose(w)
}

func writeConfluenceTable(w io.Writer, content ast.BlockContent) error {
	if content.Table == nil {
		return nil
	}
	t := content.Table
	if len(t.Headers) == 0 {
		return nil
	}

	if err := writeOpenTag(w, "table"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w); err != nil {
		return err
	}

	// Header row.
	if err := writeOpenTag(w, "tr"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w); err != nil {
		return err
	}
	for _, h := range t.Headers {
		if err := writeOpenTag(w, "th"); err != nil {
			return err
		}
		if err := writeText(w, h); err != nil {
			return err
		}
		if err := writeCloseTag(w, "th"); err != nil {
			return err
		}
		if _, err := fmt.Fprintln(w); err != nil {
			return err
		}
	}
	if err := writeCloseTag(w, "tr"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w); err != nil {
		return err
	}

	// Data rows.
	for _, row := range t.Rows {
		if err := writeOpenTag(w, "tr"); err != nil {
			return err
		}
		if _, err := fmt.Fprintln(w); err != nil {
			return err
		}
		for _, cell := range row {
			if err := writeOpenTag(w, "td"); err != nil {
				return err
			}
			if err := writeText(w, cell); err != nil {
				return err
			}
			if err := writeCloseTag(w, "td"); err != nil {
				return err
			}
			if _, err := fmt.Fprintln(w); err != nil {
				return err
			}
		}
		if err := writeCloseTag(w, "tr"); err != nil {
			return err
		}
		if _, err := fmt.Fprintln(w); err != nil {
			return err
		}
	}

	if err := writeCloseTag(w, "table"); err != nil {
		return err
	}
	return writeln(w)
}

func writeConfluenceCallout(w io.Writer, content ast.BlockContent) error {
	if content.Callout == nil {
		return nil
	}
	// Map callout kind to Confluence macro name.
	macroName := calloutKindToConfluenceMacro(content.Callout.Kind)
	if err := writeAcMacroOpen(w, macroName); err != nil {
		return err
	}
	if err := writeAcRichTextBodyWrap(w, func(inner io.Writer) error {
		if err := writeOpenTag(inner, "p"); err != nil {
			return err
		}
		if err := writeText(inner, content.Callout.Body); err != nil {
			return err
		}
		if err := writeCloseTag(inner, "p"); err != nil {
			return err
		}
		return writeln(inner)
	}); err != nil {
		return err
	}
	return writeAcMacroClose(w)
}

// calloutKindToConfluenceMacro maps callout kind strings to Confluence macro names.
// Confluence has: note, tip, info, warning.
func calloutKindToConfluenceMacro(kind string) string {
	switch strings.ToLower(kind) {
	case "warning", "danger":
		return "warning"
	case "tip":
		return "tip"
	case "note":
		return "note"
	default:
		return "info"
	}
}

func writeConfluenceEmbed(w io.Writer, content ast.BlockContent) error {
	if content.Embed == nil {
		return nil
	}
	// Embeds are represented as a Confluence page include macro.
	if err := writeAcMacroOpen(w, "include"); err != nil {
		return err
	}
	if err := writeOpenTag(w, "ri:page", "ri:content-title", content.Embed.TargetPageID); err != nil {
		return err
	}
	if err := writeCloseTag(w, "ri:page"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w); err != nil {
		return err
	}
	if content.Embed.TargetBlockID != "" {
		if err := writeAcParameter(w, "block_id", string(content.Embed.TargetBlockID)); err != nil {
			return err
		}
		if _, err := fmt.Fprintln(w); err != nil {
			return err
		}
	}
	return writeAcMacroClose(w)
}

func writeConfluenceFreeform(w io.Writer, content ast.BlockContent) error {
	if content.Freeform == nil {
		return nil
	}
	// Freeform content is stored as raw text inside a paragraph. Callers
	// writing freeform blocks are responsible for ensuring the raw content is
	// valid XHTML — we do not escape it here.
	if _, err := fmt.Fprintln(w, content.Freeform.Raw); err != nil {
		return err
	}
	return nil
}

func writeConfluenceStaleBanner(w io.Writer, content ast.BlockContent) error {
	if content.StaleBanner == nil {
		return nil
	}
	s := content.StaleBanner
	// Stale banners render as Confluence warning macros.
	if err := writeAcMacroOpen(w, "warning"); err != nil {
		return err
	}
	if err := writeAcRichTextBodyWrap(w, func(inner io.Writer) error {
		if err := writeOpenTag(inner, "p"); err != nil {
			return err
		}
		syms := strings.Join(s.TriggeringSymbols, ", ")
		text := fmt.Sprintf("This page may be out of date. Recent changes to %s (commit %s) may affect this content.", syms, s.TriggeringCommit)
		if s.RefreshURL != "" {
			text += " Refresh from source: " + s.RefreshURL
		}
		if s.NextRegenWindow != "" {
			text += " Next scheduled regen: " + s.NextRegenWindow
		}
		if err := writeText(inner, text); err != nil {
			return err
		}
		if err := writeCloseTag(inner, "p"); err != nil {
			return err
		}
		return writeln(inner)
	}); err != nil {
		return err
	}
	return writeAcMacroClose(w)
}

// ─────────────────────────────────────────────────────────────────────────────
// XHTML → AST parsing (for reconciliation read-back)
// ─────────────────────────────────────────────────────────────────────────────

// confluenceParsedBlock is the result of parsing one sourcebridge-block macro
// from stored Confluence XHTML.
type confluenceParsedBlock struct {
	id      ast.BlockID
	kind    ast.BlockKind
	owner   ast.Owner
	rawXHTML string
}

// parseConfluenceBlocks extracts all sourcebridge-block macros from XHTML,
// returning their id/kind/owner parameters and raw body content.
func parseConfluenceBlocks(xhtml []byte) []confluenceParsedBlock {
	s := string(xhtml)
	const macroOpen = `<ac:structured-macro ac:name="sourcebridge-block">`
	const macroClose = `</ac:structured-macro>`

	var results []confluenceParsedBlock
	offset := 0
	for {
		idx := strings.Index(s[offset:], macroOpen)
		if idx < 0 {
			break
		}
		start := offset + idx
		end := strings.Index(s[start:], macroClose)
		if end < 0 {
			break
		}
		end = start + end + len(macroClose)
		macroXHTML := s[start:end]

		id := extractAcParameter(macroXHTML, "id")
		kind := extractAcParameter(macroXHTML, "kind")
		owner := extractAcParameter(macroXHTML, "owner")
		body := extractRichTextBody(macroXHTML)

		if id != "" {
			results = append(results, confluenceParsedBlock{
				id:      ast.BlockID(id),
				kind:    ast.BlockKind(kind),
				owner:   ast.Owner(owner),
				rawXHTML: body,
			})
		}
		offset = end
	}
	return results
}

// extractRichTextBody returns the content between <ac:rich-text-body> tags.
func extractRichTextBody(xhtml string) string {
	const open = "<ac:rich-text-body>"
	const close = "</ac:rich-text-body>"
	start := strings.Index(xhtml, open)
	if start < 0 {
		return ""
	}
	start += len(open)
	end := strings.Index(xhtml[start:], close)
	if end < 0 {
		return xhtml[start:]
	}
	return strings.TrimSpace(xhtml[start : start+end])
}

// confluenceXHTMLToBlocks converts parsed Confluence block data to [ast.Block]
// values. Content fields are partially reconstructed from XHTML; for
// reconciliation purposes, we need at minimum the ID, Kind, and Owner so that
// human-edited blocks are recognised and preserved.
func confluenceXHTMLToBlocks(xhtml []byte) []ast.Block {
	parsed := parseConfluenceBlocks(xhtml)
	blocks := make([]ast.Block, 0, len(parsed))
	for _, p := range parsed {
		blk := ast.Block{
			ID:    p.id,
			Kind:  p.kind,
			Owner: p.owner,
		}
		// Reconstruct content from XHTML for fingerprinting.
		blk.Content = confluenceXHTMLToBlockContent(p.kind, p.rawXHTML)
		blocks = append(blocks, blk)
	}
	return blocks
}

// confluenceXHTMLToBlockContent does a best-effort reconstruction of block
// content from Confluence XHTML. Heading, paragraph, and code are recovered
// with reasonable fidelity; table and callout are partial. The primary use
// case is content-fingerprint matching during reconciliation, not perfect
// round-trip.
func confluenceXHTMLToBlockContent(kind ast.BlockKind, rawXHTML string) ast.BlockContent {
	switch kind {
	case ast.BlockKindHeading:
		return confluenceParseHeading(rawXHTML)
	case ast.BlockKindParagraph:
		return confluenceParseParagraph(rawXHTML)
	case ast.BlockKindCode:
		return confluenceParseCode(rawXHTML)
	case ast.BlockKindTable:
		return confluenceParseTable(rawXHTML)
	case ast.BlockKindCallout:
		return confluenceParseCallout(rawXHTML)
	case ast.BlockKindStaleBanner:
		return confluenceParseStaleBanner(rawXHTML)
	case ast.BlockKindFreeform:
		return ast.BlockContent{
			Freeform: &ast.FreeformContent{Raw: strings.TrimSpace(rawXHTML)},
		}
	default:
		return ast.BlockContent{
			Freeform: &ast.FreeformContent{Raw: strings.TrimSpace(rawXHTML)},
		}
	}
}

// reHeadingTag matches an opening heading tag and captures the level digit and content.
// Go's regexp does not support backreferences, so we match the open/close tags separately.
var reHeadingTag = regexp.MustCompile(`(?i)<(h[1-6])[^>]*>`)

func confluenceParseHeading(rawXHTML string) ast.BlockContent {
	m := reHeadingTag.FindStringSubmatch(rawXHTML)
	if m == nil {
		return ast.BlockContent{
			Heading: &ast.HeadingContent{Level: 1, Text: strings.TrimSpace(stripTags(rawXHTML))},
		}
	}
	tag := strings.ToLower(m[1])
	level := 1
	if len(tag) == 2 && tag[0] == 'h' {
		level = int(tag[1] - '0')
	}
	// Strip the opening tag, content between tags, closing tag.
	closeTag := "</" + tag + ">"
	text := rawXHTML
	if start := strings.Index(text, m[0]); start >= 0 {
		text = text[start+len(m[0]):]
	}
	if end := strings.Index(strings.ToLower(text), closeTag); end >= 0 {
		text = text[:end]
	}
	return ast.BlockContent{
		Heading: &ast.HeadingContent{Level: level, Text: strings.TrimSpace(stripTags(text))},
	}
}

func confluenceParseParagraph(rawXHTML string) ast.BlockContent {
	text := strings.TrimSpace(stripTags(rawXHTML))
	// Unescape XML entities.
	text = strings.ReplaceAll(text, "&amp;", "&")
	text = strings.ReplaceAll(text, "&lt;", "<")
	text = strings.ReplaceAll(text, "&gt;", ">")
	text = strings.ReplaceAll(text, "&quot;", `"`)
	text = strings.ReplaceAll(text, "&apos;", "'")
	return ast.BlockContent{
		Paragraph: &ast.ParagraphContent{Markdown: text},
	}
}

func confluenceParseCode(rawXHTML string) ast.BlockContent {
	// Extract language from ac:parameter and body from CDATA.
	lang := extractAcParameter(rawXHTML, "language")
	body := extractCDATA(rawXHTML)
	return ast.BlockContent{
		Code: &ast.CodeContent{Language: lang, Body: body},
	}
}

// reConfluenceTable parses table cells out of simple Confluence XHTML tables.
var reTH = regexp.MustCompile(`(?i)<th[^>]*>([\s\S]*?)</th>`)
var reTD = regexp.MustCompile(`(?i)<td[^>]*>([\s\S]*?)</td>`)
var reTR = regexp.MustCompile(`(?i)<tr[^>]*>([\s\S]*?)</tr>`)

func confluenceParseTable(rawXHTML string) ast.BlockContent {
	var headers []string
	var rows [][]string

	trMatches := reTR.FindAllStringSubmatch(rawXHTML, -1)
	for i, trm := range trMatches {
		rowXHTML := trm[1]
		if i == 0 {
			// Header row — th elements.
			for _, thm := range reTH.FindAllStringSubmatch(rowXHTML, -1) {
				headers = append(headers, strings.TrimSpace(stripTags(thm[1])))
			}
			if len(headers) == 0 {
				// Headerless table — treat first tr as data.
				for _, tdm := range reTD.FindAllStringSubmatch(rowXHTML, -1) {
					headers = append(headers, strings.TrimSpace(stripTags(tdm[1])))
				}
			}
		} else {
			var row []string
			for _, tdm := range reTD.FindAllStringSubmatch(rowXHTML, -1) {
				row = append(row, strings.TrimSpace(stripTags(tdm[1])))
			}
			if len(row) > 0 {
				rows = append(rows, row)
			}
		}
	}

	return ast.BlockContent{
		Table: &ast.TableContent{Headers: headers, Rows: rows},
	}
}

func confluenceParseCallout(rawXHTML string) ast.BlockContent {
	text := strings.TrimSpace(stripTags(rawXHTML))
	return ast.BlockContent{
		Callout: &ast.CalloutContent{Kind: "note", Body: text},
	}
}

func confluenceParseStaleBanner(rawXHTML string) ast.BlockContent {
	// Best-effort: extract any text content.
	return ast.BlockContent{
		StaleBanner: &ast.StaleBannerContent{},
	}
}

// stripTags removes all XML/HTML tags from a string.
var reAnyTag = regexp.MustCompile(`<[^>]+>`)

func stripTags(s string) string {
	return reAnyTag.ReplaceAllString(s, "")
}

// extractCDATA extracts the content of the first CDATA section in s.
func extractCDATA(s string) string {
	const open = "<![CDATA["
	const close = "]]>"
	start := strings.Index(s, open)
	if start < 0 {
		return stripTags(s)
	}
	start += len(open)
	end := strings.Index(s[start:], close)
	if end < 0 {
		return s[start:]
	}
	return s[start : start+end]
}

// ─────────────────────────────────────────────────────────────────────────────
// Shared helpers
// ─────────────────────────────────────────────────────────────────────────────

// buildAnchorsForPage builds a StructuralAnchor for each block in blocks.
// It walks the blocks to compute the current heading path and same-kind ordinal
// at each level. This is the same anchoring used by the markdown writer.
func buildAnchorsForPage(blocks []ast.Block) []ast.StructuralAnchor {
	anchors := make([]ast.StructuralAnchor, len(blocks))
	headingPath := ""
	kindCounters := make(map[string]int) // headingPath+kind → count

	for i, blk := range blocks {
		key := headingPath + string(blk.Kind)
		ordinal := kindCounters[key]
		kindCounters[key]++
		anchors[i] = ast.StructuralAnchor{
			HeadingPath: headingPath,
			Kind:        blk.Kind,
			Ordinal:     ordinal,
		}
		if blk.Kind == ast.BlockKindHeading && blk.Content.Heading != nil {
			headingPath = blk.Content.Heading.Text
			// Reset kind counters for blocks under the new heading.
			kindCounters = make(map[string]int)
		}
	}
	return anchors
}

// Compile-time check: ConfluenceWriter satisfies no public interface currently
// because WritePage needs a context (unlike the sync SinkWriter interface).
// The confluence and notion writers have a richer WritePage(ctx, page) signature.
var _ ConfluenceClient = (*MemoryConfluenceClient)(nil)
