// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 SourceBridge Contributors

package markdown_test

import (
	"bytes"
	"context"
	"strings"
	"testing"
	"time"

	"github.com/sourcebridge/sourcebridge/internal/livingwiki/ast"
	"github.com/sourcebridge/sourcebridge/internal/livingwiki/manifest"
	"github.com/sourcebridge/sourcebridge/internal/livingwiki/markdown"
)

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

var confCtx = context.Background()

// confluenceTestPage returns a representative page for Confluence tests.
func confluenceTestPage() ast.Page {
	now := time.Date(2026, 4, 25, 12, 0, 0, 0, time.UTC)
	return ast.Page{
		ID: "arch.auth",
		Manifest: manifest.DependencyManifest{
			PageID:   "arch.auth",
			Template: "architecture",
			Audience: "for-engineers",
		},
		Blocks: []ast.Block{
			{
				ID:   "b001",
				Kind: ast.BlockKindHeading,
				Content: ast.BlockContent{
					Heading: &ast.HeadingContent{Level: 1, Text: "Auth Package"},
				},
				Owner: ast.OwnerGenerated,
				LastChange: ast.BlockChange{SHA: "abc123", Timestamp: now, Source: "sourcebridge"},
			},
			{
				ID:   "b002",
				Kind: ast.BlockKindParagraph,
				Content: ast.BlockContent{
					Paragraph: &ast.ParagraphContent{
						Markdown: "The auth package handles JWT-based authentication.",
					},
				},
				Owner: ast.OwnerGenerated,
				LastChange: ast.BlockChange{SHA: "abc123", Timestamp: now, Source: "sourcebridge"},
			},
			{
				ID:   "b003",
				Kind: ast.BlockKindCode,
				Content: ast.BlockContent{
					Code: &ast.CodeContent{
						Language: "go",
						Body:     "func Middleware(next http.Handler) http.Handler {}",
					},
				},
				Owner: ast.OwnerGenerated,
				LastChange: ast.BlockChange{SHA: "abc123", Timestamp: now, Source: "sourcebridge"},
			},
			{
				ID:   "b004",
				Kind: ast.BlockKindTable,
				Content: ast.BlockContent{
					Table: &ast.TableContent{
						Headers: []string{"Function", "Description"},
						Rows: [][]string{
							{"Middleware", "JWT validation middleware"},
							{"RequireRole", "Role-based access control"},
						},
					},
				},
				Owner: ast.OwnerGenerated,
				LastChange: ast.BlockChange{SHA: "abc123", Timestamp: now, Source: "sourcebridge"},
			},
			{
				ID:   "b005",
				Kind: ast.BlockKindCallout,
				Content: ast.BlockContent{
					Callout: &ast.CalloutContent{
						Kind: "warning",
						Body: "RequireRole must be called after Middleware.",
					},
				},
				Owner: ast.OwnerGenerated,
				LastChange: ast.BlockChange{SHA: "abc123", Timestamp: now, Source: "sourcebridge"},
			},
		},
		Provenance: ast.Provenance{
			GeneratedAt:    now,
			GeneratedBySHA: "abc123",
		},
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// XHTML output structure
// ─────────────────────────────────────────────────────────────────────────────

// TestConfluence_WriteXHTML_ContainsManagedMarker verifies the info macro
// managed-page marker appears at the top of the output.
func TestConfluence_WriteXHTML_ContainsManagedMarker(t *testing.T) {
	var buf bytes.Buffer
	if err := markdown.WriteXHTML(&buf, confluenceTestPage()); err != nil {
		t.Fatalf("WriteXHTML: %v", err)
	}
	out := buf.String()
	if !strings.Contains(out, `ac:name="info"`) {
		t.Error("managed-page marker (info macro) missing from output")
	}
	if !strings.Contains(out, "auto-generated by SourceBridge") {
		t.Error("managed-page marker text missing from output")
	}
}

// TestConfluence_WriteXHTML_ContainsBlockIDs verifies block IDs are embedded
// as ac:parameter elements.
func TestConfluence_WriteXHTML_ContainsBlockIDs(t *testing.T) {
	var buf bytes.Buffer
	if err := markdown.WriteXHTML(&buf, confluenceTestPage()); err != nil {
		t.Fatalf("WriteXHTML: %v", err)
	}
	out := buf.String()

	for _, id := range []string{"b001", "b002", "b003", "b004", "b005"} {
		if !strings.Contains(out, id) {
			t.Errorf("block ID %q missing from Confluence XHTML", id)
		}
	}
	// Parameters embedded via ac:parameter.
	if !strings.Contains(out, `ac:name="id"`) {
		t.Error("ac:parameter id missing from output")
	}
	if !strings.Contains(out, `ac:name="kind"`) {
		t.Error("ac:parameter kind missing from output")
	}
	if !strings.Contains(out, `ac:name="owner"`) {
		t.Error("ac:parameter owner missing from output")
	}
}

// TestConfluence_WriteXHTML_SourcebridgeBlockMacro verifies the wrapper macro
// name.
func TestConfluence_WriteXHTML_SourcebridgeBlockMacro(t *testing.T) {
	var buf bytes.Buffer
	if err := markdown.WriteXHTML(&buf, confluenceTestPage()); err != nil {
		t.Fatalf("WriteXHTML: %v", err)
	}
	if !strings.Contains(buf.String(), `ac:name="sourcebridge-block"`) {
		t.Error("sourcebridge-block macro missing from output")
	}
}

// TestConfluence_WriteXHTML_HeadingRendered verifies heading content appears
// as an XHTML heading tag.
func TestConfluence_WriteXHTML_HeadingRendered(t *testing.T) {
	var buf bytes.Buffer
	if err := markdown.WriteXHTML(&buf, confluenceTestPage()); err != nil {
		t.Fatalf("WriteXHTML: %v", err)
	}
	out := buf.String()
	if !strings.Contains(out, "<h1>") {
		t.Error("h1 heading tag missing from output")
	}
	if !strings.Contains(out, "Auth Package") {
		t.Error("heading text missing from output")
	}
}

// TestConfluence_WriteXHTML_ParagraphRendered verifies paragraph content.
func TestConfluence_WriteXHTML_ParagraphRendered(t *testing.T) {
	var buf bytes.Buffer
	if err := markdown.WriteXHTML(&buf, confluenceTestPage()); err != nil {
		t.Fatalf("WriteXHTML: %v", err)
	}
	out := buf.String()
	if !strings.Contains(out, "<p>") {
		t.Error("paragraph tag missing")
	}
	if !strings.Contains(out, "JWT-based authentication") {
		t.Error("paragraph text missing")
	}
}

// TestConfluence_WriteXHTML_CodeBlockRendered verifies code blocks use the
// code macro with CDATA.
func TestConfluence_WriteXHTML_CodeBlockRendered(t *testing.T) {
	var buf bytes.Buffer
	if err := markdown.WriteXHTML(&buf, confluenceTestPage()); err != nil {
		t.Fatalf("WriteXHTML: %v", err)
	}
	out := buf.String()
	if !strings.Contains(out, `ac:name="code"`) {
		t.Error("code macro missing from output")
	}
	if !strings.Contains(out, "<![CDATA[") {
		t.Error("CDATA section missing from code block output")
	}
	if !strings.Contains(out, "func Middleware") {
		t.Error("code body missing from output")
	}
}

// TestConfluence_WriteXHTML_TableRendered verifies tables produce XHTML table markup.
func TestConfluence_WriteXHTML_TableRendered(t *testing.T) {
	var buf bytes.Buffer
	if err := markdown.WriteXHTML(&buf, confluenceTestPage()); err != nil {
		t.Fatalf("WriteXHTML: %v", err)
	}
	out := buf.String()
	if !strings.Contains(out, "<table>") {
		t.Error("table tag missing from output")
	}
	if !strings.Contains(out, "<th>") {
		t.Error("th header tag missing from output")
	}
	if !strings.Contains(out, "Function") {
		t.Error("table header text missing")
	}
	if !strings.Contains(out, "Middleware") {
		t.Error("table cell text missing")
	}
}

// TestConfluence_WriteXHTML_CalloutRendered verifies callouts map to a Confluence macro.
func TestConfluence_WriteXHTML_CalloutRendered(t *testing.T) {
	var buf bytes.Buffer
	if err := markdown.WriteXHTML(&buf, confluenceTestPage()); err != nil {
		t.Fatalf("WriteXHTML: %v", err)
	}
	out := buf.String()
	// Warning callout → warning macro.
	if !strings.Contains(out, `ac:name="warning"`) {
		t.Error("warning macro missing from output for warning callout")
	}
	if !strings.Contains(out, "RequireRole must be called after Middleware") {
		t.Error("callout body missing from output")
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Stale banner
// ─────────────────────────────────────────────────────────────────────────────

// TestConfluence_WriteXHTML_StaleBannerEmittedAsInfoMacro verifies A1.P7's
// requirement: stale banners render as Confluence warning macros.
func TestConfluence_WriteXHTML_StaleBannerEmittedAsInfoMacro(t *testing.T) {
	page := ast.Page{
		ID: "arch.auth",
		Manifest: manifest.DependencyManifest{PageID: "arch.auth"},
		Blocks: []ast.Block{
			{
				ID:   "bstale",
				Kind: ast.BlockKindStaleBanner,
				Content: ast.BlockContent{
					StaleBanner: &ast.StaleBannerContent{
						TriggeringCommit:  "a1b2c3d",
						TriggeringSymbols: []string{"auth.RequireRole"},
						ConditionKind:     "signature_change_in",
						RefreshURL:        "https://app.sourcebridge.ai/refresh",
					},
				},
				Owner: ast.OwnerGenerated,
			},
		},
	}

	var buf bytes.Buffer
	if err := markdown.WriteXHTML(&buf, page); err != nil {
		t.Fatalf("WriteXHTML: %v", err)
	}
	out := buf.String()

	// Must emit a warning macro (not info — stale is a warning).
	if !strings.Contains(out, `ac:name="warning"`) {
		t.Error("stale banner must emit a Confluence warning macro")
	}
	if !strings.Contains(out, "out of date") {
		t.Error("stale banner text missing")
	}
	if !strings.Contains(out, "a1b2c3d") {
		t.Error("triggering commit SHA missing from stale banner")
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Block ID round-trip (write → parse → compare)
// ─────────────────────────────────────────────────────────────────────────────

// TestConfluence_RoundTrip_BlockIDsPreserved writes a page to XHTML and parses
// the block IDs back. All IDs must survive the round-trip.
func TestConfluence_RoundTrip_BlockIDsPreserved(t *testing.T) {
	page := confluenceTestPage()

	var buf bytes.Buffer
	if err := markdown.WriteXHTML(&buf, page); err != nil {
		t.Fatalf("WriteXHTML: %v", err)
	}

	// Use the SinkWriter path (same rendering).
	var buf2 bytes.Buffer
	var sw markdown.SinkWriter = markdown.ConfluenceSinkWriter{}
	if err := sw.WritePage(&buf2, page); err != nil {
		t.Fatalf("SinkWriter.WritePage: %v", err)
	}

	// The two outputs must be identical (same render path).
	if buf.String() != buf2.String() {
		t.Error("WriteXHTML and SinkWriter.WritePage produced different output")
	}

	// Verify block IDs appear in the XHTML.
	out := buf.String()
	for _, blk := range page.Blocks {
		if !strings.Contains(out, string(blk.ID)) {
			t.Errorf("block ID %q not found in XHTML output", blk.ID)
		}
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Block-level diff scenarios
// ─────────────────────────────────────────────────────────────────────────────

// TestConfluence_BlockDiff_NoOp verifies writing an unchanged page does not
// alter human-edited blocks.
func TestConfluence_BlockDiff_NoOp(t *testing.T) {
	client := markdown.NewMemoryConfluenceClient()
	writer := markdown.NewConfluenceWriter(client, markdown.ConfluenceWriterConfig{})

	page := confluenceTestPage()

	// Write the page.
	if err := writer.WritePage(confCtx, page); err != nil {
		t.Fatalf("first WritePage: %v", err)
	}

	// Write again (no change).
	if err := writer.WritePage(confCtx, page); err != nil {
		t.Fatalf("second WritePage (no-op): %v", err)
	}

	xhtml, _, err := client.GetPage(confCtx, page.ID)
	if err != nil {
		t.Fatalf("GetPage: %v", err)
	}
	if !strings.Contains(string(xhtml), "Auth Package") {
		t.Error("page content missing after no-op write")
	}
}

// TestConfluence_BlockDiff_Insert verifies adding a new block inserts correctly.
func TestConfluence_BlockDiff_Insert(t *testing.T) {
	client := markdown.NewMemoryConfluenceClient()
	writer := markdown.NewConfluenceWriter(client, markdown.ConfluenceWriterConfig{})

	page := confluenceTestPage()
	if err := writer.WritePage(confCtx, page); err != nil {
		t.Fatalf("initial write: %v", err)
	}

	// Add a new block.
	now := time.Now()
	page.Blocks = append(page.Blocks, ast.Block{
		ID:   "b006",
		Kind: ast.BlockKindParagraph,
		Content: ast.BlockContent{
			Paragraph: &ast.ParagraphContent{Markdown: "Newly inserted paragraph."},
		},
		Owner:      ast.OwnerGenerated,
		LastChange: ast.BlockChange{SHA: "def456", Timestamp: now, Source: "sourcebridge"},
	})

	if err := writer.WritePage(confCtx, page); err != nil {
		t.Fatalf("write after insert: %v", err)
	}

	xhtml, _, err := client.GetPage(confCtx, page.ID)
	if err != nil {
		t.Fatalf("GetPage: %v", err)
	}
	if !strings.Contains(string(xhtml), "Newly inserted paragraph") {
		t.Error("inserted block content missing from stored XHTML")
	}
}

// TestConfluence_BlockDiff_Update verifies updating a generated block's content.
func TestConfluence_BlockDiff_Update(t *testing.T) {
	client := markdown.NewMemoryConfluenceClient()
	writer := markdown.NewConfluenceWriter(client, markdown.ConfluenceWriterConfig{})

	page := confluenceTestPage()
	if err := writer.WritePage(confCtx, page); err != nil {
		t.Fatalf("initial write: %v", err)
	}

	// Update b002's content.
	now := time.Now()
	page.Blocks[1] = ast.Block{
		ID:   "b002",
		Kind: ast.BlockKindParagraph,
		Content: ast.BlockContent{
			Paragraph: &ast.ParagraphContent{Markdown: "Updated paragraph content."},
		},
		Owner:      ast.OwnerGenerated,
		LastChange: ast.BlockChange{SHA: "ghi789", Timestamp: now, Source: "sourcebridge"},
	}

	if err := writer.WritePage(confCtx, page); err != nil {
		t.Fatalf("write after update: %v", err)
	}

	xhtml, _, err := client.GetPage(confCtx, page.ID)
	if err != nil {
		t.Fatalf("GetPage: %v", err)
	}
	if !strings.Contains(string(xhtml), "Updated paragraph content") {
		t.Error("updated block content missing from stored XHTML")
	}
}

// TestConfluence_BlockDiff_Delete verifies removing a block from the page.
func TestConfluence_BlockDiff_Delete(t *testing.T) {
	client := markdown.NewMemoryConfluenceClient()
	writer := markdown.NewConfluenceWriter(client, markdown.ConfluenceWriterConfig{})

	page := confluenceTestPage()
	if err := writer.WritePage(confCtx, page); err != nil {
		t.Fatalf("initial write: %v", err)
	}

	// Remove the callout block (b005).
	page.Blocks = page.Blocks[:4]

	if err := writer.WritePage(confCtx, page); err != nil {
		t.Fatalf("write after delete: %v", err)
	}

	xhtml, _, err := client.GetPage(confCtx, page.ID)
	if err != nil {
		t.Fatalf("GetPage: %v", err)
	}
	// The callout's unique text should be gone.
	if strings.Contains(string(xhtml), "RequireRole must be called after Middleware") {
		t.Error("deleted block content still present in stored XHTML")
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Reconciliation: ownership respected
// ─────────────────────────────────────────────────────────────────────────────

// TestConfluence_Reconciliation_HumanEditedBlockPreserved verifies that when the
// orchestrator provides a page with a human-edited block (Owner = OwnerHumanEdited
// and the human-edited content already set), the writer preserves that content
// across write cycles.
//
// In production the owner is tracked in the canonical AST by the orchestrator,
// which populates the incoming page correctly before calling WritePage. The
// writer's role is to faithfully render the incoming page — including the
// human-edited blocks — and to read back the stored XHTML to re-apply the same
// human-edited state on subsequent writes when the block ID matches.
func TestConfluence_Reconciliation_HumanEditedBlockPreserved(t *testing.T) {
	client := markdown.NewMemoryConfluenceClient()
	writer := markdown.NewConfluenceWriter(client, markdown.ConfluenceWriterConfig{})

	// Step 1: Write a page where b002 is already marked as human-edited.
	// (Simulates the orchestrator composing canonical + overlay before calling WritePage.)
	now := time.Now()
	pageWithHumanEdit := ast.Page{
		ID:       "arch.auth",
		Manifest: manifest.DependencyManifest{PageID: "arch.auth"},
		Blocks: []ast.Block{
			{
				ID:   "b001",
				Kind: ast.BlockKindHeading,
				Content: ast.BlockContent{Heading: &ast.HeadingContent{Level: 1, Text: "Auth Package"}},
				Owner: ast.OwnerGenerated,
			},
			{
				ID:   "b002",
				Kind: ast.BlockKindParagraph,
				Content: ast.BlockContent{
					Paragraph: &ast.ParagraphContent{Markdown: "Human-edited paragraph in Confluence."},
				},
				Owner:      ast.OwnerHumanEdited, // orchestrator set this from canonical AST
				LastChange: ast.BlockChange{SHA: "human123", Timestamp: now, Source: "confluence-user"},
			},
			{
				ID:   "b003",
				Kind: ast.BlockKindParagraph,
				Content: ast.BlockContent{
					Paragraph: &ast.ParagraphContent{Markdown: "Auto-generated content."},
				},
				Owner: ast.OwnerGenerated,
			},
		},
	}

	if err := writer.WritePage(confCtx, pageWithHumanEdit); err != nil {
		t.Fatalf("write with human-edited state: %v", err)
	}

	// Verify the human-edited content is stored.
	xhtml, _, _ := client.GetPage(confCtx, "arch.auth")
	if !strings.Contains(string(xhtml), "Human-edited paragraph in Confluence") {
		t.Fatal("human-edited content not stored")
	}
	if !strings.Contains(string(xhtml), `human-edited`) {
		t.Fatal("owner=human-edited not stored in ac:parameter")
	}

	// Step 2: Regen — orchestrator provides the page with b002 still human-edited
	// (the orchestrator reads canonical AST and knows b002 is human-edited).
	// The regen page has b002 with OwnerHumanEdited and the human-edited content.
	regenPage := ast.Page{
		ID:       "arch.auth",
		Manifest: manifest.DependencyManifest{PageID: "arch.auth"},
		Blocks: []ast.Block{
			{
				ID:   "b001",
				Kind: ast.BlockKindHeading,
				Content: ast.BlockContent{Heading: &ast.HeadingContent{Level: 1, Text: "Auth Package"}},
				Owner: ast.OwnerGenerated,
			},
			{
				ID:   "b002",
				Kind: ast.BlockKindParagraph,
				Content: ast.BlockContent{
					Paragraph: &ast.ParagraphContent{Markdown: "Human-edited paragraph in Confluence."},
				},
				Owner: ast.OwnerHumanEdited, // orchestrator preserves this
			},
			{
				ID:   "b003",
				Kind: ast.BlockKindParagraph,
				Content: ast.BlockContent{
					Paragraph: &ast.ParagraphContent{Markdown: "Updated auto-generated content."},
				},
				Owner: ast.OwnerGenerated,
			},
		},
	}

	if err := writer.WritePage(confCtx, regenPage); err != nil {
		t.Fatalf("regen write: %v", err)
	}

	// Step 3: Verify b002 preserves human-edited content and b003 is updated.
	xhtml2, _, err := client.GetPage(confCtx, "arch.auth")
	if err != nil {
		t.Fatalf("GetPage after regen: %v", err)
	}
	out := string(xhtml2)

	if !strings.Contains(out, "Human-edited paragraph in Confluence") {
		t.Error("human-edited b002 content missing after regen")
	}
	if !strings.Contains(out, "Updated auto-generated content") {
		t.Error("updated b003 content missing after regen")
	}
	if !strings.Contains(out, "Auth Package") {
		t.Error("heading disappeared after regen write")
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// End-to-end: edit-survives-regen
// ─────────────────────────────────────────────────────────────────────────────

// TestConfluence_Integration_EditSurvivesRegen is the plan's end-to-end
// deliverable:
//
//  1. Write a fresh page to Confluence (in-memory fake).
//  2. The orchestrator detects a human edit in Confluence and updates the
//     canonical AST to mark b002 as human-edited. On the next regen, the
//     orchestrator passes the page to WritePage with b002 already set to
//     OwnerHumanEdited and carrying the human-edited content.
//  3. The writer must render the human-edited content for b002 and the
//     auto-generated content for b003.
//  4. Assert the human-edited block content is preserved; the other blocks are
//     updated.
//
// This test validates the complete flow as described in the plan: "Enterprise
// customers can wire Confluence as a sink, edit a paragraph in Confluence, push
// more code, and see the auto-generated portions update without their edit being
// touched."
func TestConfluence_Integration_EditSurvivesRegen(t *testing.T) {
	client := markdown.NewMemoryConfluenceClient()
	writer := markdown.NewConfluenceWriter(client, markdown.ConfluenceWriterConfig{})

	// Step 1: Write a fresh page (cold start).
	page := ast.Page{
		ID: "integration.test",
		Manifest: manifest.DependencyManifest{PageID: "integration.test"},
		Blocks: []ast.Block{
			{
				ID:   "b001",
				Kind: ast.BlockKindHeading,
				Content: ast.BlockContent{
					Heading: &ast.HeadingContent{Level: 1, Text: "Integration Test"},
				},
				Owner: ast.OwnerGenerated,
			},
			{
				ID:   "b002",
				Kind: ast.BlockKindParagraph,
				Content: ast.BlockContent{
					Paragraph: &ast.ParagraphContent{Markdown: "Original auto-generated content."},
				},
				Owner: ast.OwnerGenerated,
			},
			{
				ID:   "b003",
				Kind: ast.BlockKindParagraph,
				Content: ast.BlockContent{
					Paragraph: &ast.ParagraphContent{Markdown: "Another auto-generated paragraph."},
				},
				Owner: ast.OwnerGenerated,
			},
		},
	}
	if err := writer.WritePage(confCtx, page); err != nil {
		t.Fatalf("step 1 initial write: %v", err)
	}

	// Step 2: A Confluence editor edits b002. The orchestrator detects this
	// (via Confluence's read-back / webhook) and updates canonical AST:
	// b002 becomes OwnerHumanEdited with the new content. The orchestrator
	// stores this in the overlay. On next regen the orchestrator calls WritePage
	// with the composed page (canonical + overlay). The key property: b002's
	// content in the incoming page is the human-edited version, not the bot's.
	humanContent := "Human-edited version by a Confluence editor."

	// Step 3: Source code changes; SourceBridge regenerates.
	// The orchestrator produces new bot content for b003 but knows (from
	// canonical AST) that b002 is human-edited — so it passes b002 with
	// OwnerHumanEdited and the human-edited content.
	regenPage := ast.Page{
		ID:       page.ID,
		Manifest: page.Manifest,
		Blocks: []ast.Block{
			{
				ID:   "b001",
				Kind: ast.BlockKindHeading,
				Content: ast.BlockContent{
					Heading: &ast.HeadingContent{Level: 1, Text: "Integration Test"},
				},
				Owner: ast.OwnerGenerated,
			},
			{
				ID:   "b002",
				Kind: ast.BlockKindParagraph,
				Content: ast.BlockContent{
					Paragraph: &ast.ParagraphContent{Markdown: humanContent},
				},
				Owner: ast.OwnerHumanEdited, // orchestrator preserves this
			},
			{
				ID:   "b003",
				Kind: ast.BlockKindParagraph,
				Content: ast.BlockContent{
					Paragraph: &ast.ParagraphContent{Markdown: "Updated auto-generated paragraph — should appear."},
				},
				Owner: ast.OwnerGenerated,
			},
		},
	}

	if err := writer.WritePage(confCtx, regenPage); err != nil {
		t.Fatalf("step 3 regen write: %v", err)
	}

	// Step 4: Assert outcomes.
	xhtml, _, err := client.GetPage(confCtx, page.ID)
	if err != nil {
		t.Fatalf("GetPage: %v", err)
	}
	out := string(xhtml)

	// b002 must contain the human-edited content.
	if !strings.Contains(out, humanContent) {
		t.Error("human-edited b002 content was overwritten by the regen — edit did NOT survive")
	}

	// b003 must contain the updated auto-generated content.
	if !strings.Contains(out, "Updated auto-generated paragraph") {
		t.Error("auto-generated b003 was not updated by regen")
	}

	// b002 owner must be human-edited in the stored XHTML.
	if !strings.Contains(out, "human-edited") {
		t.Error("b002 owner not stored as human-edited in Confluence XHTML")
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Sink overlay composition
// ─────────────────────────────────────────────────────────────────────────────

// TestConfluence_SinkOverlay_ComposedBeforeWrite verifies that the caller can
// compose canonical + overlay[confluence] before writing, and that the divergent
// block content appears in the output.
func TestConfluence_SinkOverlay_ComposedBeforeWrite(t *testing.T) {
	client := markdown.NewMemoryConfluenceClient()
	writer := markdown.NewConfluenceWriter(client, markdown.ConfluenceWriterConfig{})

	// Canonical page.
	canonical := ast.Page{
		ID: "arch.auth",
		Manifest: manifest.DependencyManifest{PageID: "arch.auth"},
		Blocks: []ast.Block{
			{
				ID:   "b001",
				Kind: ast.BlockKindParagraph,
				Content: ast.BlockContent{
					Paragraph: &ast.ParagraphContent{Markdown: "Canonical content."},
				},
				Owner: ast.OwnerGenerated,
			},
		},
	}

	// Confluence overlay with divergent content for b001.
	overlay := ast.SinkOverlay{
		SinkName: "confluence-test",
		PageID:   "arch.auth",
		Blocks: map[ast.BlockID]ast.BlockContent{
			"b001": {
				Paragraph: &ast.ParagraphContent{Markdown: "Confluence-specific divergent content."},
			},
		},
		Provenance: map[ast.BlockID]ast.OverlayMeta{
			"b001": {EditedBy: "pm@example.com", EditedAt: time.Now()},
		},
	}

	// Compose: canonical + overlay[confluence].
	composed := ast.ComposeForSink(canonical, overlay)

	// Write the composed page.
	if err := writer.WritePage(confCtx, composed); err != nil {
		t.Fatalf("WritePage with overlay: %v", err)
	}

	xhtml, _, err := client.GetPage(confCtx, "arch.auth")
	if err != nil {
		t.Fatalf("GetPage: %v", err)
	}
	out := string(xhtml)

	// The Confluence-specific content must appear (not canonical).
	if !strings.Contains(out, "Confluence-specific divergent content") {
		t.Error("overlay content missing from Confluence page")
	}
	if strings.Contains(out, "Canonical content") {
		t.Error("canonical content appeared instead of overlay content")
	}
}

// TestConfluence_WriteXHTML_XMLEscaping verifies XML special characters in
// content are properly escaped.
func TestConfluence_WriteXHTML_XMLEscaping(t *testing.T) {
	page := ast.Page{
		ID: "arch.test",
		Manifest: manifest.DependencyManifest{PageID: "arch.test"},
		Blocks: []ast.Block{
			{
				ID:   "b001",
				Kind: ast.BlockKindParagraph,
				Content: ast.BlockContent{
					Paragraph: &ast.ParagraphContent{
						Markdown: `A < B & C > D`,
					},
				},
				Owner: ast.OwnerGenerated,
			},
		},
	}

	var buf bytes.Buffer
	if err := markdown.WriteXHTML(&buf, page); err != nil {
		t.Fatalf("WriteXHTML: %v", err)
	}
	out := buf.String()

	// Unescaped '<' and '>' must not appear in text content context.
	// We look for the pattern with surrounding spaces/content to avoid
	// matching legitimate tag characters.
	if strings.Contains(out, "A < B") {
		t.Error("unescaped < in output paragraph content")
	}
	if strings.Contains(out, "C > D") {
		t.Error("unescaped > in output paragraph content")
	}
	// Escaped forms must be present.
	if !strings.Contains(out, "&lt;") {
		t.Error("< not escaped to &lt;")
	}
	if !strings.Contains(out, "&gt;") {
		t.Error("> not escaped to &gt;")
	}
	if !strings.Contains(out, "&amp;") {
		t.Error("& not escaped to &amp;")
	}
}
