// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 SourceBridge Contributors

// notion_writer.go implements the Notion block-based sink adapter
// (Workstream A1.P4).
//
// # Notion block format
//
// Notion pages are composed of a flat list of typed block objects.
// Each block is a JSON object with the schema:
//
//	{
//	  "object": "block",
//	  "type": "<block_type>",
//	  "<block_type>": { /* type-specific payload */ },
//	  "external_id": "<sourcebridge-block-id>"
//	}
//
// The "external_id" field is used by SourceBridge to recover block IDs after
// they are stored in Notion. Notion preserves arbitrary metadata in the
// external_id field across view/edit/save cycles for API-created blocks.
//
// # AST → Notion block type mapping
//
//	AST kind       → Notion type
//	---------        -----------
//	heading        → heading_1 / heading_2 / heading_3 (by level; level 4+ → heading_3)
//	paragraph      → paragraph
//	code           → code (with language)
//	table          → table (parent) + table_row (children) — see note below
//	callout        → callout
//	embed          → embed (URL from page/block reference)
//	freeform       → paragraph (with raw content as text)
//	stale_banner   → callout (warning emoji)
//
// # Table limitations
//
// Notion's table block model requires a nested structure:
// - A "table" block containing a "children" array of "table_row" blocks.
// - The first row is the header row (table.has_column_header = true).
//
// This adapter emits the nested structure. Round-trip fidelity for tables is
// limited: reading back a table from Notion via [NotionReader] may not
// recover all content since Notion's API returns children separately from
// the parent table block.
//
// # Page reconciliation
//
// Pages are identified by the SourceBridge page ID stored as a Notion page
// property ("sourcebridge_page_id"). [NotionWriter.WritePage] performs:
//
//  1. Fetch the existing Notion page blocks via [NotionClient].
//  2. Recover block IDs from the external_id fields.
//  3. Run block-level reconciliation ([ast.ReconcileBlocks]).
//  4. Append new blocks; update changed generated blocks; leave human-edited blocks.
//
// # Managed-page marker
//
// A callout block is emitted at the top of every managed Notion page:
//
//	{
//	  "object": "block",
//	  "type": "callout",
//	  "callout": {
//	    "icon": {"type":"emoji","emoji":"ℹ️"},
//	    "rich_text": [{"type":"text","text":{"content":"This page is auto-generated by SourceBridge. …"}}]
//	  }
//	}
//
// # Edit policy
//
// Default is local_to_sink (G.2). The caller must compose canonical + overlay
// via [ast.ComposeForSink] before passing the page to [NotionWriter.WritePage].
//
// # Real HTTP client
//
// [NotionClient] is the port. Real HTTP implementations call the Notion API;
// [MemoryNotionClient] is the in-memory fake for tests.
package markdown

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strings"

	"github.com/sourcebridge/sourcebridge/internal/livingwiki/ast"
)

// ─────────────────────────────────────────────────────────────────────────────
// Notion block types
// ─────────────────────────────────────────────────────────────────────────────

// NotionBlock is one Notion block object. The Type field discriminates the
// payload; the payload field with the same name as Type is populated.
//
// SourceBridge stores block IDs in the ExternalID field so they survive
// Notion's own ID churn and can be parsed back during reconciliation.
type NotionBlock struct {
	Object     string          `json:"object"`
	Type       string          `json:"type"`
	ExternalID string          `json:"external_id,omitempty"`
	Payload    json.RawMessage `json:"-"` // typed payload; serialized via MarshalJSON

	// Parsed payload fields — populated by UnmarshalJSON, consumed by MarshalJSON.
	paragraph  *notionParagraph
	heading1   *notionHeading
	heading2   *notionHeading
	heading3   *notionHeading
	code       *notionCode
	callout    *notionCallout
	embed      *notionEmbed
	table      *notionTable
	tableRow   *notionTableRow
	children   []NotionBlock
}

// MarshalJSON serialises the block to JSON, placing the typed payload under
// the block's type key. Children are inlined within the payload for table rows.
func (b NotionBlock) MarshalJSON() ([]byte, error) {
	// Build a raw map so we can set the dynamic type field.
	m := map[string]interface{}{
		"object": b.Object,
		"type":   b.Type,
	}
	if b.ExternalID != "" {
		m["external_id"] = b.ExternalID
	}

	switch b.Type {
	case "paragraph":
		m["paragraph"] = b.paragraph
	case "heading_1":
		m["heading_1"] = b.heading1
	case "heading_2":
		m["heading_2"] = b.heading2
	case "heading_3":
		m["heading_3"] = b.heading3
	case "code":
		m["code"] = b.code
	case "callout":
		m["callout"] = b.callout
	case "embed":
		m["embed"] = b.embed
	case "table":
		m["table"] = b.table
		if len(b.children) > 0 {
			m["children"] = b.children
		}
	case "table_row":
		m["table_row"] = b.tableRow
	}
	return json.Marshal(m)
}

// UnmarshalJSON parses a Notion block JSON object into the typed struct.
func (b *NotionBlock) UnmarshalJSON(data []byte) error {
	// Decode into a raw map first.
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	if v, ok := raw["object"]; ok {
		_ = json.Unmarshal(v, &b.Object)
	}
	if v, ok := raw["type"]; ok {
		_ = json.Unmarshal(v, &b.Type)
	}
	if v, ok := raw["external_id"]; ok {
		_ = json.Unmarshal(v, &b.ExternalID)
	}
	if v, ok := raw["children"]; ok {
		_ = json.Unmarshal(v, &b.children)
	}

	switch b.Type {
	case "paragraph":
		b.paragraph = &notionParagraph{}
		if v, ok := raw["paragraph"]; ok {
			_ = json.Unmarshal(v, b.paragraph)
		}
	case "heading_1":
		b.heading1 = &notionHeading{}
		if v, ok := raw["heading_1"]; ok {
			_ = json.Unmarshal(v, b.heading1)
		}
	case "heading_2":
		b.heading2 = &notionHeading{}
		if v, ok := raw["heading_2"]; ok {
			_ = json.Unmarshal(v, b.heading2)
		}
	case "heading_3":
		b.heading3 = &notionHeading{}
		if v, ok := raw["heading_3"]; ok {
			_ = json.Unmarshal(v, b.heading3)
		}
	case "code":
		b.code = &notionCode{}
		if v, ok := raw["code"]; ok {
			_ = json.Unmarshal(v, b.code)
		}
	case "callout":
		b.callout = &notionCallout{}
		if v, ok := raw["callout"]; ok {
			_ = json.Unmarshal(v, b.callout)
		}
	case "embed":
		b.embed = &notionEmbed{}
		if v, ok := raw["embed"]; ok {
			_ = json.Unmarshal(v, b.embed)
		}
	case "table":
		b.table = &notionTable{}
		if v, ok := raw["table"]; ok {
			_ = json.Unmarshal(v, b.table)
		}
	case "table_row":
		b.tableRow = &notionTableRow{}
		if v, ok := raw["table_row"]; ok {
			_ = json.Unmarshal(v, b.tableRow)
		}
	}
	return nil
}

// notionRichTextItem is one element of a rich_text array.
type notionRichTextItem struct {
	Type string          `json:"type"`
	Text notionTextValue `json:"text"`
}

// notionTextValue is the text content within a rich_text item.
type notionTextValue struct {
	Content string `json:"content"`
}

// notionRichText builds a single-item rich_text array with plain text.
func notionRichText(text string) []notionRichTextItem {
	return []notionRichTextItem{
		{Type: "text", Text: notionTextValue{Content: text}},
	}
}

// notionParagraph is the payload for a "paragraph" block.
type notionParagraph struct {
	RichText []notionRichTextItem `json:"rich_text"`
}

// notionHeading is the shared payload for heading_1 / heading_2 / heading_3.
type notionHeading struct {
	RichText []notionRichTextItem `json:"rich_text"`
}

// notionCode is the payload for a "code" block.
type notionCode struct {
	RichText []notionRichTextItem `json:"rich_text"`
	Language string               `json:"language"`
}

// notionCalloutIcon is the icon sub-object of a callout block.
type notionCalloutIcon struct {
	Type  string `json:"type"`
	Emoji string `json:"emoji,omitempty"`
}

// notionCallout is the payload for a "callout" block.
type notionCallout struct {
	Icon     notionCalloutIcon    `json:"icon"`
	RichText []notionRichTextItem `json:"rich_text"`
}

// notionEmbed is the payload for an "embed" block.
type notionEmbed struct {
	URL string `json:"url"`
}

// notionTable is the payload for a "table" block.
type notionTable struct {
	TableWidth      int  `json:"table_width"`
	HasColumnHeader bool `json:"has_column_header"`
	HasRowHeader    bool `json:"has_row_header"`
}

// notionTableRow is the payload for a "table_row" block.
type notionTableRow struct {
	Cells [][]notionRichTextItem `json:"cells"`
}

// NotionProperties is a typed property bag for a Notion page.
type NotionProperties map[string]string

// ─────────────────────────────────────────────────────────────────────────────
// Port interface
// ─────────────────────────────────────────────────────────────────────────────

// NotionClient is the port interface for interacting with the Notion API.
// Real implementations call the Notion REST API; [MemoryNotionClient] is the
// in-memory fake for tests.
type NotionClient interface {
	// GetPage fetches all blocks for the page identified by externalID.
	// Returns (nil, nil, nil) when no page with externalID exists yet.
	GetPage(ctx context.Context, externalID string) (blocks []NotionBlock, properties NotionProperties, err error)

	// UpsertPage creates or replaces the page identified by externalID with
	// the given blocks and properties. On update the implementation is
	// responsible for translating externalID to a Notion page ID.
	UpsertPage(ctx context.Context, externalID string, blocks []NotionBlock, properties NotionProperties) error

	// AppendBlocks adds new blocks to an existing page.
	AppendBlocks(ctx context.Context, pageExternalID string, blocks []NotionBlock) error

	// UpdateBlock replaces the content of an existing block identified by its
	// Notion block ID (not the SourceBridge external_id). In the in-memory fake
	// we identify blocks by external_id for simplicity.
	UpdateBlock(ctx context.Context, blockExternalID string, block NotionBlock) error

	// DeleteBlock removes a block from its parent page.
	DeleteBlock(ctx context.Context, blockExternalID string) error
}

// ─────────────────────────────────────────────────────────────────────────────
// In-memory fake
// ─────────────────────────────────────────────────────────────────────────────

// notionPageRecord is the in-memory storage for one Notion page.
type notionPageRecord struct {
	blocks     []NotionBlock
	properties NotionProperties
}

// MemoryNotionClient is a thread-safe in-memory implementation of [NotionClient].
type MemoryNotionClient struct {
	pages map[string]*notionPageRecord // externalID → record
}

// NewMemoryNotionClient creates an empty [MemoryNotionClient].
func NewMemoryNotionClient() *MemoryNotionClient {
	return &MemoryNotionClient{
		pages: make(map[string]*notionPageRecord),
	}
}

// GetPage implements [NotionClient].
func (m *MemoryNotionClient) GetPage(_ context.Context, externalID string) ([]NotionBlock, NotionProperties, error) {
	rec, ok := m.pages[externalID]
	if !ok {
		return nil, nil, nil
	}
	blocks := make([]NotionBlock, len(rec.blocks))
	copy(blocks, rec.blocks)
	props := make(NotionProperties, len(rec.properties))
	for k, v := range rec.properties {
		props[k] = v
	}
	return blocks, props, nil
}

// UpsertPage implements [NotionClient].
func (m *MemoryNotionClient) UpsertPage(_ context.Context, externalID string, blocks []NotionBlock, properties NotionProperties) error {
	bl := make([]NotionBlock, len(blocks))
	copy(bl, blocks)
	props := make(NotionProperties, len(properties))
	for k, v := range properties {
		props[k] = v
	}
	m.pages[externalID] = &notionPageRecord{blocks: bl, properties: props}
	return nil
}

// AppendBlocks implements [NotionClient].
func (m *MemoryNotionClient) AppendBlocks(_ context.Context, pageExternalID string, blocks []NotionBlock) error {
	rec, ok := m.pages[pageExternalID]
	if !ok {
		return fmt.Errorf("memory notion: page %q not found", pageExternalID)
	}
	rec.blocks = append(rec.blocks, blocks...)
	return nil
}

// UpdateBlock implements [NotionClient] by external_id.
func (m *MemoryNotionClient) UpdateBlock(_ context.Context, blockExternalID string, block NotionBlock) error {
	for _, rec := range m.pages {
		for i, b := range rec.blocks {
			if b.ExternalID == blockExternalID {
				rec.blocks[i] = block
				return nil
			}
		}
	}
	return fmt.Errorf("memory notion: block %q not found", blockExternalID)
}

// DeleteBlock implements [NotionClient] by external_id.
func (m *MemoryNotionClient) DeleteBlock(_ context.Context, blockExternalID string) error {
	for _, rec := range m.pages {
		for i, b := range rec.blocks {
			if b.ExternalID == blockExternalID {
				rec.blocks = append(rec.blocks[:i], rec.blocks[i+1:]...)
				return nil
			}
		}
	}
	return fmt.Errorf("memory notion: block %q not found", blockExternalID)
}

// MutateBlock directly modifies a block's rich_text content, simulating a
// Notion editor changing content. Used in integration tests to inject "human
// edits" without going through WritePage.
func (m *MemoryNotionClient) MutateBlock(pageExternalID string, blockExternalID string, newText string) error {
	rec, ok := m.pages[pageExternalID]
	if !ok {
		return fmt.Errorf("memory notion: page %q not found", pageExternalID)
	}
	for i, b := range rec.blocks {
		if b.ExternalID == blockExternalID {
			mutated := b
			switch b.Type {
			case "paragraph":
				mutated.paragraph = &notionParagraph{RichText: notionRichText(newText)}
			case "heading_1", "heading_2", "heading_3":
				h := &notionHeading{RichText: notionRichText(newText)}
				switch b.Type {
				case "heading_1":
					mutated.heading1 = h
				case "heading_2":
					mutated.heading2 = h
				case "heading_3":
					mutated.heading3 = h
				}
			case "callout":
				if mutated.callout == nil {
					mutated.callout = &notionCallout{}
				}
				mutated.callout.RichText = notionRichText(newText)
			default:
				mutated.paragraph = &notionParagraph{RichText: notionRichText(newText)}
				mutated.Type = "paragraph"
			}
			rec.blocks[i] = mutated
			return nil
		}
	}
	return fmt.Errorf("memory notion: block %q not found in page %q", blockExternalID, pageExternalID)
}

// ─────────────────────────────────────────────────────────────────────────────
// NotionWriterConfig
// ─────────────────────────────────────────────────────────────────────────────

// NotionWriterConfig controls the behaviour of [NotionWriter].
type NotionWriterConfig struct {
	// ParentPageID is the Notion page ID under which new pages are created.
	// Optional; if empty the implementation creates a top-level page.
	ParentPageID string
}

// ─────────────────────────────────────────────────────────────────────────────
// NotionWriter
// ─────────────────────────────────────────────────────────────────────────────

// NotionWriter is the Notion sink adapter.
//
// Call [WritePage] to do the full read-diff-write cycle:
//  1. Fetch the existing Notion page blocks via [NotionClient].
//  2. Recover block IDs from external_id fields.
//  3. Run block-level reconciliation.
//  4. Write only changed generated blocks; preserve human-edited blocks.
//  5. Upsert the composed block list via [NotionClient].
type NotionWriter struct {
	client NotionClient
	cfg    NotionWriterConfig
}

// NewNotionWriter creates a [NotionWriter] using the given client.
func NewNotionWriter(client NotionClient, cfg NotionWriterConfig) *NotionWriter {
	return &NotionWriter{client: client, cfg: cfg}
}

// WritePage performs the read-diff-write cycle for one page.
//
// The incoming page's blocks carry stable IDs from the canonical AST.
//
// Algorithm:
//  1. Fetch existing Notion blocks.
//  2. Build a map of blockID → existing AST block (recovering ownership from
//     the Notion external_id and a stored owner hint).
//  3. For each incoming block: if an existing block with the same ID is
//     human-edited or human-only, preserve its content. Otherwise use incoming.
//  4. Render and upsert.
func (nw *NotionWriter) WritePage(ctx context.Context, page ast.Page) error {
	// Step 1: Fetch existing blocks.
	existingBlocks, _, err := nw.client.GetPage(ctx, page.ID)
	if err != nil {
		return fmt.Errorf("notion_writer: GetPage %q: %w", page.ID, err)
	}

	// Step 2: Build existing block map by ID.
	existingAST := notionBlocksToAST(existingBlocks)
	existingByID := make(map[ast.BlockID]ast.Block, len(existingAST))
	for _, b := range existingAST {
		existingByID[b.ID] = b
	}

	// Step 3: Compose output, preserving human-edited blocks.
	output := make([]ast.Block, len(page.Blocks))
	for i, blk := range page.Blocks {
		output[i] = blk
		if existing, ok := existingByID[blk.ID]; ok {
			if existing.Owner == ast.OwnerHumanEdited || existing.Owner == ast.OwnerHumanOnly {
				output[i].Content = existing.Content
				output[i].Owner = existing.Owner
			}
		}
	}

	// Step 4: Render to Notion blocks and upsert.
	notionBlocks := astPageToNotionBlocks(ast.Page{
		ID:         page.ID,
		Manifest:   page.Manifest,
		Blocks:     output,
		Provenance: page.Provenance,
	})

	props := NotionProperties{"sourcebridge_page_id": page.ID}
	return nw.client.UpsertPage(ctx, page.ID, notionBlocks, props)
}

// WriteNotionBlocks renders a page to a JSON array of Notion block objects and
// writes the result to w. Useful for testing the render output independently.
func WriteNotionBlocks(w io.Writer, page ast.Page) error {
	blocks := astPageToNotionBlocks(page)
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(blocks)
}

// MarshalNotionBlocks renders a page to a slice of NotionBlock values.
// Exported for use by callers that need the raw block slice without encoding.
func MarshalNotionBlocks(page ast.Page) []NotionBlock {
	return astPageToNotionBlocks(page)
}

// ─────────────────────────────────────────────────────────────────────────────
// AST → Notion block rendering
// ─────────────────────────────────────────────────────────────────────────────

// managedPageCallout is the callout block emitted at the top of every managed page.
func managedPageCallout() NotionBlock {
	return NotionBlock{
		Object: "block",
		Type:   "callout",
		callout: &notionCallout{
			Icon:     notionCalloutIcon{Type: "emoji", Emoji: "ℹ️"},
			RichText: notionRichText("This page is auto-generated by SourceBridge. Edits made directly may be overwritten unless this block is human-edited."),
		},
	}
}

// astPageToNotionBlocks converts an [ast.Page] to a slice of [NotionBlock]s,
// prepending the managed-page callout.
func astPageToNotionBlocks(page ast.Page) []NotionBlock {
	out := []NotionBlock{managedPageCallout()}
	for _, blk := range page.Blocks {
		nb := astBlockToNotionBlocks(blk)
		out = append(out, nb...)
	}
	return out
}

// astBlockToNotionBlocks converts one [ast.Block] to one or more [NotionBlock]s.
// Tables expand into a parent table block + row child blocks.
func astBlockToNotionBlocks(blk ast.Block) []NotionBlock {
	nb := notionBlockFromAST(blk)
	return nb
}

func notionBlockFromAST(blk ast.Block) []NotionBlock {
	switch blk.Kind {
	case ast.BlockKindHeading:
		return []NotionBlock{notionHeadingBlock(blk)}
	case ast.BlockKindParagraph:
		return []NotionBlock{notionParagraphBlock(blk)}
	case ast.BlockKindCode:
		return []NotionBlock{notionCodeBlock(blk)}
	case ast.BlockKindTable:
		return notionTableBlocks(blk)
	case ast.BlockKindCallout:
		return []NotionBlock{notionCalloutBlock(blk)}
	case ast.BlockKindEmbed:
		return []NotionBlock{notionEmbedBlock(blk)}
	case ast.BlockKindFreeform:
		return []NotionBlock{notionFreeformBlock(blk)}
	case ast.BlockKindStaleBanner:
		return []NotionBlock{notionStaleBannerBlock(blk)}
	default:
		// Unknown kind → paragraph with raw content notation.
		return []NotionBlock{{
			Object:     "block",
			Type:       "paragraph",
			ExternalID: string(blk.ID),
			paragraph: &notionParagraph{
				RichText: notionRichText(fmt.Sprintf("[unknown block kind: %s]", blk.Kind)),
			},
		}}
	}
}

func notionHeadingBlock(blk ast.Block) NotionBlock {
	if blk.Content.Heading == nil {
		return emptyParagraphBlock(blk.ID)
	}
	level := blk.Content.Heading.Level
	if level > 3 {
		level = 3
	}
	if level < 1 {
		level = 1
	}
	notionType := fmt.Sprintf("heading_%d", level)
	h := &notionHeading{RichText: notionRichText(blk.Content.Heading.Text)}
	nb := NotionBlock{
		Object:     "block",
		Type:       notionType,
		ExternalID: string(blk.ID),
	}
	switch notionType {
	case "heading_1":
		nb.heading1 = h
	case "heading_2":
		nb.heading2 = h
	case "heading_3":
		nb.heading3 = h
	}
	return nb
}

func notionParagraphBlock(blk ast.Block) NotionBlock {
	text := ""
	if blk.Content.Paragraph != nil {
		text = blk.Content.Paragraph.Markdown
	}
	return NotionBlock{
		Object:     "block",
		Type:       "paragraph",
		ExternalID: string(blk.ID),
		paragraph:  &notionParagraph{RichText: notionRichText(text)},
	}
}

func notionCodeBlock(blk ast.Block) NotionBlock {
	lang := ""
	body := ""
	if blk.Content.Code != nil {
		lang = notionCodeLanguage(blk.Content.Code.Language)
		body = blk.Content.Code.Body
	}
	return NotionBlock{
		Object:     "block",
		Type:       "code",
		ExternalID: string(blk.ID),
		code:       &notionCode{RichText: notionRichText(body), Language: lang},
	}
}

// notionTableBlocks emits a parent table block and child table_row blocks.
// Notion requires table rows to be nested children of the table block.
// Block ID is applied to the parent table block; row blocks get derived IDs.
func notionTableBlocks(blk ast.Block) []NotionBlock {
	if blk.Content.Table == nil {
		return nil
	}
	t := blk.Content.Table
	colCount := len(t.Headers)

	// Build row blocks.
	var rows []NotionBlock
	// Header row.
	if len(t.Headers) > 0 {
		cells := make([][]notionRichTextItem, len(t.Headers))
		for i, h := range t.Headers {
			cells[i] = notionRichText(h)
		}
		rows = append(rows, NotionBlock{
			Object:   "block",
			Type:     "table_row",
			tableRow: &notionTableRow{Cells: cells},
		})
	}
	// Data rows.
	for _, row := range t.Rows {
		cells := make([][]notionRichTextItem, len(row))
		for i, cell := range row {
			cells[i] = notionRichText(cell)
		}
		rows = append(rows, NotionBlock{
			Object:   "block",
			Type:     "table_row",
			tableRow: &notionTableRow{Cells: cells},
		})
	}

	tableBlock := NotionBlock{
		Object:     "block",
		Type:       "table",
		ExternalID: string(blk.ID),
		table: &notionTable{
			TableWidth:      colCount,
			HasColumnHeader: len(t.Headers) > 0,
			HasRowHeader:    false,
		},
		children: rows,
	}
	return []NotionBlock{tableBlock}
}

func notionCalloutBlock(blk ast.Block) NotionBlock {
	emoji := calloutKindToNotionEmoji(blk.Content.Callout)
	text := ""
	if blk.Content.Callout != nil {
		text = blk.Content.Callout.Body
	}
	return NotionBlock{
		Object:     "block",
		Type:       "callout",
		ExternalID: string(blk.ID),
		callout: &notionCallout{
			Icon:     notionCalloutIcon{Type: "emoji", Emoji: emoji},
			RichText: notionRichText(text),
		},
	}
}

// calloutKindToNotionEmoji maps AST callout kinds to emoji.
func calloutKindToNotionEmoji(c *ast.CalloutContent) string {
	if c == nil {
		return "💡"
	}
	switch strings.ToLower(c.Kind) {
	case "warning", "danger":
		return "⚠️"
	case "tip":
		return "💡"
	case "note":
		return "📝"
	default:
		return "ℹ️"
	}
}

func notionEmbedBlock(blk ast.Block) NotionBlock {
	url := ""
	if blk.Content.Embed != nil {
		// Embed references are page/block IDs, not actual URLs. We encode as
		// a sourcebridge:// scheme URI so round-trip is possible.
		if blk.Content.Embed.TargetBlockID != "" {
			url = fmt.Sprintf("sourcebridge://page/%s/block/%s",
				blk.Content.Embed.TargetPageID,
				blk.Content.Embed.TargetBlockID)
		} else {
			url = fmt.Sprintf("sourcebridge://page/%s", blk.Content.Embed.TargetPageID)
		}
	}
	return NotionBlock{
		Object:     "block",
		Type:       "embed",
		ExternalID: string(blk.ID),
		embed:      &notionEmbed{URL: url},
	}
}

func notionFreeformBlock(blk ast.Block) NotionBlock {
	text := ""
	if blk.Content.Freeform != nil {
		text = blk.Content.Freeform.Raw
	}
	return NotionBlock{
		Object:     "block",
		Type:       "paragraph",
		ExternalID: string(blk.ID),
		paragraph:  &notionParagraph{RichText: notionRichText(text)},
	}
}

func notionStaleBannerBlock(blk ast.Block) NotionBlock {
	text := "This page may be out of date."
	if blk.Content.StaleBanner != nil {
		s := blk.Content.StaleBanner
		syms := strings.Join(s.TriggeringSymbols, ", ")
		text = fmt.Sprintf("This page may be out of date. Recent changes to %s (commit %s) may affect this content.", syms, s.TriggeringCommit)
		if s.RefreshURL != "" {
			text += " Refresh: " + s.RefreshURL
		}
	}
	return NotionBlock{
		Object:     "block",
		Type:       "callout",
		ExternalID: string(blk.ID),
		callout: &notionCallout{
			Icon:     notionCalloutIcon{Type: "emoji", Emoji: "⚠️"},
			RichText: notionRichText(text),
		},
	}
}

func emptyParagraphBlock(id ast.BlockID) NotionBlock {
	return NotionBlock{
		Object:     "block",
		Type:       "paragraph",
		ExternalID: string(id),
		paragraph:  &notionParagraph{RichText: notionRichText("")},
	}
}

// notionCodeLanguage maps common language IDs to Notion's supported language list.
// Notion supports a fixed set: https://developers.notion.com/reference/block#code
func notionCodeLanguage(lang string) string {
	supported := map[string]string{
		"abap":       "abap",
		"arduino":    "arduino",
		"bash":       "bash",
		"sh":         "bash",
		"shell":      "bash",
		"basic":      "basic",
		"c":          "c",
		"clojure":    "clojure",
		"coffeescript": "coffeescript",
		"cpp":        "c++",
		"c++":        "c++",
		"csharp":     "c#",
		"cs":         "c#",
		"css":        "css",
		"dart":       "dart",
		"diff":       "diff",
		"docker":     "docker",
		"elixir":     "elixir",
		"elm":        "elm",
		"erlang":     "erlang",
		"flow":       "flow",
		"fortran":    "fortran",
		"fsharp":     "f#",
		"gherkin":    "gherkin",
		"glsl":       "glsl",
		"go":         "go",
		"golang":     "go",
		"graphql":    "graphql",
		"groovy":     "groovy",
		"haskell":    "haskell",
		"html":       "html",
		"java":       "java",
		"javascript": "javascript",
		"js":         "javascript",
		"json":       "json",
		"julia":      "julia",
		"kotlin":     "kotlin",
		"latex":      "latex",
		"less":       "less",
		"lisp":       "lisp",
		"livescript": "livescript",
		"lua":        "lua",
		"makefile":   "makefile",
		"markdown":   "markdown",
		"markup":     "markup",
		"matlab":     "matlab",
		"mermaid":    "mermaid",
		"nix":        "nix",
		"objective-c": "objective-c",
		"ocaml":      "ocaml",
		"pascal":     "pascal",
		"perl":       "perl",
		"php":        "php",
		"powershell": "powershell",
		"prolog":     "prolog",
		"protobuf":   "protobuf",
		"python":     "python",
		"py":         "python",
		"r":          "r",
		"reason":     "reason",
		"ruby":       "ruby",
		"rust":       "rust",
		"sass":       "sass",
		"scala":      "scala",
		"scheme":     "scheme",
		"scss":       "scss",
		"sql":        "sql",
		"swift":      "swift",
		"typescript": "typescript",
		"ts":         "typescript",
		"vbnet":      "vb.net",
		"verilog":    "verilog",
		"vhdl":       "vhdl",
		"webassembly": "webassembly",
		"xml":        "xml",
		"yaml":       "yaml",
		"yml":        "yaml",
	}
	if v, ok := supported[strings.ToLower(lang)]; ok {
		return v
	}
	return "plain text"
}

// ─────────────────────────────────────────────────────────────────────────────
// Notion blocks → AST (read-back for reconciliation)
// ─────────────────────────────────────────────────────────────────────────────

// notionBlocksToAST converts a slice of Notion blocks back to [ast.Block] values
// for reconciliation. The conversion is partial — it recovers ID, Kind, Owner,
// and enough content for fingerprinting.
func notionBlocksToAST(blocks []NotionBlock) []ast.Block {
	var result []ast.Block
	for _, nb := range blocks {
		blk, ok := notionBlockToAST(nb)
		if !ok {
			continue
		}
		result = append(result, blk)
	}
	return result
}

// notionBlockToAST converts one NotionBlock to an ast.Block.
// Returns (block, true) when the block has a SourceBridge external_id and
// therefore participates in reconciliation. Returns (zero, false) for the
// managed-page callout (which has no external_id) and for table_row children.
func notionBlockToAST(nb NotionBlock) (ast.Block, bool) {
	if nb.ExternalID == "" {
		return ast.Block{}, false
	}

	blk := ast.Block{
		ID:    ast.BlockID(nb.ExternalID),
		Owner: ast.OwnerGenerated, // default; owner is not stored in Notion blocks
	}

	switch nb.Type {
	case "heading_1":
		blk.Kind = ast.BlockKindHeading
		text := notionHeadingText(nb, 1)
		blk.Content = ast.BlockContent{
			Heading: &ast.HeadingContent{Level: 1, Text: text},
		}
	case "heading_2":
		blk.Kind = ast.BlockKindHeading
		text := notionHeadingText(nb, 2)
		blk.Content = ast.BlockContent{
			Heading: &ast.HeadingContent{Level: 2, Text: text},
		}
	case "heading_3":
		blk.Kind = ast.BlockKindHeading
		text := notionHeadingText(nb, 3)
		blk.Content = ast.BlockContent{
			Heading: &ast.HeadingContent{Level: 3, Text: text},
		}
	case "paragraph":
		blk.Kind = ast.BlockKindParagraph
		text := notionRichTextToString(notionParagraphRichText(nb))
		blk.Content = ast.BlockContent{
			Paragraph: &ast.ParagraphContent{Markdown: text},
		}
	case "code":
		blk.Kind = ast.BlockKindCode
		body := ""
		lang := ""
		if nb.code != nil {
			body = notionRichTextToString(nb.code.RichText)
			lang = nb.code.Language
		}
		blk.Content = ast.BlockContent{
			Code: &ast.CodeContent{Language: lang, Body: body},
		}
	case "callout":
		blk.Kind = ast.BlockKindCallout
		text := ""
		if nb.callout != nil {
			text = notionRichTextToString(nb.callout.RichText)
		}
		blk.Content = ast.BlockContent{
			Callout: &ast.CalloutContent{Kind: "note", Body: text},
		}
	case "table":
		blk.Kind = ast.BlockKindTable
		// Table content is partially recovered from the table block's children.
		blk.Content = notionTableToAST(nb)
	case "embed":
		blk.Kind = ast.BlockKindEmbed
		url := ""
		if nb.embed != nil {
			url = nb.embed.URL
		}
		blk.Content = notionEmbedURLToAST(url)
	default:
		blk.Kind = ast.BlockKindFreeform
		blk.Content = ast.BlockContent{
			Freeform: &ast.FreeformContent{Raw: nb.Type},
		}
	}

	return blk, true
}

func notionHeadingText(nb NotionBlock, level int) string {
	var rt []notionRichTextItem
	switch level {
	case 1:
		if nb.heading1 != nil {
			rt = nb.heading1.RichText
		}
	case 2:
		if nb.heading2 != nil {
			rt = nb.heading2.RichText
		}
	case 3:
		if nb.heading3 != nil {
			rt = nb.heading3.RichText
		}
	}
	return notionRichTextToString(rt)
}

func notionParagraphRichText(nb NotionBlock) []notionRichTextItem {
	if nb.paragraph != nil {
		return nb.paragraph.RichText
	}
	return nil
}

func notionRichTextToString(rt []notionRichTextItem) string {
	var sb strings.Builder
	for _, item := range rt {
		sb.WriteString(item.Text.Content)
	}
	return sb.String()
}

func notionTableToAST(nb NotionBlock) ast.BlockContent {
	var headers []string
	var rows [][]string

	for i, child := range nb.children {
		if child.Type != "table_row" || child.tableRow == nil {
			continue
		}
		cells := make([]string, len(child.tableRow.Cells))
		for j, cell := range child.tableRow.Cells {
			cells[j] = notionRichTextToString(cell)
		}
		if i == 0 {
			headers = cells
		} else {
			rows = append(rows, cells)
		}
	}
	return ast.BlockContent{
		Table: &ast.TableContent{Headers: headers, Rows: rows},
	}
}

// notionEmbedURLToAST parses a sourcebridge:// embed URL back to EmbedContent.
func notionEmbedURLToAST(url string) ast.BlockContent {
	// sourcebridge://page/<pageID>/block/<blockID>
	if strings.HasPrefix(url, "sourcebridge://page/") {
		rest := strings.TrimPrefix(url, "sourcebridge://page/")
		parts := strings.SplitN(rest, "/block/", 2)
		if len(parts) == 2 {
			return ast.BlockContent{
				Embed: &ast.EmbedContent{
					TargetPageID:  parts[0],
					TargetBlockID: ast.BlockID(parts[1]),
				},
			}
		}
		return ast.BlockContent{
			Embed: &ast.EmbedContent{TargetPageID: rest},
		}
	}
	return ast.BlockContent{
		Embed: &ast.EmbedContent{TargetPageID: url},
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// JSON output helper
// ─────────────────────────────────────────────────────────────────────────────

// MarshalNotionPage renders a page to a JSON-encoded bytes.Buffer.
// The top-level JSON is an array of block objects.
func MarshalNotionPage(page ast.Page) ([]byte, error) {
	var buf bytes.Buffer
	if err := WriteNotionBlocks(&buf, page); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// Compile-time interface check.
var _ NotionClient = (*MemoryNotionClient)(nil)
