name = "sourcebridge-telemetry"
main = "src/worker.ts"
compatibility_date = "2024-12-01"

routes = [
  { pattern = "telemetry.sourcebridge.ai/*", zone_name = "sourcebridge.ai" }
]

[[d1_databases]]
binding = "DB"
database_name = "sourcebridge-telemetry"
database_id = "3b91def6-5729-4562-988f-24eeb976fc24"

[vars]
POSTHOG_API_KEY = "phc_vhLdm8b5dYsYUi44n6Dm2aH2nFqnFyupre8FkEC6fDhx"
POSTHOG_HOST = "https://us.i.posthog.com"
