// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 SourceBridge Contributors

package llm

import "time"

// JobStore is the persistence contract for LLM jobs. Both the in-memory
// implementation in memstore.go and the SurrealDB implementation in
// internal/db/llm_job_store.go satisfy this interface.
//
// The store is deliberately narrow: it knows nothing about concurrency,
// retries, dedupe, or progress debouncing — all of that lives in the
// orchestrator package. The store only persists state and answers queries.
type JobStore interface {
	// Create inserts a new job with status pending. The caller supplies an
	// id (typically a UUID generated by the orchestrator); the store may
	// return the hydrated record or a store-specific error.
	Create(job *Job) (*Job, error)

	// Update writes the supplied fields back to the store. Callers must
	// pass the full job record; partial updates happen via the dedicated
	// setters below to keep the write path predictable.
	Update(job *Job) error

	// GetByID returns a single job by id, or nil when it does not exist.
	GetByID(id string) *Job

	// GetActiveByTargetKey returns the currently-active (pending or
	// generating) job for a given target key, or nil. Used by the
	// orchestrator's DB-level dedupe path.
	GetActiveByTargetKey(targetKey string) *Job

	// ListActive returns every job currently in pending or generating
	// state. Ordered by updated_at descending. Powers the Monitor page's
	// "Now running" zone.
	ListActive(filter ListFilter) []*Job

	// ListRecent returns terminal jobs (ready, failed, cancelled) whose
	// updated_at is within the supplied window, ordered by updated_at
	// descending. Capped by filter.Limit (default 50 when zero).
	ListRecent(filter ListFilter, since time.Time) []*Job

	// SetStatus transitions a job to a new status and updates the
	// appropriate timestamp columns (started_at on generating,
	// completed_at on terminal states).
	SetStatus(id string, status JobStatus) error

	// SetProgress writes a progress update. Callers are expected to
	// debounce upstream; the store writes every call it receives.
	SetProgress(id string, progress float64, phase, message string) error

	// SetError records a terminal failure with classified code + message.
	// It also transitions the job to StatusFailed and stamps completed_at.
	SetError(id string, code, message string) error

	// SetTokens records the final token usage for a job.
	SetTokens(id string, input, output int) error

	// SetSnapshotBytes records the serialized input size.
	SetSnapshotBytes(id string, bytes int) error

	// IncrementRetry bumps the retry counter on an existing job without
	// changing its status. Called between retry attempts.
	IncrementRetry(id string) error
}

// ListFilter narrows the result of the list endpoints. Zero-value filters
// mean "no restriction" on that field.
type ListFilter struct {
	Subsystem  Subsystem
	JobType    string
	RepoID     string
	TargetKey  string
	Statuses   []JobStatus
	Limit      int
}
